// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.rest.model;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import dev.rsdlang.sample.server.service.model.PatchableRecord;

public class PatchableRecordDataImpl extends _BaseDataImpl implements PatchableRecord.Data {
	PatchableRecordDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public String version() {
		return _JsonUtils.mapString(data, "version");
	}

	@Override
	public String value() {
		return _JsonUtils.mapString(data, "value");
	}

	public static PatchableRecord.Data of(JsonObject obj) {
		return new PatchableRecordDataImpl(obj);
	}

	public String toString() {
		return "%s[%s=%s@%s=%s]".formatted(getClass().getSimpleName(), "key", key(), "version", version());
	}

	public static class DataBuilderImpl implements PatchableRecord.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public PatchableRecord.DataBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		@Override
		public PatchableRecord.DataBuilder version(String version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public PatchableRecord.DataBuilder value(String value) {
			if (value == null) {
				return this;
			}
			$builder.add("value", value);
			return this;
		}

		public PatchableRecord.Data build() {
			return new PatchableRecordDataImpl($builder.build());
		}
	}

	public static PatchableRecord.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
