import { CompositeGeneratorNode, NL } from 'langium/generate';
import { ArtifactGeneratorConfig } from './artifact-generator.js';
import { MBuiltinType } from './model.js';

export type TypescriptClientAPIGeneratorConfig = ArtifactGeneratorConfig & {
	targetFolder: string;
	allowImportingTsExtensions?: boolean;
};

export function isTypescriptClientAPIGeneratorConfig(
	config: ArtifactGeneratorConfig,
): config is TypescriptClientAPIGeneratorConfig {
	return 'targetFolder' in config && typeof config.targetFolder === 'string';
}

export type TypescriptFetchClientGeneratorConfig = ArtifactGeneratorConfig & {
	targetFolder: string;
	apiNamespacePath: string;
	allowImportingTsExtensions?: boolean;
	contentTypeEncodings?: ('application/json' | 'application/vnd.msgpack')[];
};

export function isTypescriptFetchClientGeneratorConfig(
	config: ArtifactGeneratorConfig,
): config is TypescriptFetchClientGeneratorConfig {
	return (
		'apiNamespacePath' in config &&
		typeof config.apiNamespacePath === 'string' &&
		'targetFolder' in config &&
		typeof config.targetFolder === 'string'
	);
}

export class TypescriptImportCollector {
	private aliasCount = 0;
	private readonly fqnTypes = new Map<string, string>();
	private readonly importTypes = new Map<string, Set<string>>();
	private readonly typeOnlyTypes = new Set<string>();
	private readonly allowImportingTsExtensions: boolean;
	private readonly filename: string;

	constructor(config: TypescriptClientAPIGeneratorConfig, filename: string) {
		this.allowImportingTsExtensions = config.allowImportingTsExtensions ?? false;
		this.filename = filename;
	}

	importType(type: string, typeOnly: boolean) {
		const parts = type.split(':');
		return this._importType(parts[0], parts[1], typeOnly);
	}

	public appendImportGroups(node: CompositeGeneratorNode) {
		this.importTypes.forEach((v, p) => {
			// skip self imports, these can happen when a type references itself, either directly or indirectly. In this case we can just use the type without importing it.
			if (p === `./${this.filename}`) {
				return;
			}
			if (!this.allowImportingTsExtensions) {
				p = p.replace(/\.ts$/, '.js');
			}
			const importedTypes = [...v];
			if (importedTypes.find(i => !this.typeOnlyTypes.has(i))) {
				node.append(
					`import { ${importedTypes
						.sort((a, b) => a.localeCompare(b))
						.map(v => (this.typeOnlyTypes.has(v) ? `type ${v}` : v))
						.join(', ')} } from '${p}';`,
					NL,
				);
			} else {
				node.append(`import type { ${importedTypes.sort((a, b) => a.localeCompare(b)).join(', ')} } from '${p}';`, NL);
			}
		});

		node.appendNewLineIf(this.importTypes.size > 0);
	}

	private _importType(type: string, path: string, typeOnly: boolean) {
		let resultType = type;
		if (this.fqnTypes.get(type) == null) {
			this.fqnTypes.set(type, path);
		} else if (path !== this.fqnTypes.get(type)) {
			resultType = `${type}${(this.aliasCount++).toFixed()}`;
			type = type + ' as ' + resultType;
		}

		const types = this.importTypes.get(path) ?? new Set();
		this.importTypes.set(path, types);
		types.add(type);
		if (typeOnly) {
			this.typeOnlyTypes.add(type);
		}

		return resultType;
	}
}

export function generateCompilationUnit(importCollector: TypescriptImportCollector, content: CompositeGeneratorNode) {
	const node = new CompositeGeneratorNode();
	node.append('// Generated by RSD - Do not modify', NL);
	importCollector.appendImportGroups(node);
	node.append(content);
	return node;
}

export function builtinToType(type: MBuiltinType, fqn: (v: string, typeOnly: boolean) => string, relativePath: string) {
	if (type === 'boolean') {
		return fqn(`RSDBoolean:${relativePath}_Builtins.ts`, true);
	} else if (type === 'string') {
		return fqn(`RSDString:${relativePath}_Builtins.ts`, true);
	} else if (type === 'short') {
		return fqn(`RSDShort:${relativePath}_Builtins.ts`, true);
	} else if (type === 'int') {
		return fqn(`RSDInt:${relativePath}_Builtins.ts`, true);
	} else if (type === 'long') {
		return fqn(`RSDLong:${relativePath}_Builtins.ts`, true);
	} else if (type === 'float') {
		return fqn(`RSDFloat:${relativePath}_Builtins.ts`, true);
	} else if (type === 'double') {
		return fqn(`RSDDouble:${relativePath}_Builtins.ts`, true);
	} else if (type === 'local-date') {
		return fqn(`RSDLocalDate:${relativePath}_Builtins.ts`, true);
	} else if (type === 'local-date-time') {
		return fqn(`RSDLocalDateTime:${relativePath}_Builtins.ts`, true);
	} else if (type === 'local-time') {
		return fqn(`RSDLocalTime:${relativePath}_Builtins.ts`, true);
	} else if (type === 'offset-date-time') {
		return fqn(`RSDOffsetDateTime:${relativePath}_Builtins.ts`, true);
	} else {
		return fqn(`RSDZonedDateTime:${relativePath}_Builtins.ts`, true);
	}
}

export function builtinTypeGuard(
	type: MBuiltinType,
	fqn: (v: string, typeOnly: boolean) => string,
	relativePath: string,
): string {
	if (type === 'boolean') {
		return fqn(`isRSDBoolean:${relativePath}_Builtins.ts`, false);
	} else if (type === 'string') {
		return fqn(`isRSDString:${relativePath}_Builtins.ts`, false);
	} else if (type === 'short') {
		return fqn(`isRSDShort:${relativePath}_Builtins.ts`, false);
	} else if (type === 'int') {
		return fqn(`isRSDInt:${relativePath}_Builtins.ts`, false);
	} else if (type === 'long') {
		return fqn(`isRSDLong:${relativePath}_Builtins.ts`, false);
	} else if (type === 'float') {
		return fqn(`isRSDFloat:${relativePath}_Builtins.ts`, false);
	} else if (type === 'double') {
		return fqn(`isRSDDouble:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-date-time') {
		return fqn(`isRSDLocalDateTime:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-date') {
		return fqn(`isRSDLocalDate:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-time') {
		return fqn(`isRSDLocalTime:${relativePath}_Builtins.ts`, false);
	} else if (type === 'offset-date-time') {
		return fqn(`isRSDOffsetDateTime:${relativePath}_Builtins.ts`, false);
	} else {
		return fqn(`isRSDZonedDateTime:${relativePath}_Builtins.ts`, false);
	}
}

export function builtinFromJsonTypeGuard(type: MBuiltinType, fqn: (v: string, typeOnly: boolean) => string) {
	if (type === 'boolean') {
		return fqn('isBoolean:../_type-utils.ts', false);
	} else if (type === 'double' || type === 'float' || type === 'int' || type === 'short') {
		return fqn('isNumber:../_type-utils.ts', false);
	} else if (type === 'long') {
		return fqn('isNumeric:../_type-utils.ts', false);
	} else {
		return fqn('isString:../_type-utils.ts', false);
	}
}

export function builtinFromJSON(
	type: MBuiltinType,
	fqn: (v: string, typeOnly: boolean) => string,
	relativePath: string,
): string {
	if (type === 'local-date-time') {
		return fqn(`RSDLocalDateTimeFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-date') {
		return fqn(`RSDLocalDateFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-time') {
		return fqn(`RSDLocalTimeFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'offset-date-time') {
		return fqn(`RSDOffsetDateTimeFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'zoned-date-time') {
		return fqn(`RSDZonedDateTimeFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'long') {
		return fqn(`RSDLongFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'double') {
		return fqn(`RSDDoubleFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'float') {
		return fqn(`RSDFloatFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'int') {
		return fqn(`RSDIntFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'short') {
		return fqn(`RSDShortFromJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'boolean') {
		return fqn(`RSDBooleanFromJSON:${relativePath}_Builtins.ts`, false);
	} else {
		return fqn(`RSDStringFromJSON:${relativePath}_Builtins.ts`, false);
	}
}

export function builtinToJSON(
	type: MBuiltinType,
	fqn: (v: string, typeOnly: boolean) => string,
	relativePath: string,
): string {
	if (type === 'local-date-time') {
		return fqn(`RSDLocalDateTimeToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-date') {
		return fqn(`RSDLocalDateToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'local-time') {
		return fqn(`RSDLocalTimeToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'offset-date-time') {
		return fqn(`RSDOffsetDateTimeToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'zoned-date-time') {
		return fqn(`RSDZonedDateTimeToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'long') {
		return fqn(`RSDLongToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'double') {
		return fqn(`RSDDoubleToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'float') {
		return fqn(`RSDFloatToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'int') {
		return fqn(`RSDIntToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'short') {
		return fqn(`RSDShortToJSON:${relativePath}_Builtins.ts`, false);
	} else if (type === 'boolean') {
		return fqn(`RSDBooleanToJSON:${relativePath}_Builtins.ts`, false);
	} else {
		return fqn(`RSDStringToJSON:${relativePath}_Builtins.ts`, false);
	}
}
