// Generated by RSD - Do not modify
package dev.rsdlang.sample.client;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.ZoneId;

import dev.rsdlang.sample.client.model.SampleEnum;
import dev.rsdlang.sample.client.model.SimpleRecord;

public interface SampleServiceService extends BaseService {
	public boolean getBoolean();

	public short getShort();

	public int getInt();

	public long getLong();

	public float getFloat();

	public double getDouble();

	public String getString();

	public LocalDate getLocalDate();

	public LocalDateTime getLocalDateTime();

	public ZonedDateTime getZonedDateTime();

	public ZoneId getScalar();

	public SampleEnum getEnum();

	public void voidOperation();

	public void errorOperation() throws SampleErrorException;

	public void multiErrorOperation() throws SampleErrorException, SampleErrorException;

	public SimpleRecord.Data getSimpleRecord(String key);

	public SimpleRecord.Data getSimpleRecordWithError(String key) throws SampleErrorException;

}
