// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.service.model;

import java.util.function.Function;
import java.util.List;

public interface RecordOfRecords {

	public interface Data extends _Base.BaseData, RecordOfRecords {
		public SimpleRecord_Basic.Data value();

		public SimpleRecord_Basic.Data value_Null();

		public SimpleRecord_Basic.Data value_Opt();

		public SimpleRecord_Basic.Data value_Opt_Null();

		public List<SimpleRecord_Basic.Data> list();

		public List<SimpleRecord_Basic.Data> list_Null();

		public List<SimpleRecord_Basic.Data> list_Opt();

		public List<SimpleRecord_Basic.Data> list_Opt_Null();

	}

	public interface DataBuilder extends _Base.BaseDataBuilder<RecordOfRecords.Data> {
		public DataBuilder value(SimpleRecord_Basic.Data value);

		public <T extends SimpleRecord_Basic.DataBuilder> DataBuilder withValue(Class<T> clazz, Function<T, SimpleRecord_Basic.Data> block);

		public DataBuilder value_Null(SimpleRecord_Basic.Data value_Null);

		public <T extends SimpleRecord_Basic.DataBuilder> DataBuilder withValue_Null(Class<T> clazz, Function<T, SimpleRecord_Basic.Data> block);

		public DataBuilder value_Opt(SimpleRecord_Basic.Data value_Opt);

		public <T extends SimpleRecord_Basic.DataBuilder> DataBuilder withValue_Opt(Class<T> clazz, Function<T, SimpleRecord_Basic.Data> block);

		public DataBuilder value_Opt_Null(SimpleRecord_Basic.Data value_Opt_Null);

		public <T extends SimpleRecord_Basic.DataBuilder> DataBuilder withValue_Opt_Null(Class<T> clazz, Function<T, SimpleRecord_Basic.Data> block);

		public DataBuilder list(List<SimpleRecord_Basic.Data> list);

		public DataBuilder list_Null(List<SimpleRecord_Basic.Data> list_Null);

		public DataBuilder list_Opt(List<SimpleRecord_Basic.Data> list_Opt);

		public DataBuilder list_Opt_Null(List<SimpleRecord_Basic.Data> list_Opt_Null);

	}
}
