// Generated by RSD - Do not modify
import { decodeResponse, encodeAsciiString, encodeValue, encodingType, safeExecute, type ServiceProps } from './_fetch-type-utils.js';
import { api } from '../index.js';

export function createScalarSubstition_ServiceService(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService {
	return {
		get: fnGet(props),
		list: fnList(props),
		post: fnPost(props),
		postOpt: fnPostOpt(props),
		postNull: fnPostNull(props),
		postOptNull: fnPostOptNull(props),
		postList: fnPostList(props),
		postListOpt: fnPostListOpt(props),
		postListNull: fnPostListNull(props),
		postListOptNull: fnPostListOptNull(props),
		query: fnQuery(props),
		queryOpt: fnQueryOpt(props),
		queryNull: fnQueryNull(props),
		queryOptNull: fnQueryOptNull(props),
		queryList: fnQueryList(props),
		queryListOpt: fnQueryListOpt(props),
		queryListNull: fnQueryListNull(props),
		queryListOptNull: fnQueryListOptNull(props),
		header: fnHeader(props),
		headerOpt: fnHeaderOpt(props),
		headerNull: fnHeaderNull(props),
		headerOptNull: fnHeaderOptNull(props),
		headerList: fnHeaderList(props),
		headerListOpt: fnHeaderListOpt(props),
		headerListNull: fnHeaderListNull(props),
		headerListOptNull: fnHeaderListOptNull(props),
		fail: fnFail(props),
	};
}
function fnGet(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['get'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async () => {
		try {
			const $init = (await preFetch?.('get')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/get`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.RangeFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('get', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('get', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('get');
		}
	};
}

function fnList(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['list'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async () => {
		try {
			const $init = (await preFetch?.('list')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/list`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, v => api.utils.isTypedArray(v, api.utils.isString));
				const $result = $data.map(api.model.RangeFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('list', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('list', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('list');
		}
	};
}

function fnPost(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['post'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range) => {
		try {
			const $init = (await preFetch?.('post')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/post`;
			const $body = encodeValue(encodingType(props), api.model.RangeToJSON(range));
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.RangeFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('post', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('post', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('post');
		}
	};
}

function fnPostOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range) => {
		try {
			const $init = (await preFetch?.('postOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postOpt`;
			const $body = encodeValue(encodingType(props), range ? api.model.RangeToJSON(range) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postOpt');
		}
	};
}

function fnPostNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('postNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postNull`;
			const $body = encodeValue(encodingType(props), range ? api.model.RangeToJSON(range) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postNull');
		}
	};
}

function fnPostOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('postOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postOptNull`;
			const $body = encodeValue(encodingType(props), range ? api.model.RangeToJSON(range) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postOptNull');
		}
	};
}

function fnPostList(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postList'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('postList')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postList`;
			const $body = encodeValue(encodingType(props), range.map(api.model.RangeToJSON));
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, v => api.utils.isTypedArray(v, api.utils.isString));
				const $result = $data.map(api.model.RangeFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postList', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postList', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postList');
		}
	};
}

function fnPostListOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postListOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('postListOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postListOpt`;
			const $body = encodeValue(encodingType(props), range ? range.map(api.model.RangeToJSON) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postListOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postListOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postListOpt');
		}
	};
}

function fnPostListNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postListNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('postListNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postListNull`;
			const $body = encodeValue(encodingType(props), range ? range.map(api.model.RangeToJSON) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postListNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postListNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postListNull');
		}
	};
}

function fnPostListOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['postListOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('postListOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/postListOptNull`;
			const $body = encodeValue(encodingType(props), range ? range.map(api.model.RangeToJSON) : range);
			const $response = await fetchAPI($path, { ...$init, method: 'POST', body: $body });
			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('postListOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('postListOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('postListOptNull');
		}
	};
}

function fnQuery(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['query'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range) => {
		try {
			const $init = (await preFetch?.('query')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			$param.append('range', api.model.RangeToJSON(range));
			const $path = `${baseUrl}/api/scalarsubstitution/query?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.RangeFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('query', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('query', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('query');
		}
	};
}

function fnQueryOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range) => {
		try {
			const $init = (await preFetch?.('queryOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== undefined) {
				$param.append('range', api.model.RangeToJSON(range));
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryOpt?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryOpt');
		}
	};
}

function fnQueryNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('queryNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== null) {
				$param.append('range', api.model.RangeToJSON(range));
			} else {
				$headers.append('range', 'null');
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryNull?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryNull');
		}
	};
}

function fnQueryOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('queryOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== undefined && range !== null) {
				$param.append('range', api.model.RangeToJSON(range));
			} else if(range === null) {
				$headers.append('range', 'null');
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryOptNull?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryOptNull');
		}
	};
}

function fnQueryList(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryList'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('queryList')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			range.forEach($entry => {
				$param.append('range', api.model.RangeToJSON($entry));
			});
			const $path = `${baseUrl}/api/scalarsubstitution/queryList?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, v => api.utils.isTypedArray(v, api.utils.isString));
				const $result = $data.map(api.model.RangeFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryList', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryList', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryList');
		}
	};
}

function fnQueryListOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryListOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('queryListOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== undefined) {
				range.forEach($entry => {
					$param.append('range', api.model.RangeToJSON($entry));
				});
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryListOpt?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryListOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryListOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryListOpt');
		}
	};
}

function fnQueryListNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryListNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('queryListNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== null) {
				range.forEach($entry => {
					$param.append('range', api.model.RangeToJSON($entry));
				});
			} else {
				$headers.append('range', 'null');
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryListNull?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryListNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryListNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryListNull');
		}
	};
}

function fnQueryListOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['queryListOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('queryListOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $param = new URLSearchParams();
			if (range !== undefined && range !== null) {
				range.forEach($entry => {
					$param.append('range', api.model.RangeToJSON($entry));
				});
			} else if(range === null) {
				$headers.append('range', 'null');
			}
			const $path = `${baseUrl}/api/scalarsubstitution/queryListOptNull?${$param.toString()}`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('queryListOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('queryListOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('queryListOptNull');
		}
	};
}

function fnHeader(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['header'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range) => {
		try {
			const $init = (await preFetch?.('header')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$headers.append('range', encodeAsciiString(api.model.RangeToJSON(range)));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/header`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.RangeFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('header', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('header', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('header');
		}
	};
}

function fnHeaderOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range) => {
		try {
			const $init = (await preFetch?.('headerOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== undefined) {
				$headers.append('range', encodeAsciiString(api.model.RangeToJSON(range)));
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerOpt`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerOpt');
		}
	};
}

function fnHeaderNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('headerNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== null) {
				$headers.append('range', encodeAsciiString(api.model.RangeToJSON(range)));
			} else {
				$headers.append('range', 'null');
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerNull`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerNull');
		}
	};
}

function fnHeaderOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range | null) => {
		try {
			const $init = (await preFetch?.('headerOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== undefined && range !== null) {
				$headers.append('range', encodeAsciiString(api.model.RangeToJSON(range)));
			} else if (range === null) {
				$headers.append('range', 'null');
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerOptNull`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerOptNull');
		}
	};
}

function fnHeaderList(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerList'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('headerList')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			range.forEach($entry => {
				$headers.append('range', encodeAsciiString(api.model.RangeToJSON($entry)));
			});
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerList`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, v => api.utils.isTypedArray(v, api.utils.isString));
				const $result = $data.map(api.model.RangeFromJSON);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerList', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerList', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerList');
		}
	};
}

function fnHeaderListOpt(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerListOpt'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[]) => {
		try {
			const $init = (await preFetch?.('headerListOpt')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== undefined) {
				range.forEach($entry => {
					$headers.append('range', encodeAsciiString(api.model.RangeToJSON($entry)));
				});
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerListOpt`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerListOpt', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerListOpt', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerListOpt');
		}
	};
}

function fnHeaderListNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerListNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('headerListNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== null) {
				range.forEach($entry => {
					$headers.append('range', encodeAsciiString(api.model.RangeToJSON($entry)));
				});
			} else {
				$headers.append('range', 'null');
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerListNull`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerListNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerListNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerListNull');
		}
	};
}

function fnHeaderListOptNull(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['headerListOptNull'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onCatch, final } = lifecycleHandlers;
	return async (range?: api.model.Range[] | null) => {
		try {
			const $init = (await preFetch?.('headerListOptNull')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			if (range !== undefined && range !== null) {
				range.forEach($entry => {
					$headers.append('range', encodeAsciiString(api.model.RangeToJSON($entry)));
				});
			} else if (range === null) {
				$headers.append('range', 'null');
			}
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/headerListOptNull`;
			const $response = await fetchAPI($path, { ...$init, method: 'GET' });

			if ($response.status === 200) {
				const $data = await decodeResponse($response, api.utils.isString);
				const $result = api.model.NilResultFromJSON($data);
				return safeExecute(api.result.OK($result), () => onSuccess?.('headerListOptNull', $result));
			}
			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('headerListOptNull', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('headerListOptNull');
		}
	};
}

function fnFail(props: ServiceProps<api.service.ErrorType>): api.service.ScalarSubstition_ServiceService['fail'] {
	const { baseUrl, fetchAPI = fetch, lifecycleHandlers = {} } = props;
	const { preFetch, onSuccess, onError, onCatch, final } = lifecycleHandlers;
	return async () => {
		try {
			const $init = (await preFetch?.('fail')) ?? {};
			const $headers = new Headers($init.headers ?? {});
			$headers.append('Accept', encodingType(props));
			$headers.append('Content-Type', encodingType(props));
			$init.headers = $headers;

			const $path = `${baseUrl}/api/scalarsubstitution/fail`;
			const $response = await fetchAPI($path, { ...$init, method: 'POST' });

			if ($response.status === 200) {
				return safeExecute(api.result.OK(api.result.Void), () => onSuccess?.('fail', api.result.Void));
			}
			if ($response.status === 400) {
				if($response.headers.get('X-RSD-Error-Type') === 'SampleErrorScalarSub') {
					const $data = await decodeResponse($response, api.utils.isString);
					const $result = api.model.RangeFromJSON($data);
					const err = {
						_type: 'SampleErrorScalarSub',
						data: $result,
					} as const;
					return safeExecute(api.result.ERR(err), () => onError?.('fail', err));
				}
			}

			const err = { _type: '_Status', message: await $response.text(), status: $response.status } as const;
			return api.result.ERR(err);
		} catch (e) {
			onCatch?.('fail', e);
			const ee = e instanceof Error ? e : new Error('', { cause: e });
			const err = { _type: '_Native', message: ee.message, error: ee } as const;
			return api.result.ERR(err);
		} finally {
			final?.('fail');
		}
	};
}

