// Generated by RSD - Do not modify
package dev.rsdlang.sample.client.impl.model.json;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import dev.rsdlang.sample.client.model.SimpleRecord_Basic_List_Null;

public class SimpleRecord_Basic_List_NullDataImpl extends _BaseDataImpl implements SimpleRecord_Basic_List_Null.Data {
	SimpleRecord_Basic_List_NullDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public Optional<List<Boolean>> valueBoolean() {
		return _JsonUtils.mapNullBooleans(data, "valueBoolean");
	}

	@Override
	public Optional<List<Short>> valueShort() {
		return _JsonUtils.mapNullShorts(data, "valueShort");
	}

	@Override
	public Optional<List<Integer>> valueInt() {
		return _JsonUtils.mapNullInts(data, "valueInt");
	}

	@Override
	public Optional<List<Long>> valueLong() {
		return _JsonUtils.mapNullLongs(data, "valueLong");
	}

	@Override
	public Optional<List<Float>> valueFloat() {
		return _JsonUtils.mapNullFloats(data, "valueFloat");
	}

	@Override
	public Optional<List<Double>> valueDouble() {
		return _JsonUtils.mapNullDoubles(data, "valueDouble");
	}

	@Override
	public Optional<List<String>> valueString() {
		return _JsonUtils.mapNullStrings(data, "valueString");
	}

	@Override
	public Optional<List<LocalDate>> valueLocalDate() {
		return _JsonUtils.mapNullLocalDates(data, "valueLocalDate");
	}

	@Override
	public Optional<List<LocalDateTime>> valueLocalDateTime() {
		return _JsonUtils.mapNullLocalDateTimes(data, "valueLocalDateTime");
	}

	@Override
	public Optional<List<LocalTime>> valueLocalTime() {
		return _JsonUtils.mapNullLocalTimes(data, "valueLocalTime");
	}

	@Override
	public Optional<List<ZonedDateTime>> valueZonedDateTime() {
		return _JsonUtils.mapNullZonedDateTimes(data, "valueZonedDateTime");
	}

	public static SimpleRecord_Basic_List_Null.Data of(JsonObject obj) {
		return new SimpleRecord_Basic_List_NullDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements SimpleRecord_Basic_List_Null.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueBoolean(List<Boolean> valueBoolean) {
			if (valueBoolean == null) {
				$builder.addNull("valueBoolean");
				return this;
			}
			$builder.add("valueBoolean", _JsonUtils.toJsonBooleanArray(valueBoolean));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueShort(List<Short> valueShort) {
			if (valueShort == null) {
				$builder.addNull("valueShort");
				return this;
			}
			$builder.add("valueShort", _JsonUtils.toJsonShortArray(valueShort));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueInt(List<Integer> valueInt) {
			if (valueInt == null) {
				$builder.addNull("valueInt");
				return this;
			}
			$builder.add("valueInt", _JsonUtils.toJsonIntArray(valueInt));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueLong(List<Long> valueLong) {
			if (valueLong == null) {
				$builder.addNull("valueLong");
				return this;
			}
			$builder.add("valueLong", _JsonUtils.toJsonLongArray(valueLong));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueFloat(List<Float> valueFloat) {
			if (valueFloat == null) {
				$builder.addNull("valueFloat");
				return this;
			}
			$builder.add("valueFloat", _JsonUtils.toJsonFloatArray(valueFloat));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueDouble(List<Double> valueDouble) {
			if (valueDouble == null) {
				$builder.addNull("valueDouble");
				return this;
			}
			$builder.add("valueDouble", _JsonUtils.toJsonDoubleArray(valueDouble));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueString(List<String> valueString) {
			if (valueString == null) {
				$builder.addNull("valueString");
				return this;
			}
			$builder.add("valueString", _JsonUtils.toJsonStringArray(valueString));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueLocalDate(List<LocalDate> valueLocalDate) {
			if (valueLocalDate == null) {
				$builder.addNull("valueLocalDate");
				return this;
			}
			$builder.add("valueLocalDate", _JsonUtils.toJsonLiteralArray(valueLocalDate));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueLocalDateTime(List<LocalDateTime> valueLocalDateTime) {
			if (valueLocalDateTime == null) {
				$builder.addNull("valueLocalDateTime");
				return this;
			}
			$builder.add("valueLocalDateTime", _JsonUtils.toJsonLiteralArray(valueLocalDateTime));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueLocalTime(List<LocalTime> valueLocalTime) {
			if (valueLocalTime == null) {
				$builder.addNull("valueLocalTime");
				return this;
			}
			$builder.add("valueLocalTime", _JsonUtils.toJsonLiteralArray(valueLocalTime));
			return this;
		}

		@Override
		public SimpleRecord_Basic_List_Null.DataBuilder valueZonedDateTime(List<ZonedDateTime> valueZonedDateTime) {
			if (valueZonedDateTime == null) {
				$builder.addNull("valueZonedDateTime");
				return this;
			}
			$builder.add("valueZonedDateTime", _JsonUtils.toJsonLiteralArray(valueZonedDateTime));
			return this;
		}

		public SimpleRecord_Basic_List_Null.Data build() {
			return new SimpleRecord_Basic_List_NullDataImpl($builder.build());
		}
	}

	public static SimpleRecord_Basic_List_Null.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
