/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type SampleEnum,
    SampleEnumFromJSON,
    SampleEnumToJSON,
} from '../models/SampleEnum.js';

export interface PathParameterTypeServiceMultiPathParamRequest {
    valueA: string;
    valueB: number;
}

export interface PathParameterTypeServiceSimpleBooleanPathParamRequest {
    pathBoolean: boolean;
}

export interface PathParameterTypeServiceSimpleDoublePathParamRequest {
    pathDouble: number;
}

export interface PathParameterTypeServiceSimpleEnumPathParamRequest {
    pathEnum: SampleEnum;
}

export interface PathParameterTypeServiceSimpleFloatPathParamRequest {
    pathFloat: number;
}

export interface PathParameterTypeServiceSimpleIntPathParamRequest {
    pathInt: number;
}

export interface PathParameterTypeServiceSimpleLocalDatePathParamRequest {
    pathLocalDate: Date;
}

export interface PathParameterTypeServiceSimpleLocalDateTimePathParamRequest {
    pathLocalDateTime: string;
}

export interface PathParameterTypeServiceSimpleLocalTimePathParamRequest {
    pathLocalTime: string;
}

export interface PathParameterTypeServiceSimpleLongPathParamRequest {
    pathLong: number;
}

export interface PathParameterTypeServiceSimpleOffsetDateTimePathParamRequest {
    pathOffsetDateTime: string;
}

export interface PathParameterTypeServiceSimpleScalarPathParamRequest {
    pathScalar: string;
}

export interface PathParameterTypeServiceSimpleShortPathParamRequest {
    pathShort: number;
}

export interface PathParameterTypeServiceSimpleStringPathParamRequest {
    pathString: string;
}

export interface PathParameterTypeServiceSimpleZonedDateTimePathParamRequest {
    pathZonedDateTime: string;
}

/**
 * 
 */
export class PathParameterTypeServiceApi extends runtime.BaseAPI {

    /**
     * Creates request options for pathParameterTypeServiceMultiPathParam without sending the request
     */
    async pathParameterTypeServiceMultiPathParamRequestOpts(requestParameters: PathParameterTypeServiceMultiPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['valueA'] == null) {
            throw new runtime.RequiredError(
                'valueA',
                'Required parameter "valueA" was null or undefined when calling pathParameterTypeServiceMultiPathParam().'
            );
        }

        if (requestParameters['valueB'] == null) {
            throw new runtime.RequiredError(
                'valueB',
                'Required parameter "valueB" was null or undefined when calling pathParameterTypeServiceMultiPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/multipathparam/{valueA}/{valueB}`;
        urlPath = urlPath.replace('{valueA}', encodeURIComponent(String(requestParameters['valueA'])));
        urlPath = urlPath.replace('{valueB}', encodeURIComponent(String(requestParameters['valueB'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceMultiPathParamRaw(requestParameters: PathParameterTypeServiceMultiPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceMultiPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceMultiPathParam(requestParameters: PathParameterTypeServiceMultiPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceMultiPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleBooleanPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleBooleanPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleBooleanPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathBoolean'] == null) {
            throw new runtime.RequiredError(
                'pathBoolean',
                'Required parameter "pathBoolean" was null or undefined when calling pathParameterTypeServiceSimpleBooleanPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/boolean/{pathBoolean}`;
        urlPath = urlPath.replace('{pathBoolean}', encodeURIComponent(String(requestParameters['pathBoolean'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleBooleanPathParamRaw(requestParameters: PathParameterTypeServiceSimpleBooleanPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleBooleanPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleBooleanPathParam(requestParameters: PathParameterTypeServiceSimpleBooleanPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.pathParameterTypeServiceSimpleBooleanPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleDoublePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleDoublePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleDoublePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathDouble'] == null) {
            throw new runtime.RequiredError(
                'pathDouble',
                'Required parameter "pathDouble" was null or undefined when calling pathParameterTypeServiceSimpleDoublePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/double/{pathDouble}`;
        urlPath = urlPath.replace('{pathDouble}', encodeURIComponent(String(requestParameters['pathDouble'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleDoublePathParamRaw(requestParameters: PathParameterTypeServiceSimpleDoublePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleDoublePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleDoublePathParam(requestParameters: PathParameterTypeServiceSimpleDoublePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pathParameterTypeServiceSimpleDoublePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleEnumPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleEnumPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleEnumPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathEnum'] == null) {
            throw new runtime.RequiredError(
                'pathEnum',
                'Required parameter "pathEnum" was null or undefined when calling pathParameterTypeServiceSimpleEnumPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/enum/{pathEnum}`;
        urlPath = urlPath.replace('{pathEnum}', encodeURIComponent(String(requestParameters['pathEnum'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleEnumPathParamRaw(requestParameters: PathParameterTypeServiceSimpleEnumPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SampleEnum>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleEnumPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleEnumFromJSON(jsonValue));
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleEnumPathParam(requestParameters: PathParameterTypeServiceSimpleEnumPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SampleEnum> {
        const response = await this.pathParameterTypeServiceSimpleEnumPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleFloatPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleFloatPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleFloatPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathFloat'] == null) {
            throw new runtime.RequiredError(
                'pathFloat',
                'Required parameter "pathFloat" was null or undefined when calling pathParameterTypeServiceSimpleFloatPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/float/{pathFloat}`;
        urlPath = urlPath.replace('{pathFloat}', encodeURIComponent(String(requestParameters['pathFloat'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleFloatPathParamRaw(requestParameters: PathParameterTypeServiceSimpleFloatPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleFloatPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleFloatPathParam(requestParameters: PathParameterTypeServiceSimpleFloatPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pathParameterTypeServiceSimpleFloatPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleIntPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleIntPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleIntPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathInt'] == null) {
            throw new runtime.RequiredError(
                'pathInt',
                'Required parameter "pathInt" was null or undefined when calling pathParameterTypeServiceSimpleIntPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/int/{pathInt}`;
        urlPath = urlPath.replace('{pathInt}', encodeURIComponent(String(requestParameters['pathInt'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleIntPathParamRaw(requestParameters: PathParameterTypeServiceSimpleIntPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleIntPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleIntPathParam(requestParameters: PathParameterTypeServiceSimpleIntPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pathParameterTypeServiceSimpleIntPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleLocalDatePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleLocalDatePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleLocalDatePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathLocalDate'] == null) {
            throw new runtime.RequiredError(
                'pathLocalDate',
                'Required parameter "pathLocalDate" was null or undefined when calling pathParameterTypeServiceSimpleLocalDatePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/localdate/{pathLocalDate}`;
        if (requestParameters['pathLocalDate'] instanceof Date) {
            urlPath = urlPath.replace('{pathLocalDate}', encodeURIComponent(requestParameters['pathLocalDate'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace('{pathLocalDate}', encodeURIComponent(String(requestParameters['pathLocalDate'])));
        }

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalDatePathParamRaw(requestParameters: PathParameterTypeServiceSimpleLocalDatePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Date>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleLocalDatePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<Date>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalDatePathParam(requestParameters: PathParameterTypeServiceSimpleLocalDatePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Date> {
        const response = await this.pathParameterTypeServiceSimpleLocalDatePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleLocalDateTimePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleLocalDateTimePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleLocalDateTimePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathLocalDateTime'] == null) {
            throw new runtime.RequiredError(
                'pathLocalDateTime',
                'Required parameter "pathLocalDateTime" was null or undefined when calling pathParameterTypeServiceSimpleLocalDateTimePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/localdatetime/{pathLocalDateTime}`;
        urlPath = urlPath.replace('{pathLocalDateTime}', encodeURIComponent(String(requestParameters['pathLocalDateTime'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalDateTimePathParamRaw(requestParameters: PathParameterTypeServiceSimpleLocalDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleLocalDateTimePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalDateTimePathParam(requestParameters: PathParameterTypeServiceSimpleLocalDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleLocalDateTimePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleLocalTimePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleLocalTimePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleLocalTimePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathLocalTime'] == null) {
            throw new runtime.RequiredError(
                'pathLocalTime',
                'Required parameter "pathLocalTime" was null or undefined when calling pathParameterTypeServiceSimpleLocalTimePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/localtime/{pathLocalTime}`;
        urlPath = urlPath.replace('{pathLocalTime}', encodeURIComponent(String(requestParameters['pathLocalTime'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalTimePathParamRaw(requestParameters: PathParameterTypeServiceSimpleLocalTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleLocalTimePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLocalTimePathParam(requestParameters: PathParameterTypeServiceSimpleLocalTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleLocalTimePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleLongPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleLongPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleLongPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathLong'] == null) {
            throw new runtime.RequiredError(
                'pathLong',
                'Required parameter "pathLong" was null or undefined when calling pathParameterTypeServiceSimpleLongPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/long/{pathLong}`;
        urlPath = urlPath.replace('{pathLong}', encodeURIComponent(String(requestParameters['pathLong'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLongPathParamRaw(requestParameters: PathParameterTypeServiceSimpleLongPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleLongPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleLongPathParam(requestParameters: PathParameterTypeServiceSimpleLongPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pathParameterTypeServiceSimpleLongPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleOffsetDateTimePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleOffsetDateTimePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleOffsetDateTimePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathOffsetDateTime'] == null) {
            throw new runtime.RequiredError(
                'pathOffsetDateTime',
                'Required parameter "pathOffsetDateTime" was null or undefined when calling pathParameterTypeServiceSimpleOffsetDateTimePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/offsetdatetime/{pathOffsetDateTime}`;
        urlPath = urlPath.replace('{pathOffsetDateTime}', encodeURIComponent(String(requestParameters['pathOffsetDateTime'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleOffsetDateTimePathParamRaw(requestParameters: PathParameterTypeServiceSimpleOffsetDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleOffsetDateTimePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleOffsetDateTimePathParam(requestParameters: PathParameterTypeServiceSimpleOffsetDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleOffsetDateTimePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleScalarPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleScalarPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleScalarPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathScalar'] == null) {
            throw new runtime.RequiredError(
                'pathScalar',
                'Required parameter "pathScalar" was null or undefined when calling pathParameterTypeServiceSimpleScalarPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/scalar/{pathScalar}`;
        urlPath = urlPath.replace('{pathScalar}', encodeURIComponent(String(requestParameters['pathScalar'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleScalarPathParamRaw(requestParameters: PathParameterTypeServiceSimpleScalarPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleScalarPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleScalarPathParam(requestParameters: PathParameterTypeServiceSimpleScalarPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleScalarPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleShortPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleShortPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleShortPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathShort'] == null) {
            throw new runtime.RequiredError(
                'pathShort',
                'Required parameter "pathShort" was null or undefined when calling pathParameterTypeServiceSimpleShortPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/short/{pathShort}`;
        urlPath = urlPath.replace('{pathShort}', encodeURIComponent(String(requestParameters['pathShort'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleShortPathParamRaw(requestParameters: PathParameterTypeServiceSimpleShortPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleShortPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleShortPathParam(requestParameters: PathParameterTypeServiceSimpleShortPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pathParameterTypeServiceSimpleShortPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleStringPathParam without sending the request
     */
    async pathParameterTypeServiceSimpleStringPathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleStringPathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathString'] == null) {
            throw new runtime.RequiredError(
                'pathString',
                'Required parameter "pathString" was null or undefined when calling pathParameterTypeServiceSimpleStringPathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/string/{pathString}`;
        urlPath = urlPath.replace('{pathString}', encodeURIComponent(String(requestParameters['pathString'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleStringPathParamRaw(requestParameters: PathParameterTypeServiceSimpleStringPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleStringPathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleStringPathParam(requestParameters: PathParameterTypeServiceSimpleStringPathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleStringPathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pathParameterTypeServiceSimpleZonedDateTimePathParam without sending the request
     */
    async pathParameterTypeServiceSimpleZonedDateTimePathParamRequestOpts(requestParameters: PathParameterTypeServiceSimpleZonedDateTimePathParamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pathZonedDateTime'] == null) {
            throw new runtime.RequiredError(
                'pathZonedDateTime',
                'Required parameter "pathZonedDateTime" was null or undefined when calling pathParameterTypeServiceSimpleZonedDateTimePathParam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/pathparametertype/zoneddatetime/{pathZonedDateTime}`;
        urlPath = urlPath.replace('{pathZonedDateTime}', encodeURIComponent(String(requestParameters['pathZonedDateTime'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleZonedDateTimePathParamRaw(requestParameters: PathParameterTypeServiceSimpleZonedDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pathParameterTypeServiceSimpleZonedDateTimePathParamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 
     */
    async pathParameterTypeServiceSimpleZonedDateTimePathParam(requestParameters: PathParameterTypeServiceSimpleZonedDateTimePathParamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pathParameterTypeServiceSimpleZonedDateTimePathParamRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
