// Generated by RSD - Do not modify
package dev.rsdlang.sample.client.model.impl.avro;

import java.util.function.Function;

import dev.rsdlang.sample.client.model.CyclicNodeA;
import dev.rsdlang.sample.client.model.CyclicNodeB;
import org.apache.avro.generic.GenericRecord;
import org.apache.avro.generic.GenericRecordBuilder;

public class CyclicNodeBDataImpl extends _BaseDataImpl implements CyclicNodeB.Data {
	CyclicNodeBDataImpl(GenericRecord data) {
		super(data);
	}

	@Override
	public String value() {
		return _AvroUtils.mapString(data, "value");
	}

	@Override
	public CyclicNodeA.Data nodeA() {
		return _AvroUtils.mapObject(data, "nodeA", CyclicNodeADataImpl::of);
	}

	public static CyclicNodeB.Data of(GenericRecord obj) {
		return new CyclicNodeBDataImpl(obj);
	}

	public String toString() {
		return getClass().getSimpleName();
	}

	public static class DataBuilderImpl implements CyclicNodeB.DataBuilder {
		private final GenericRecordBuilder $builder = _AvroUtils.newBuilder(_AvroSchema.AvroTypes.CyclicNodeB);

		@Override
		public CyclicNodeB.DataBuilder value(String value) {
			if (value == null) {
				return this;
			}
			$builder.set("value", value);
			return this;
		}

		@Override
		public CyclicNodeB.DataBuilder nodeA(CyclicNodeA.Data nodeA) {
			if (nodeA == null) {
				return this;
			}
			$builder.set("nodeA", ((_BaseDataImpl) nodeA).data);
			return this;
		}


		public <T extends CyclicNodeA.DataBuilder> DataBuilder withNodeA(Class<T> clazz, Function<T, CyclicNodeA.Data> block) {
			var b = CyclicNodeADataImpl.builder();
			return nodeA(block.apply(clazz.cast(b)));
		}

		public CyclicNodeB.Data build() {
			return new CyclicNodeBDataImpl($builder.build());
		}
	}

	public static CyclicNodeB.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
