/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MRSDModel } from "./utils/model";
export { MRSDModel } from "./utils/model";
export namespace Components {
    interface RsdPreview {
        "model": string | MRSDModel;
        "projectname": string;
    }
}
declare global {
    interface HTMLRsdPreviewElement extends Components.RsdPreview, HTMLStencilElement {
    }
    var HTMLRsdPreviewElement: {
        prototype: HTMLRsdPreviewElement;
        new (): HTMLRsdPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "rsd-preview": HTMLRsdPreviewElement;
    }
}
declare namespace LocalJSX {
    interface RsdPreview {
        "model"?: string | MRSDModel;
        "projectname"?: string;
    }
    interface IntrinsicElements {
        "rsd-preview": RsdPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rsd-preview": LocalJSX.RsdPreview & JSXBase.HTMLAttributes<HTMLRsdPreviewElement>;
        }
    }
}
