// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.rest.model;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.StringWriter;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.function.Function;
import java.util.List;
import java.util.Optional;
import java.util.OptionalDouble;
import java.util.OptionalInt;
import java.util.OptionalLong;
import java.util.stream.Collector;
import java.util.stream.Stream;

import jakarta.json.Json;
import jakarta.json.JsonArray;
import jakarta.json.JsonArrayBuilder;
import jakarta.json.JsonNumber;
import jakarta.json.JsonObject;
import jakarta.json.JsonString;
import jakarta.json.JsonValue;
import jakarta.json.stream.JsonGenerator;
import jakarta.json.JsonException;

import dev.rsdlang.sample.server.service.model._Base;

public class _JsonUtils {


	private static final Optional<Boolean> OPTIONAL_FALSE = Optional.of(Boolean.FALSE);
	private static final Optional<Boolean> OPTIONAL_TRUE = Optional.of(Boolean.TRUE);
	private static final _Base.Nillable<Boolean> NILLABLE_FALSE = _NillableImpl.of(Boolean.FALSE);
	private static final _Base.Nillable<Boolean> NILLABLE_TRUE = _NillableImpl.of(Boolean.TRUE);

	public static <J extends JsonValue, T> Stream<T> mapToStream(JsonObject object, String property, Class<J> clazz,
			Function<J, T> mapper) {
		if (object.containsKey(property)) {
			return mapToStream(object.getJsonArray(property), clazz, mapper);
		}
		return Stream.empty();
	}

	private static <J extends JsonValue, T> Stream<T> mapToStream(JsonArray array,
			Class<J> clazz, Function<J, T> mapper) {
		return array
				.getValuesAs(clazz)
				.stream()
				.map(mapper);
	}

	public static <J extends JsonValue, T> Optional<Stream<T>> mapToNullStream(JsonObject object, String property,
			Class<J> clazz, Function<J, T> mapper) {
		if (!object.isNull(property)) {
			return Optional.of(mapToStream(object, property, clazz, mapper));
		}
		return Optional.empty();
	}

	public static <J extends JsonValue, T> Optional<Stream<T>> mapToOptStream(JsonObject object, String property,
			Class<J> clazz, Function<J, T> mapper) {
		if (object.containsKey(property)) {
			return Optional.of(mapToStream(object, property, clazz, mapper));
		}
		return Optional.empty();
	}

	public static <J extends JsonValue, T> _Base.Nillable<Stream<T>> mapToNilStream(JsonObject object, String property,
			Class<J> clazz, Function<J, T> mapper) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapToStream(object, property, clazz, mapper));
		}
		return _NillableImpl.undefined();
	}

	// ----------------

	public static <T> List<T> mapObjects(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		return mapToStream(object, property, JsonObject.class, converter).toList();
	}

	public static <T> T mapLiteral(JsonObject object, String property,
			Function<String, T> converter) {
		return converter.apply(object.getString(property));
	}

	public static <T> Optional<T> mapNullLiteral(JsonObject object, String property, Function<String, T> converter) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return Optional.of(mapLiteral(object, property, converter));
	}

	public static <T> Optional<T> mapOptLiteral(JsonObject object, String property, Function<String, T> converter) {
		if (object.containsKey(property)) {
			return Optional.of(mapLiteral(object, property, converter));
		}
		return Optional.empty();
	}

	public static <T> _Base.Nillable<T> mapNilLiteral(JsonObject object, String property, Function<String, T> converter) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapLiteral(object, property, converter));
		}
		return _NillableImpl.undefined();
	}

	public static <T> List<T> mapLiterals(JsonObject object, String property,
			Function<String, T> mapper) {
		return mapToStream(object, property, JsonString.class,
				JsonString::getString).map(mapper).toList();
	}

	public static <T> Optional<List<T>> mapNullLiterals(JsonObject object, String property, Function<String, T> mapper) {
		return mapToNullStream(object, property, JsonString.class,
				JsonString::getString).map(s -> s.map(mapper)).map(Stream::toList);
	}

	public static <T> Optional<List<T>> mapOptLiterals(JsonObject object, String property, Function<String, T> mapper) {
		return mapToOptStream(object, property, JsonString.class,
				JsonString::getString).map(s -> s.map(mapper))
				.map(Stream::toList);
	}

	public static <T> _Base.Nillable<List<T>> mapNilLiterals(JsonObject object,
			String property,
			Function<String, T> mapper) {
		return mapToNilStream(object, property, JsonString.class,
				JsonString::getString).map(s -> s.map(mapper))
				.map(Stream::toList);
	}

	// ----------------

	public static <T> T mapObject(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		return converter.apply(object.getJsonObject(property));
	}

	public static <T> Optional<T> mapOptObject(JsonObject object, String property, Function<JsonObject, T> converter) {
		if (object.containsKey(property)) {
			return Optional.of(mapObject(object, property, converter));
		}
		return Optional.empty();
	}

	public static <T> _Base.Nillable<T> mapNilObject(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapObject(object, property, converter));
		}
		return _NillableImpl.undefined();
	}

	public static <T> Optional<T> mapNullObject(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return Optional.of(mapObject(object, property, converter));
	}

	public static <T> Optional<List<T>> mapNullObjects(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		return mapToNullStream(object, property, JsonObject.class,
				converter).map(Stream::toList);
	}

	public static <T> Optional<List<T>> mapOptObjects(JsonObject object, String property,
			Function<JsonObject, T> converter) {
		return mapToOptStream(object, property, JsonObject.class,
				converter).map(Stream::toList);
	}

	public static <T> _Base.Nillable<List<T>> mapNilObjects(JsonObject object,
			String property,
			Function<JsonObject, T> converter) {
		return mapToNilStream(object, property, JsonObject.class,
				converter).map(Stream::toList);
	}

	// ----------------

	public static Optional<List<Boolean>> mapNullBooleans(JsonObject object,
			String property) {
		return mapToNullStream(object, property, JsonValue.class, v -> v == JsonValue.TRUE).map(Stream::toList);
	}

	public static _Base.Nillable<List<Boolean>> mapNilBooleans(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonValue.class, v -> v == JsonValue.TRUE).map(Stream::toList);
	}

	public static Optional<List<Boolean>> mapOptBooleans(JsonObject object,
			String property) {
		return mapToOptStream(object, property, JsonValue.class, v -> v == JsonValue.TRUE).map(Stream::toList);
	}

	public static List<Boolean> mapBooleans(JsonObject object, String property) {
		return mapToStream(object, property, JsonValue.class, v -> v == JsonValue.TRUE).toList();
	}

	public static Optional<Boolean> mapNullBoolean(JsonObject object, String property) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return object.getBoolean(property) ? OPTIONAL_TRUE : OPTIONAL_FALSE;
	}

	public static _Base.Nillable<Boolean> mapNilBoolean(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return object.getBoolean(property) ? NILLABLE_TRUE : NILLABLE_FALSE;
		}
		return _NillableImpl.undefined();
	}

	public static Optional<Boolean> mapOptBoolean(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return object.getBoolean(property) ? OPTIONAL_TRUE : OPTIONAL_FALSE;
		}
		return Optional.empty();
	}

	public static boolean mapBoolean(JsonObject object, String property) {
		return object.getBoolean(property);
	}

	// ----------------

	public static Optional<List<Short>> mapNullShorts(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonNumber.class, v -> v.numberValue().shortValue()).map(Stream::toList);
	}

	public static _Base.Nillable<List<Short>> mapNilShorts(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonNumber.class, v -> v.numberValue().shortValue()).map(Stream::toList);
	}

	public static Optional<List<Short>> mapOptShorts(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonNumber.class, v -> v.numberValue().shortValue()).map(Stream::toList);
	}

	public static List<Short> mapShorts(JsonObject object, String property) {
		return mapToStream(object, property, JsonNumber.class, v -> v.numberValue().shortValue()).toList();
	}

	public static Optional<Short> mapNullShort(JsonObject object, String property) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return Optional.of(mapShort(object, property));
	}

	public static short mapShort(JsonObject object, String property) {
		return (short) object.getInt(property);
	}

	public static _Base.Nillable<Short> mapNilShort(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapShort(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static Optional<Short> mapOptShort(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return Optional.of(mapShort(object, property));
		}
		return Optional.empty();
	}

	// ----------------
	public static Optional<List<Integer>> mapNullInts(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonNumber.class,
				JsonNumber::intValue).map(Stream::toList);
	}

	public static _Base.Nillable<List<Integer>> mapNilInts(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonNumber.class,
				JsonNumber::intValue).map(Stream::toList);
	}

	public static Optional<List<Integer>> mapOptInts(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonNumber.class,
				JsonNumber::intValue).map(Stream::toList);
	}

	public static List<Integer> mapInts(JsonObject object, String property) {
		return mapToStream(object, property, JsonNumber.class,
				JsonNumber::intValue).toList();
	}

	public static OptionalInt mapNullInt(JsonObject object, String property) {
		if (object.isNull(property)) {
			return OptionalInt.empty();
		}
		return OptionalInt.of(mapInt(object, property));
	}

	public static int mapInt(JsonObject object, String property) {
		return object.getInt(property);
	}

	public static _Base.Nillable<Integer> mapNilInt(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapInt(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static OptionalInt mapOptInt(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return OptionalInt.of(mapInt(object, property));
		}
		return OptionalInt.empty();
	}

	// ----------------
	public static Optional<List<Long>> mapNullLongs(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonNumber.class, v -> v.numberValue().longValue()).map(Stream::toList);
	}

	public static _Base.Nillable<List<Long>> mapNilLongs(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonNumber.class, v -> v.numberValue().longValue()).map(Stream::toList);
	}

	public static Optional<List<Long>> mapOptLongs(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonNumber.class, v -> v.numberValue().longValue()).map(Stream::toList);
	}

	public static List<Long> mapLongs(JsonObject object, String property) {
		return mapToStream(object, property, JsonNumber.class, v -> v.numberValue().longValue()).toList();
	}

	public static OptionalLong mapNullLong(JsonObject object, String property) {
		if (object.isNull(property)) {
			return OptionalLong.empty();
		}
		return OptionalLong.of(mapLong(object, property));
	}

	public static long mapLong(JsonObject object, String property) {
		return object.getJsonNumber(property).longValue();
	}

	public static _Base.Nillable<Long> mapNilLong(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapLong(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static OptionalLong mapOptLong(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return OptionalLong.of(mapLong(object, property));
		}
		return OptionalLong.empty();
	}

	// ----------------
	public static Optional<List<Float>> mapNullFloats(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonNumber.class, v -> v.numberValue().floatValue()).map(Stream::toList);
	}

	public static _Base.Nillable<List<Float>> mapNilFloats(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonNumber.class, v -> v.numberValue().floatValue()).map(Stream::toList);
	}

	public static Optional<List<Float>> mapOptFloats(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonNumber.class, v -> v.numberValue().floatValue()).map(Stream::toList);
	}

	public static List<Float> mapFloats(JsonObject object, String property) {
		return mapToStream(object, property, JsonNumber.class, v -> v.numberValue().floatValue()).toList();
	}

	public static Optional<Float> mapNullFloat(JsonObject object, String property) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return Optional.of(mapFloat(object, property));
	}

	public static float mapFloat(JsonObject object, String property) {
		return (float) object.getJsonNumber(property).doubleValue();
	}

	public static _Base.Nillable<Float> mapNilFloat(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapFloat(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static Optional<Float> mapOptFloat(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return Optional.of(mapFloat(object, property));
		}
		return Optional.empty();
	}

	// ----------------
	public static Optional<List<Double>> mapNullDoubles(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonNumber.class,
				JsonNumber::doubleValue).map(Stream::toList);
	}

	public static _Base.Nillable<List<Double>> mapNilDoubles(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonNumber.class,
				JsonNumber::doubleValue).map(Stream::toList);
	}

	public static Optional<List<Double>> mapOptDoubles(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonNumber.class,
				JsonNumber::doubleValue).map(Stream::toList);
	}

	public static List<Double> mapDoubles(JsonObject object, String property) {
		return mapToStream(object, property, JsonNumber.class,
				JsonNumber::doubleValue).toList();
	}

	public static OptionalDouble mapNullDouble(JsonObject object, String property) {
		if (object.isNull(property)) {
			return OptionalDouble.empty();
		}
		return OptionalDouble.of(mapDouble(object, property));
	}

	public static double mapDouble(JsonObject object, String property) {
		return object.getJsonNumber(property).doubleValue();
	}

	public static _Base.Nillable<Double> mapNilDouble(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapDouble(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static OptionalDouble mapOptDouble(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return OptionalDouble.of(mapDouble(object, property));
		}
		return OptionalDouble.empty();
	}

	// ----------------
	public static Optional<List<String>> mapNullStrings(JsonObject object, String property) {
		return mapToNullStream(object, property, JsonString.class,
				JsonString::getString).map(Stream::toList);
	}

	public static _Base.Nillable<List<String>> mapNilStrings(JsonObject object,
			String property) {
		return mapToNilStream(object, property, JsonString.class,
				JsonString::getString).map(Stream::toList);
	}

	public static Optional<List<String>> mapOptStrings(JsonObject object, String property) {
		return mapToOptStream(object, property, JsonString.class,
				JsonString::getString).map(Stream::toList);
	}

	public static List<String> mapStrings(JsonObject object, String property) {
		return mapToStream(object, property, JsonString.class,
				JsonString::getString).toList();
	}

	public static Optional<String> mapNullString(JsonObject object, String property) {
		if (object.isNull(property)) {
			return Optional.empty();
		}
		return Optional.of(mapString(object, property));
	}

	public static String mapString(JsonObject object, String property) {
		return object.getString(property);
	}

	public static _Base.Nillable<String> mapNilString(JsonObject object, String property) {
		if (object.containsKey(property)) {
			if (object.isNull(property)) {
				return _NillableImpl.nill();
			}
			return _NillableImpl.of(mapString(object, property));
		}
		return _NillableImpl.undefined();
	}

	public static Optional<String> mapOptString(JsonObject object, String property) {
		if (object.containsKey(property)) {
			return Optional.of(mapString(object, property));
		}
		return Optional.empty();
	}

	// ----------------
	public static Optional<List<LocalDate>> mapNullLocalDates(JsonObject object,
			String property) {
		return mapNullLiterals(object, property, LocalDate::parse);
	}

	public static _Base.Nillable<List<LocalDate>> mapNilLocalDates(JsonObject object, String property) {
		return mapNilLiterals(object, property, LocalDate::parse);
	}

	public static Optional<List<LocalDate>> mapOptLocalDates(JsonObject object,
			String property) {
		return mapOptLiterals(object, property, LocalDate::parse);
	}

	public static List<LocalDate> mapLocalDates(JsonObject object, String property) {
		return mapLiterals(object, property, LocalDate::parse);
	}

	public static Optional<LocalDate> mapNullLocalDate(JsonObject object, String property) {
		return mapNullLiteral(object, property, LocalDate::parse);
	}

	public static _Base.Nillable<LocalDate> mapNilLocalDate(JsonObject object,
			String property) {
		return mapNilLiteral(object, property, LocalDate::parse);
	}

	public static Optional<LocalDate> mapOptLocalDate(JsonObject object, String property) {
		return mapOptLiteral(object, property, LocalDate::parse);
	}

	public static LocalDate mapLocalDate(JsonObject object, String property) {
		return mapLiteral(object, property, LocalDate::parse);
	}

	// ----------------
	public static Optional<List<LocalDateTime>> mapNullLocalDateTimes(JsonObject object, String property) {
		return mapNullLiterals(object, property, LocalDateTime::parse);
	}

	public static _Base.Nillable<List<LocalDateTime>> mapNilLocalDateTimes(JsonObject object, String property) {
		return mapNilLiterals(object, property, LocalDateTime::parse);
	}

	public static Optional<List<LocalDateTime>> mapOptLocalDateTimes(JsonObject object, String property) {
		return mapOptLiterals(object, property, LocalDateTime::parse);
	}

	public static List<LocalDateTime> mapLocalDateTimes(JsonObject object, String property) {
		return mapLiterals(object, property, LocalDateTime::parse);
	}

	public static Optional<LocalDateTime> mapNullLocalDateTime(JsonObject object,
			String property) {
		return mapNullLiteral(object, property, LocalDateTime::parse);
	}

	public static _Base.Nillable<LocalDateTime> mapNilLocalDateTime(JsonObject object, String property) {
		return mapNilLiteral(object, property, LocalDateTime::parse);
	}

	public static Optional<LocalDateTime> mapOptLocalDateTime(JsonObject object,
			String property) {
		return mapOptLiteral(object, property, LocalDateTime::parse);
	}

	public static LocalDateTime mapLocalDateTime(JsonObject object, String property) {
		return mapLiteral(object, property, LocalDateTime::parse);
	}

	// ----------------
	public static Optional<List<ZonedDateTime>> mapNullZonedDateTimes(JsonObject object, String property) {
		return mapNullLiterals(object, property, ZonedDateTime::parse);
	}

	public static _Base.Nillable<List<ZonedDateTime>> mapNilZonedDateTimes(JsonObject object, String property) {
		return mapNilLiterals(object, property, ZonedDateTime::parse);
	}

	public static Optional<List<ZonedDateTime>> mapOptZonedDateTimes(JsonObject object, String property) {
		return mapOptLiterals(object, property, ZonedDateTime::parse);
	}

	public static List<ZonedDateTime> mapZonedDateTimes(JsonObject object, String property) {
		return mapLiterals(object, property, ZonedDateTime::parse);
	}

	public static Optional<ZonedDateTime> mapNullZonedDateTime(JsonObject object,
			String property) {
		return mapNullLiteral(object, property, ZonedDateTime::parse);
	}

	public static _Base.Nillable<ZonedDateTime> mapNilZonedDateTime(JsonObject object, String property) {
		return mapNilLiteral(object, property, ZonedDateTime::parse);
	}

	public static Optional<ZonedDateTime> mapOptZonedDateTime(JsonObject object,
			String property) {
		return mapOptLiteral(object, property, ZonedDateTime::parse);
	}

	public static ZonedDateTime mapZonedDateTime(JsonObject object, String property) {
		return mapLiteral(object, property, ZonedDateTime::parse);
	}

	// ----------------
	private static Collector<String, ?, JsonArray> toStringArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static <T> JsonArray toJsonLiteralArray(List<T> value, Function<T, String> converter) {
		return value.stream().map(converter).collect(toStringArray());
	}

	public static <T> JsonArray toJsonLiteralArray(List<T> value) {
		return value.stream().map(Object::toString).collect(toStringArray());
	}

	// ----------------
	private static Collector<Boolean, ?, JsonArray> toBooleanArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonBooleanArray(List<Boolean> value) {
		return value.stream().collect(toBooleanArray());
	}

	// ----------------
	private static Collector<Short, ?, JsonArray> toShortArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonShortArray(List<Short> value) {
		return value.stream().collect(toShortArray());
	}

	// ----------------
	private static Collector<Integer, ?, JsonArray> toIntArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonIntArray(List<Integer> value) {
		return value.stream().collect(toIntArray());
	}

	// ----------------
	private static Collector<Long, ?, JsonArray> toLongArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonLongArray(List<Long> value) {
		return value.stream().collect(toLongArray());
	}

	// ----------------
	public static Collector<Float, ?, JsonArray> toFloatArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonFloatArray(List<Float> value) {
		return value.stream().collect(toFloatArray());
	}

	// ----------------
	public static Collector<Double, ?, JsonArray> toDoubleArray() {
		return Collector.of(
				Json::createArrayBuilder,
				JsonArrayBuilder::add,
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	public static JsonArray toJsonDoubleArray(List<Double> value) {
		return value.stream().collect(toDoubleArray());
	}

	// ----------------
	public static JsonArray toJsonStringArray(List<String> value) {
		return value.stream().collect(toStringArray());
	}

	// ----------------
	public static <T> JsonArray toJsonValueArray(List<T> value, Function<T, ? extends JsonValue> jsonValueConverter) {
		return value.stream().collect(toArray(jsonValueConverter));
	}

	public static <T> Collector<T, ?, JsonArray> toArray(Function<T, ? extends JsonValue> jsonValueConverter) {
		return Collector.of(
				Json::createArrayBuilder,
				(b, v) -> b.add(jsonValueConverter.apply(v)),
				JsonArrayBuilder::add,
				JsonArrayBuilder::build);
	}

	// ----------------
	public static void encodeValue(OutputStream stream, Object data, String contentType) {
		if (contentType != null && contentType.startsWith("application/json")) {
			encodeJsonValue(stream, data);
			return;
		}
		throw new IllegalArgumentException("Unsupported content type: " + contentType);
	}

	public static byte[] encodeValue(Object data, String contentType) {
		if (contentType != null && contentType.startsWith("application/json")) {
			return encodeJsonValue(data);
		}
		throw new IllegalArgumentException("Unsupported content type: " + contentType);
	}

	private static byte[] encodeJsonValue(Object data) {
		StringWriter stringWriter = new StringWriter();
		try (JsonGenerator generator = Json.createGenerator(stringWriter)) {
			encodeJsonValue(generator, data);
		}
		return stringWriter.toString().getBytes();
	}

	private static void encodeJsonValue(OutputStream stream, Object data) {
		try (JsonGenerator generator = Json.createGenerator(stream)) {
			encodeJsonValue(generator, data);
		}
	}

	private static void encodeJsonValue(JsonGenerator generator, Object data) {
		if (data == null) {
			generator.writeNull();
		} else if (data instanceof JsonValue jsonValue) {
			generator.write(jsonValue);
		} else if (data instanceof String s) {
			generator.write(s);
		} else if (data instanceof Number n) {
			if (data instanceof Byte || data instanceof Short || data instanceof Integer || data instanceof Character) {
				generator.write(n.intValue());
			} else if (data instanceof Byte || data instanceof Short || data instanceof Integer || data instanceof Long) {
				generator.write(n.longValue());
			} else if (data instanceof Float || data instanceof Double) {
				generator.write(n.doubleValue());
			} else if (data instanceof BigInteger) {
				generator.write(((BigInteger) n).longValue());
			} else if (data instanceof BigDecimal) {
				generator.write(((BigDecimal) n).doubleValue());
			} else {
				throw new IllegalArgumentException("Unsupported number type: " + data.getClass());
			}
		} else if (data instanceof Boolean b) {
			generator.write(b);
		} else if (data instanceof _BaseDataImpl baseData) {
			encodeJsonValue(generator, baseData.data);
		} else if (data instanceof List<?> list) {
			generator.writeStartArray();
			for (Object item : list) {
				encodeJsonValue(generator, item);
			}
			generator.writeEnd();
		} else {
			generator.write(data.toString());
		}
	}

	// ----------------

	private enum StreamState {
		EMPTY, UNKNOWN, NON_EMPTY
	}

	private static StreamState streamState(InputStream inputStream) {
		try {
			if (inputStream.available() > 0) {
				return StreamState.NON_EMPTY;
			} else if (inputStream.markSupported()) {
				inputStream.mark(1);
				int read = inputStream.read();
				inputStream.reset();
				if (read == -1) {
					return StreamState.EMPTY;
				} else {
					return StreamState.NON_EMPTY;
				}
			}
			return StreamState.UNKNOWN;
		} catch (IOException e) {
			throw new IllegalStateException(e);
		}
	}

	private static <T> Optional<T> parseOptStream(InputStream inputStream, Function<InputStream, Optional<T>> parser) {
		var state = streamState(inputStream);
		if (state == StreamState.EMPTY) {
			return Optional.empty();
		} else if (state == StreamState.UNKNOWN) {
			try {
				return parser.apply(inputStream);
			} catch (JsonException e) {
				return Optional.empty();
			}
		} else {
			return parser.apply(inputStream);
		}
	}

	private static <T> _Base.Nillable<T> parseNilStream(InputStream inputStream, Function<InputStream, _Base.Nillable<T>> parser) {
		var state = streamState(inputStream);
		if (state == StreamState.EMPTY) {
			return _NillableImpl.undefined();
		} else if (state == StreamState.UNKNOWN) {
			try {
				return parser.apply(inputStream);
			} catch (JsonException e) {
				return _NillableImpl.undefined();
			}
		} else {
			return parser.apply(inputStream);
		}
	}

	private static <T> List<T> parseListStream(InputStream inputStream, String contentType,
			Function<JsonValue, T> mapper) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.ARRAY) {
			throw new IllegalArgumentException("Expected array value, but got: " + value);
		}
		return ((JsonArray) value).stream().map(mapper).toList();
	}

	private static <T> Optional<List<T>> parseOptListStream(InputStream inputStream, String contentType,
			Function<JsonValue, T> mapper) {
		return parseOptStream(inputStream, is -> {
			return Optional.of(parseListStream(is, contentType, mapper));
		});
	}

	private static <T> Optional<List<T>> parseNullListStream(InputStream inputStream, String contentType,
			Function<JsonValue, T> mapper) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.ARRAY) {
			return Optional.of(((JsonArray) value).stream().map(mapper).toList());
		}
		throw new IllegalArgumentException("Expected array value or null, but got: " + value);
	}

	private static <T> _Base.Nillable<List<T>> parseNilListStream(InputStream inputStream, String contentType,
			Function<JsonValue, T> mapper) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.ARRAY) {
				return _NillableImpl.of(((JsonArray) value).stream().map(mapper).toList());
			}
			throw new IllegalArgumentException("Expected array value or null, but got: " + value);
		});
	}

	// ----------------

	public static boolean parseBoolean(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.TRUE
				&& value.getValueType() != JsonValue.ValueType.FALSE) {
			throw new IllegalArgumentException("Expected boolean value, but got: " + value);
		}
		return value.getValueType() == JsonValue.ValueType.TRUE;
	}

	private static Boolean parseBooleanNull(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.TRUE) {
			return Boolean.TRUE;
		} else if (value.getValueType() == JsonValue.ValueType.FALSE) {
			return Boolean.FALSE;
		} else if (value.getValueType() == JsonValue.ValueType.NULL) {
			return null;
		}
		throw new IllegalArgumentException("Expected boolean value or null, but got: " + value);
	}

	public static Optional<Boolean> parseOptBoolean(InputStream inputStream, String contentType) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.TRUE) {
				return OPTIONAL_TRUE;
			} else if (value.getValueType() == JsonValue.ValueType.FALSE) {
				return OPTIONAL_FALSE;
			}
			throw new IllegalArgumentException("Expected boolean value or null, but got: " + value);
		});
	}

	public static Optional<Boolean> parseNullBoolean(InputStream inputStream, String contentType) {
		var result = parseBooleanNull(inputStream, contentType);
		if (result == null) {
			return Optional.empty();
		} else if (result.booleanValue()) {
			return OPTIONAL_TRUE;
		} else {
			return OPTIONAL_FALSE;
		}
	}

	public static _Base.Nillable<Boolean> parseNilBoolean(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var result = parseBooleanNull(is, contentType);
			if (result == null) {
				return _NillableImpl.nill();
			} else if (result.booleanValue()) {
				return NILLABLE_TRUE;
			} else {
				return NILLABLE_FALSE;
			}
		});
	}

	public static List<Boolean> parseBooleans(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() == JsonValue.ValueType.TRUE) {
				return Boolean.TRUE;
			} else if (v.getValueType() == JsonValue.ValueType.FALSE) {
				return Boolean.FALSE;
			}
			throw new IllegalArgumentException("Expected boolean value, but got: " + v);
		});
	}

	public static Optional<List<Boolean>> parseOptBooleans(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() == JsonValue.ValueType.TRUE) {
				return Boolean.TRUE;
			} else if (v.getValueType() == JsonValue.ValueType.FALSE) {
				return Boolean.FALSE;
			}
			throw new IllegalArgumentException("Expected boolean value, but got: " + v);
		});
	}

	public static Optional<List<Boolean>> parseNullBooleans(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() == JsonValue.ValueType.TRUE) {
				return Boolean.TRUE;
			} else if (v.getValueType() == JsonValue.ValueType.FALSE) {
				return Boolean.FALSE;
			}
			throw new IllegalArgumentException("Expected boolean value, but got: " + v);
		});
	}

	public static _Base.Nillable<List<Boolean>> parseNilBooleans(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() == JsonValue.ValueType.TRUE) {
				return Boolean.TRUE;
			} else if (v.getValueType() == JsonValue.ValueType.FALSE) {
				return Boolean.FALSE;
			}
			throw new IllegalArgumentException("Expected boolean value, but got: " + v);
		});
	}

	// ----------------
	public static short parseShort(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.NUMBER) {
			throw new IllegalArgumentException("Expected number value, but got: " + value);
		}
		return (short) ((JsonNumber) value).intValue();
	}

	public static Optional<Short> parseOptShort(InputStream inputStream, String contentType) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + value);
			}
			return Optional.of((short) ((JsonNumber) value).intValue());
		});
	}

	public static Optional<Short> parseNullShort(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
			return Optional.of((short) ((JsonNumber) value).intValue());
		}
		throw new IllegalArgumentException("Expected number value or null, but got: " + value);
	}

	public static _Base.Nillable<Short> parseNilShort(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
				return _NillableImpl.of((short) ((JsonNumber) value).intValue());
			}
			throw new IllegalArgumentException("Expected number value or null, but got: " + value);
		});
	}

	public static List<Short> parseShorts(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (short) ((JsonNumber) v).intValue();
		});
	}

	public static Optional<List<Short>> parseOptShorts(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (short) ((JsonNumber) v).intValue();
		});
	}

	public static Optional<List<Short>> parseNullShorts(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (short) ((JsonNumber) v).intValue();
		});
	}

	public static _Base.Nillable<List<Short>> parseNilShorts(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (short) ((JsonNumber) v).intValue();
		});
	}

	// ----------------
	public static int parseInt(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.NUMBER) {
			throw new IllegalArgumentException("Expected number value, but got: " + value);
		}
		return ((JsonNumber) value).intValue();
	}

	public static OptionalInt parseOptInt(InputStream inputStream, String contentType) {
		var state = streamState(inputStream);
		if (state == StreamState.EMPTY) {
			return OptionalInt.empty();
		} else if (state == StreamState.UNKNOWN) {
			try {
				return OptionalInt.of(parseInt(inputStream, contentType));
			} catch (JsonException e) {
				return OptionalInt.empty();
			}
		} else {
			return OptionalInt.of(parseInt(inputStream, contentType));
		}
	}

	public static OptionalInt parseNullInt(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return OptionalInt.empty();
		} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
			return OptionalInt.of(((JsonNumber) value).intValue());
		}
		throw new IllegalArgumentException("Expected number value or null, but got: " + value);
	}

	public static _Base.Nillable<Integer> parseNilInt(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
				return _NillableImpl.of(((JsonNumber) value).intValue());
			}
			throw new IllegalArgumentException("Expected number value or null, but got: " + value);
		});
	}

	public static List<Integer> parseInts(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).intValue();
		});
	}

	public static Optional<List<Integer>> parseOptInts(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).intValue();
		});
	}

	public static Optional<List<Integer>> parseNullInts(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).intValue();
		});
	}

	public static _Base.Nillable<List<Integer>> parseNilInts(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).intValue();
		});
	}

	// ----------------
	public static long parseLong(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.NUMBER) {
			throw new IllegalArgumentException("Expected number value, but got: " + value);
		}
		return ((JsonNumber) value).longValue();
	}

	public static OptionalLong parseOptLong(InputStream inputStream, String contentType) {
		var state = streamState(inputStream);
		if (state == StreamState.EMPTY) {
			return OptionalLong.empty();
		} else if (state == StreamState.UNKNOWN) {
			try {
				return OptionalLong.of(parseLong(inputStream, contentType));
			} catch (JsonException e) {
				return OptionalLong.empty();
			}
		} else {
			return OptionalLong.of(parseLong(inputStream, contentType));
		}
	}

	public static OptionalLong parseNullLong(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return OptionalLong.empty();
		} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
			return OptionalLong.of(((JsonNumber) value).longValue());
		}
		throw new IllegalArgumentException("Expected number value or null, but got: " + value);
	}

	public static _Base.Nillable<Long> parseNilLong(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
				return _NillableImpl.of(((JsonNumber) value).longValue());
			}
			throw new IllegalArgumentException("Expected number value or null, but got: " + value);
		});
	}

	public static List<Long> parseLongs(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).longValue();
		});
	}

	public static Optional<List<Long>> parseOptLongs(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).longValue();
		});
	}

	public static Optional<List<Long>> parseNullLongs(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).longValue();
		});
	}

	public static _Base.Nillable<List<Long>> parseNilLongs(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).longValue();
		});
	}

	// ----------------
	public static double parseDouble(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.NUMBER) {
			throw new IllegalArgumentException("Expected number value, but got: " + value);
		}
		return ((JsonNumber) value).doubleValue();
	}

	public static OptionalDouble parseOptDouble(InputStream inputStream, String contentType) {
		var state = streamState(inputStream);
		if (state == StreamState.EMPTY) {
			return OptionalDouble.empty();
		} else if (state == StreamState.UNKNOWN) {
			try {
				return OptionalDouble.of(parseDouble(inputStream, contentType));
			} catch (JsonException e) {
				return OptionalDouble.empty();
			}
		} else {
			return OptionalDouble.of(parseDouble(inputStream, contentType));
		}
	}

	public static OptionalDouble parseNullDouble(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return OptionalDouble.empty();
		} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
			return OptionalDouble.of(((JsonNumber) value).doubleValue());
		}
		throw new IllegalArgumentException("Expected number value or null, but got: " + value);
	}

	public static _Base.Nillable<Double> parseNilDouble(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
				return _NillableImpl.of(((JsonNumber) value).doubleValue());
			}
			throw new IllegalArgumentException("Expected number value or null, but got: " + value);
		});
	}

	public static List<Double> parseDoubles(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).doubleValue();
		});
	}

	public static Optional<List<Double>> parseOptDoubles(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).doubleValue();
		});
	}

	public static Optional<List<Double>> parseNullDoubles(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).doubleValue();
		});
	}

	public static _Base.Nillable<List<Double>> parseNilDoubles(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return ((JsonNumber) v).doubleValue();
		});
	}

	// ----------------
	public static Float parseFloat(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.NUMBER) {
			throw new IllegalArgumentException("Expected number value, but got: " + value);
		}
		return (float) ((JsonNumber) value).doubleValue();
	}

	public static Optional<Float> parseOptFloat(InputStream inputStream, String contentType) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + value);
			}
			return Optional.of((float) ((JsonNumber) value).doubleValue());
		});
	}

	public static Optional<Float> parseNullFloat(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
			return Optional.of((float) ((JsonNumber) value).doubleValue());
		}
		throw new IllegalArgumentException("Expected number value or null, but got: " + value);
	}

	public static _Base.Nillable<Float> parseNilFloat(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.NUMBER) {
				return _NillableImpl.of((float) ((JsonNumber) value).doubleValue());
			}
			throw new IllegalArgumentException("Expected number value or null, but got: " + value);
		});
	}

	public static List<Float> parseFloats(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (float) ((JsonNumber) v).doubleValue();
		});
	}

	public static Optional<List<Float>> parseOptFloats(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (float) ((JsonNumber) v).doubleValue();
		});
	}

	public static Optional<List<Float>> parseNullFloats(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (float) ((JsonNumber) v).doubleValue();
		});
	}

	public static _Base.Nillable<List<Float>> parseNilFloats(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.NUMBER) {
				throw new IllegalArgumentException("Expected number value, but got: " + v);
			}
			return (float) ((JsonNumber) v).doubleValue();
		});
	}

	// ----------------
	public static String parseString(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.STRING) {
			throw new IllegalArgumentException("Expected string value, but got: " + value);
		}
		return ((JsonString) value).getString();
	}

	public static Optional<String> parseOptString(InputStream inputStream, String contentType) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + value);
			}
			return Optional.of(((JsonString) value).getString());
		});
	}

	public static Optional<String> parseNullString(InputStream inputStream, String contentType) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.STRING) {
			return Optional.of(((JsonString) value).getString());
		}
		throw new IllegalArgumentException("Expected string value or null, but got: " + value);
	}

	public static _Base.Nillable<String> parseNilString(InputStream inputStream, String contentType) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.STRING) {
				return _NillableImpl.of(((JsonString) value).getString());
			}
			throw new IllegalArgumentException("Expected string value or null, but got: " + value);
		});
	}

	public static List<String> parseStrings(InputStream inputStream, String contentType) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return ((JsonString) v).getString();
		});
	}

	public static Optional<List<String>> parseOptStrings(InputStream inputStream, String contentType) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return ((JsonString) v).getString();
		});
	}

	public static Optional<List<String>> parseNullStrings(InputStream inputStream, String contentType) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return ((JsonString) v).getString();
		});
	}

	public static _Base.Nillable<List<String>> parseNilStrings(InputStream inputStream, String contentType) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return ((JsonString) v).getString();
		});
	}

	// ----------------
	public static <T> T parseLiteral(InputStream inputStream, String contentType, Function<String, T> parser) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.STRING) {
			throw new IllegalArgumentException("Expected string value, but got: " + value);
		}
		return parser.apply(((JsonString) value).getString());
	}

	public static <T> Optional<T> parseOptLiteral(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + value);
			}
			return Optional.of(parser.apply(((JsonString) value).getString()));
		});
	}

	public static <T> Optional<T> parseNullLiteral(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.STRING) {
			return Optional.of(parser.apply(((JsonString) value).getString()));
		}
		throw new IllegalArgumentException("Expected string value or null, but got: " + value);
	}

	public static <T> _Base.Nillable<T> parseNilLiteral(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.STRING) {
				return _NillableImpl.of(parser.apply(((JsonString) value).getString()));
			}
			throw new IllegalArgumentException("Expected string value or null, but got: " + value);
		});
	}

	public static <T> List<T> parseLiterals(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return parser.apply(((JsonString) v).getString());
		});
	}

	public static <T> Optional<List<T>> parseOptLiterals(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value, but got: " + v);
			}
			return parser.apply(((JsonString) v).getString());
		});
	}

	public static <T> Optional<List<T>> parseNullLiterals(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value or null, but got: " + v);
			}
			return parser.apply(((JsonString) v).getString());
		});
	}

	public static <T> _Base.Nillable<List<T>> parseNilLiterals(InputStream inputStream, String contentType,
			Function<String, T> parser) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.STRING) {
				throw new IllegalArgumentException("Expected string value or null, but got: " + v);
			}
			return parser.apply(((JsonString) v).getString());
		});
	}

	// ----------------
	public static LocalDate parseLocalDate(InputStream inputStream, String contentType) {
		return parseLiteral(inputStream, contentType, LocalDate::parse);
	}

	public static Optional<LocalDate> parseOptLocalDate(InputStream inputStream, String contentType) {
		return parseOptLiteral(inputStream, contentType, LocalDate::parse);
	}

	public static Optional<LocalDate> parseNullLocalDate(InputStream inputStream, String contentType) {
		return parseNullLiteral(inputStream, contentType, LocalDate::parse);
	}

	public static _Base.Nillable<LocalDate> parseNilLocalDate(InputStream inputStream, String contentType) {
		return parseNilLiteral(inputStream, contentType, LocalDate::parse);
	}

	public static List<LocalDate> parseLocalDates(InputStream inputStream, String contentType) {
		return parseLiterals(inputStream, contentType, LocalDate::parse);
	}

	public static Optional<List<LocalDate>> parseOptLocalDates(InputStream inputStream, String contentType) {
		return parseOptLiterals(inputStream, contentType, LocalDate::parse);
	}

	public static Optional<List<LocalDate>> parseNullLocalDates(InputStream inputStream, String contentType) {
		return parseNullLiterals(inputStream, contentType, LocalDate::parse);
	}

	public static _Base.Nillable<List<LocalDate>> parseNilLocalDates(InputStream inputStream, String contentType) {
		return parseNilLiterals(inputStream, contentType, LocalDate::parse);
	}

	// ----------------
	public static LocalDateTime parseLocalDateTime(InputStream inputStream, String contentType) {
		return parseLiteral(inputStream, contentType, LocalDateTime::parse);
	}

	public static Optional<LocalDateTime> parseOptLocalDateTime(InputStream inputStream, String contentType) {
		return parseOptLiteral(inputStream, contentType, LocalDateTime::parse);
	}

	public static Optional<LocalDateTime> parseNullLocalDateTime(InputStream inputStream, String contentType) {
		return parseNullLiteral(inputStream, contentType, LocalDateTime::parse);
	}

	public static _Base.Nillable<LocalDateTime> parseNilLocalDateTime(InputStream inputStream, String contentType) {
		return parseNilLiteral(inputStream, contentType, LocalDateTime::parse);
	}

	public static List<LocalDateTime> parseLocalDateTimes(InputStream inputStream, String contentType) {
		return parseLiterals(inputStream, contentType, LocalDateTime::parse);
	}

	public static Optional<List<LocalDateTime>> parseNullLocalDateTimes(InputStream inputStream, String contentType) {
		return parseNullLiterals(inputStream, contentType, LocalDateTime::parse);
	}

	public static Optional<List<LocalDateTime>> parseOptLocalDateTimes(InputStream inputStream, String contentType) {
		return parseOptLiterals(inputStream, contentType, LocalDateTime::parse);
	}

	public static _Base.Nillable<List<LocalDateTime>> parseNilLocalDateTimes(InputStream inputStream,
			String contentType) {
		return parseNilLiterals(inputStream, contentType, LocalDateTime::parse);
	}

	// ----------------
	public static ZonedDateTime parseZonedDateTime(InputStream inputStream, String contentType) {
		return parseLiteral(inputStream, contentType, ZonedDateTime::parse);
	}

	public static Optional<ZonedDateTime> parseOptZonedDateTime(InputStream inputStream, String contentType) {
		return parseOptLiteral(inputStream, contentType, ZonedDateTime::parse);
	}

	public static Optional<ZonedDateTime> parseNullZonedDateTime(InputStream inputStream, String contentType) {
		return parseNullLiteral(inputStream, contentType, ZonedDateTime::parse);
	}

	public static _Base.Nillable<ZonedDateTime> parseNilZonedDateTime(InputStream inputStream, String contentType) {
		return parseNilLiteral(inputStream, contentType, ZonedDateTime::parse);
	}

	public static List<ZonedDateTime> parseZonedDateTimes(InputStream inputStream, String contentType) {
		return parseLiterals(inputStream, contentType, ZonedDateTime::parse);
	}

	public static Optional<List<ZonedDateTime>> parseOptZonedDateTimes(InputStream inputStream, String contentType) {
		return parseOptLiterals(inputStream, contentType, ZonedDateTime::parse);
	}

	public static Optional<List<ZonedDateTime>> parseNullZonedDateTimes(InputStream inputStream, String contentType) {
		return parseNullLiterals(inputStream, contentType, ZonedDateTime::parse);
	}

	public static _Base.Nillable<List<ZonedDateTime>> parseNilZonedDateTimes(InputStream inputStream,
			String contentType) {
		return parseNilLiterals(inputStream, contentType, ZonedDateTime::parse);
	}

	// ----------------
	public static <T> T parseObject(InputStream inputStream, String contentType, Function<JsonObject, T> parser) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() != JsonValue.ValueType.OBJECT) {
			throw new IllegalArgumentException("Expected object value, but got: " + value);
		}
		return parser.apply((JsonObject) value);
	}

	public static <T> Optional<T> parseOptObject(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		return parseOptStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() != JsonValue.ValueType.OBJECT) {
				throw new IllegalArgumentException("Expected object value, but got: " + value);
			}
			return Optional.of(parser.apply((JsonObject) value));
		});
	}

	public static <T> Optional<T> parseNullObject(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		var value = parseValue(inputStream, contentType);
		if (value.getValueType() == JsonValue.ValueType.NULL) {
			return Optional.empty();
		} else if (value.getValueType() == JsonValue.ValueType.OBJECT) {
			return Optional.of(parser.apply((JsonObject) value));
		}
		throw new IllegalArgumentException("Expected object value or null, but got: " + value);
	}

	public static <T> _Base.Nillable<T> parseNilObject(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		return parseNilStream(inputStream, is -> {
			var value = parseValue(is, contentType);
			if (value.getValueType() == JsonValue.ValueType.NULL) {
				return _NillableImpl.nill();
			} else if (value.getValueType() == JsonValue.ValueType.OBJECT) {
				return _NillableImpl.of(parser.apply((JsonObject) value));
			}
			throw new IllegalArgumentException("Expected object value or null, but got: " + value);
		});
	}

	public static <T> List<T> parseObjects(InputStream inputStream, String contentType, Function<JsonObject, T> parser) {
		return parseListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.OBJECT) {
				throw new IllegalArgumentException("Expected object value, but got: " + v);
			}
			return parser.apply((JsonObject) v);
		});
	}

	public static <T> Optional<List<T>> parseOptObjects(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		return parseOptListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.OBJECT) {
				throw new IllegalArgumentException("Expected object value, but got: " + v);
			}
			return parser.apply((JsonObject) v);
		});
	}

	public static <T> Optional<List<T>> parseNullObjects(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		return parseNullListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.OBJECT) {
				throw new IllegalArgumentException("Expected object value, but got: " + v);
			}
			return parser.apply((JsonObject) v);
		});
	}

	public static <T> _Base.Nillable<List<T>> parseNilObjects(InputStream inputStream, String contentType,
			Function<JsonObject, T> parser) {
		return parseNilListStream(inputStream, contentType, v -> {
			if (v.getValueType() != JsonValue.ValueType.OBJECT) {
				throw new IllegalArgumentException("Expected object value, but got: " + v);
			}
			return parser.apply((JsonObject) v);
		});
	}

	// ----------------

	public static JsonValue parseValue(Path path, String contentType) {
		try (InputStream inputStream = Files.newInputStream(path)) {
			return parseValue(inputStream, contentType);
		} catch (IOException e) {
			throw new IllegalStateException(e);
		}
	}

	public static JsonValue parseValue(InputStream inputStream, String contentType) {
		if (contentType != null && contentType.startsWith("application/json")) {
			return parseJsonValue(inputStream);
		}
		throw new IllegalArgumentException("Unsupported content type: " + contentType);
	}

	private static JsonValue parseJsonValue(InputStream inputStream) {
		return Json.createReader(inputStream).readValue();
	}
}