// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.rest.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;

import dev.rsdlang.sample.server.service.model.PatchableRecord_Basic;

public class PatchableRecord_BasicDataImpl extends _BaseDataImpl implements PatchableRecord_Basic.Data {
	PatchableRecord_BasicDataImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public String version() {
		return _JsonUtils.mapString(data, "version");
	}

	@Override
	public boolean valueBoolean() {
		return _JsonUtils.mapBoolean(data, "valueBoolean");
	}

	@Override
	public short valueShort() {
		return _JsonUtils.mapShort(data, "valueShort");
	}

	@Override
	public int valueInt() {
		return _JsonUtils.mapInt(data, "valueInt");
	}

	@Override
	public long valueLong() {
		return _JsonUtils.mapLong(data, "valueLong");
	}

	@Override
	public float valueFloat() {
		return _JsonUtils.mapFloat(data, "valueFloat");
	}

	@Override
	public double valueDouble() {
		return _JsonUtils.mapDouble(data, "valueDouble");
	}

	@Override
	public String valueString() {
		return _JsonUtils.mapString(data, "valueString");
	}

	@Override
	public LocalDate valueLocalDate() {
		return _JsonUtils.mapLocalDate(data, "valueLocalDate");
	}

	@Override
	public LocalDateTime valueLocalDateTime() {
		return _JsonUtils.mapLocalDateTime(data, "valueLocalDateTime");
	}

	@Override
	public ZonedDateTime valueZonedDateTime() {
		return _JsonUtils.mapZonedDateTime(data, "valueZonedDateTime");
	}

	public static PatchableRecord_Basic.Data of(JsonObject obj) {
		return new PatchableRecord_BasicDataImpl(obj);
	}

	public String toString() {
		return "%s[%s=%s@%s=%s]".formatted(getClass().getSimpleName(), "key", key(), "version", version());
	}

	public static class DataBuilderImpl implements PatchableRecord_Basic.DataBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		@Override
		public PatchableRecord_Basic.DataBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder version(String version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueBoolean(boolean valueBoolean) {
			$builder.add("valueBoolean", valueBoolean);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueShort(short valueShort) {
			$builder.add("valueShort", valueShort);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueInt(int valueInt) {
			$builder.add("valueInt", valueInt);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueLong(long valueLong) {
			$builder.add("valueLong", valueLong);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueFloat(float valueFloat) {
			$builder.add("valueFloat", valueFloat);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueDouble(double valueDouble) {
			$builder.add("valueDouble", valueDouble);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueString(String valueString) {
			if (valueString == null) {
				return this;
			}
			$builder.add("valueString", valueString);
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueLocalDate(LocalDate valueLocalDate) {
			if (valueLocalDate == null) {
				return this;
			}
			$builder.add("valueLocalDate", valueLocalDate.toString());
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueLocalDateTime(LocalDateTime valueLocalDateTime) {
			if (valueLocalDateTime == null) {
				return this;
			}
			$builder.add("valueLocalDateTime", valueLocalDateTime.toString());
			return this;
		}

		@Override
		public PatchableRecord_Basic.DataBuilder valueZonedDateTime(ZonedDateTime valueZonedDateTime) {
			if (valueZonedDateTime == null) {
				return this;
			}
			$builder.add("valueZonedDateTime", valueZonedDateTime.toString());
			return this;
		}

		public PatchableRecord_Basic.Data build() {
			return new PatchableRecord_BasicDataImpl($builder.build());
		}
	}

	public static PatchableRecord_Basic.DataBuilder builder() {
		return new DataBuilderImpl();
	}
}
