// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.model.impl.json;

import dev.rsdlang.sample.server.model.ZoneId;
import dev.rsdlang.sample.server.MyRange;

public class _ScalarSupport {
	public static Object toJson(Object value) {
		if (value instanceof ZoneId) {
			return ZoneIdToJson((ZoneId) value);
		}
		if (value instanceof MyRange) {
			return RangeToJson((MyRange) value);
		}
		return value;
	}

	public static ZoneId ZoneIdFromJson(String s) {
		return ZoneId.of(s);
	}
	public static String ZoneIdToJson(ZoneId value) {
		return value.toString();
	}

	public static MyRange RangeFromJson(String s) {
		return MyRange.parse(s);
	}
	public static String RangeToJson(MyRange value) {
		return MyRange.toString(value);
	}

}
