// Generated by RSD - Do not modify
package dev.rsdlang.sample.client.jdkhttp.impl.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.List;

import jakarta.json.Json;
import jakarta.json.JsonNumber;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;
import jakarta.json.JsonString;
import jakarta.json.JsonValue;

import dev.rsdlang.sample.client.model._Base;
import dev.rsdlang.sample.client.model.PatchableRecord_Basic_List_Null;

public class PatchableRecord_Basic_List_NullPatchImpl extends _BaseDataImpl implements PatchableRecord_Basic_List_Null.Patch {
	static class ValueBooleanSetChangeImpl extends _ChangeSupport.ValueElementsChange<Boolean> implements ValueBooleanSetChange {
		ValueBooleanSetChangeImpl(JsonObject data) {
			super(data, v -> v.getValueType() == JsonValue.ValueType.TRUE);
		}
	}

	static class ValueBooleanMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Boolean, Boolean> implements ValueBooleanMergeChange {
		ValueBooleanMergeChangeImpl(JsonObject data) {
			super(data, v -> v.getValueType() == JsonValue.ValueType.TRUE, v -> v.getValueType() == JsonValue.ValueType.TRUE);
		}
	}

	static class ValueShortSetChangeImpl extends _ChangeSupport.ValueElementsChange<Short> implements ValueShortSetChange {
		ValueShortSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).numberValue().shortValue());
		}
	}

	static class ValueShortMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Short, Short> implements ValueShortMergeChange {
		ValueShortMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).numberValue().shortValue(), v -> ((JsonNumber) v).numberValue().shortValue());
		}
	}

	static class ValueIntSetChangeImpl extends _ChangeSupport.ValueElementsChange<Integer> implements ValueIntSetChange {
		ValueIntSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).intValue());
		}
	}

	static class ValueIntMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Integer, Integer> implements ValueIntMergeChange {
		ValueIntMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).intValue(), v -> ((JsonNumber) v).intValue());
		}
	}

	static class ValueLongSetChangeImpl extends _ChangeSupport.ValueElementsChange<Long> implements ValueLongSetChange {
		ValueLongSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).longValue());
		}
	}

	static class ValueLongMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Long, Long> implements ValueLongMergeChange {
		ValueLongMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).longValue(), v -> ((JsonNumber) v).longValue());
		}
	}

	static class ValueFloatSetChangeImpl extends _ChangeSupport.ValueElementsChange<Float> implements ValueFloatSetChange {
		ValueFloatSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber)v).numberValue().floatValue());
		}
	}

	static class ValueFloatMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Float, Float> implements ValueFloatMergeChange {
		ValueFloatMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber)v).numberValue().floatValue(), v -> ((JsonNumber)v).numberValue().floatValue());
		}
	}

	static class ValueDoubleSetChangeImpl extends _ChangeSupport.ValueElementsChange<Double> implements ValueDoubleSetChange {
		ValueDoubleSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).doubleValue());
		}
	}

	static class ValueDoubleMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<Double, Double> implements ValueDoubleMergeChange {
		ValueDoubleMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonNumber) v).doubleValue(), v -> ((JsonNumber) v).doubleValue());
		}
	}

	static class ValueStringSetChangeImpl extends _ChangeSupport.ValueElementsChange<String> implements ValueStringSetChange {
		ValueStringSetChangeImpl(JsonObject data) {
			super(data, v -> ((JsonString) v).getString());
		}
	}

	static class ValueStringMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<String, String> implements ValueStringMergeChange {
		ValueStringMergeChangeImpl(JsonObject data) {
			super(data, v -> ((JsonString) v).getString(), v -> ((JsonString) v).getString());
		}
	}

	static class ValueLocalDateSetChangeImpl extends _ChangeSupport.ValueElementsChange<LocalDate> implements ValueLocalDateSetChange {
		ValueLocalDateSetChangeImpl(JsonObject data) {
			super(data, v -> LocalDate.parse(((JsonString)v).getString()));
		}
	}

	static class ValueLocalDateMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<LocalDate, LocalDate> implements ValueLocalDateMergeChange {
		ValueLocalDateMergeChangeImpl(JsonObject data) {
			super(data, v -> LocalDate.parse(((JsonString)v).getString()), v -> LocalDate.parse(((JsonString)v).getString()));
		}
	}

	static class ValueLocalDateTimeSetChangeImpl extends _ChangeSupport.ValueElementsChange<LocalDateTime> implements ValueLocalDateTimeSetChange {
		ValueLocalDateTimeSetChangeImpl(JsonObject data) {
			super(data, v -> LocalDateTime.parse(((JsonString)v).getString()));
		}
	}

	static class ValueLocalDateTimeMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<LocalDateTime, LocalDateTime> implements ValueLocalDateTimeMergeChange {
		ValueLocalDateTimeMergeChangeImpl(JsonObject data) {
			super(data, v -> LocalDateTime.parse(((JsonString)v).getString()), v -> LocalDateTime.parse(((JsonString)v).getString()));
		}
	}

	static class ValueZonedDateTimeSetChangeImpl extends _ChangeSupport.ValueElementsChange<ZonedDateTime> implements ValueZonedDateTimeSetChange {
		ValueZonedDateTimeSetChangeImpl(JsonObject data) {
			super(data, v -> ZonedDateTime.parse(((JsonString)v).getString()));
		}
	}

	static class ValueZonedDateTimeMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<ZonedDateTime, ZonedDateTime> implements ValueZonedDateTimeMergeChange {
		ValueZonedDateTimeMergeChangeImpl(JsonObject data) {
			super(data, v -> ZonedDateTime.parse(((JsonString)v).getString()), v -> ZonedDateTime.parse(((JsonString)v).getString()));
		}
	}

	PatchableRecord_Basic_List_NullPatchImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public String version() {
		return _JsonUtils.mapString(data, "version");
	}

	public _Base.Nillable<ValueBooleanChange> valueBoolean() {
		return _JsonUtils.mapNilObject(data, "valueBoolean", o -> _ChangeSupport.of(o, "@type", ValueBooleanSetChangeImpl::new, ValueBooleanMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueShortChange> valueShort() {
		return _JsonUtils.mapNilObject(data, "valueShort", o -> _ChangeSupport.of(o, "@type", ValueShortSetChangeImpl::new, ValueShortMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueIntChange> valueInt() {
		return _JsonUtils.mapNilObject(data, "valueInt", o -> _ChangeSupport.of(o, "@type", ValueIntSetChangeImpl::new, ValueIntMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueLongChange> valueLong() {
		return _JsonUtils.mapNilObject(data, "valueLong", o -> _ChangeSupport.of(o, "@type", ValueLongSetChangeImpl::new, ValueLongMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueFloatChange> valueFloat() {
		return _JsonUtils.mapNilObject(data, "valueFloat", o -> _ChangeSupport.of(o, "@type", ValueFloatSetChangeImpl::new, ValueFloatMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueDoubleChange> valueDouble() {
		return _JsonUtils.mapNilObject(data, "valueDouble", o -> _ChangeSupport.of(o, "@type", ValueDoubleSetChangeImpl::new, ValueDoubleMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueStringChange> valueString() {
		return _JsonUtils.mapNilObject(data, "valueString", o -> _ChangeSupport.of(o, "@type", ValueStringSetChangeImpl::new, ValueStringMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueLocalDateChange> valueLocalDate() {
		return _JsonUtils.mapNilObject(data, "valueLocalDate", o -> _ChangeSupport.of(o, "@type", ValueLocalDateSetChangeImpl::new, ValueLocalDateMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueLocalDateTimeChange> valueLocalDateTime() {
		return _JsonUtils.mapNilObject(data, "valueLocalDateTime", o -> _ChangeSupport.of(o, "@type", ValueLocalDateTimeSetChangeImpl::new, ValueLocalDateTimeMergeChangeImpl::new));
	}

	public _Base.Nillable<ValueZonedDateTimeChange> valueZonedDateTime() {
		return _JsonUtils.mapNilObject(data, "valueZonedDateTime", o -> _ChangeSupport.of(o, "@type", ValueZonedDateTimeSetChangeImpl::new, ValueZonedDateTimeMergeChangeImpl::new));
	}

	public static class PatchBuilderImpl implements PatchableRecord_Basic_List_Null.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public PatchableRecord_Basic_List_Null.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder version(String version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueBoolean(ValueBooleanChange valueBoolean) {
			$builder.add("valueBoolean", ((_BaseDataImpl) valueBoolean).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueBoolean(List<Boolean> additions, List<Boolean> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonBooleanArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonBooleanArray(removals));
			$builder.add("valueBoolean", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueBoolean(List<Boolean> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonBooleanArray(elements));
			$builder.add("valueBoolean", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueShort(ValueShortChange valueShort) {
			$builder.add("valueShort", ((_BaseDataImpl) valueShort).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueShort(List<Short> additions, List<Short> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonShortArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonShortArray(removals));
			$builder.add("valueShort", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueShort(List<Short> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonShortArray(elements));
			$builder.add("valueShort", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueInt(ValueIntChange valueInt) {
			$builder.add("valueInt", ((_BaseDataImpl) valueInt).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueInt(List<Integer> additions, List<Integer> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonIntArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonIntArray(removals));
			$builder.add("valueInt", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueInt(List<Integer> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonIntArray(elements));
			$builder.add("valueInt", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueLong(ValueLongChange valueLong) {
			$builder.add("valueLong", ((_BaseDataImpl) valueLong).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLong(List<Long> additions, List<Long> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLongArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLongArray(removals));
			$builder.add("valueLong", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLong(List<Long> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLongArray(elements));
			$builder.add("valueLong", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueFloat(ValueFloatChange valueFloat) {
			$builder.add("valueFloat", ((_BaseDataImpl) valueFloat).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueFloat(List<Float> additions, List<Float> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonFloatArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonFloatArray(removals));
			$builder.add("valueFloat", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueFloat(List<Float> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonFloatArray(elements));
			$builder.add("valueFloat", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueDouble(ValueDoubleChange valueDouble) {
			$builder.add("valueDouble", ((_BaseDataImpl) valueDouble).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueDouble(List<Double> additions, List<Double> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonDoubleArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonDoubleArray(removals));
			$builder.add("valueDouble", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueDouble(List<Double> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonDoubleArray(elements));
			$builder.add("valueDouble", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueString(ValueStringChange valueString) {
			$builder.add("valueString", ((_BaseDataImpl) valueString).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueString(List<String> additions, List<String> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonStringArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonStringArray(removals));
			$builder.add("valueString", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueString(List<String> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("valueString", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDate(ValueLocalDateChange valueLocalDate) {
			$builder.add("valueLocalDate", ((_BaseDataImpl) valueLocalDate).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDate(List<LocalDate> additions, List<LocalDate> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("valueLocalDate", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDate(List<LocalDate> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("valueLocalDate", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDateTime(ValueLocalDateTimeChange valueLocalDateTime) {
			$builder.add("valueLocalDateTime", ((_BaseDataImpl) valueLocalDateTime).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDateTime(List<LocalDateTime> additions, List<LocalDateTime> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("valueLocalDateTime", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueLocalDateTime(List<LocalDateTime> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("valueLocalDateTime", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.PatchBuilder valueZonedDateTime(ValueZonedDateTimeChange valueZonedDateTime) {
			$builder.add("valueZonedDateTime", ((_BaseDataImpl) valueZonedDateTime).data);
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueZonedDateTime(List<ZonedDateTime> additions, List<ZonedDateTime> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("valueZonedDateTime", $changeBuilder.build());
			return this;
		}

		public PatchableRecord_Basic_List_Null.PatchBuilder valueZonedDateTime(List<ZonedDateTime> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("valueZonedDateTime", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableRecord_Basic_List_Null.Patch build() {
			return new PatchableRecord_Basic_List_NullPatchImpl($builder.build());
		}
	}

	public static PatchableRecord_Basic_List_Null.Patch of(JsonObject obj) {
		return new PatchableRecord_Basic_List_NullPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
