// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.service.impl;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.ZoneId;

import jakarta.enterprise.context.ApplicationScoped;

import dev.rsdlang.sample.server.service.BuilderFactory;
import dev.rsdlang.sample.server.service.model.NilResult;
import dev.rsdlang.sample.server.service.model.SampleEnum;
import dev.rsdlang.sample.server.service.model.SimpleRecord;
import dev.rsdlang.sample.server.service.QueryParameterTypesService;

@ApplicationScoped
public class QueryParameterTypesServiceImpl implements QueryParameterTypesService {
	private final SimpleBooleanQueryParamHandler simpleBooleanQueryParamHandler;
	private final SimpleBooleanQueryParamOptHandler simpleBooleanQueryParamOptHandler;
	private final SimpleShortQueryParamHandler simpleShortQueryParamHandler;
	private final SimpleShortQueryParamOptHandler simpleShortQueryParamOptHandler;
	private final SimpleIntQueryParamHandler simpleIntQueryParamHandler;
	private final SimpleIntQueryParamOptHandler simpleIntQueryParamOptHandler;
	private final SimpleLongQueryParamHandler simpleLongQueryParamHandler;
	private final SimpleLongQueryParamOptHandler simpleLongQueryParamOptHandler;
	private final SimpleFloatQueryParamHandler simpleFloatQueryParamHandler;
	private final SimpleFloatQueryParamOptHandler simpleFloatQueryParamOptHandler;
	private final SimpleDoubleQueryParamHandler simpleDoubleQueryParamHandler;
	private final SimpleDoubleQueryParamOptHandler simpleDoubleQueryParamOptHandler;
	private final SimpleStringQueryParamHandler simpleStringQueryParamHandler;
	private final SimpleStringQueryParamOptHandler simpleStringQueryParamOptHandler;
	private final SimpleLocalDateQueryParamHandler simpleLocalDateQueryParamHandler;
	private final SimpleLocalDateQueryParamOptHandler simpleLocalDateQueryParamOptHandler;
	private final SimpleLocalDateTimeQueryParamHandler simpleLocalDateTimeQueryParamHandler;
	private final SimpleLocalDateTimeQueryParamOptHandler simpleLocalDateTimeQueryParamOptHandler;
	private final SimpleZonedDateTimeQueryParamHandler simpleZonedDateTimeQueryParamHandler;
	private final SimpleZonedDateTimeQueryParamOptHandler simpleZonedDateTimeQueryParamOptHandler;
	private final SimpleScalarQueryParamHandler simpleScalarQueryParamHandler;
	private final SimpleScalarQueryParamOptHandler simpleScalarQueryParamOptHandler;
	private final SimpleEnumQueryParamHandler simpleEnumQueryParamHandler;
	private final SimpleEnumQueryParamOptHandler simpleEnumQueryParamOptHandler;
	private final MultiQueryParamHandler multiQueryParamHandler;
	private final MultiQueryParamOptHandler multiQueryParamOptHandler;
	private final RecordQueryParamHandler recordQueryParamHandler;
	private final RecordQueryParamOptHandler recordQueryParamOptHandler;

	public QueryParameterTypesServiceImpl(SimpleBooleanQueryParamHandler simpleBooleanQueryParamHandler, SimpleBooleanQueryParamOptHandler simpleBooleanQueryParamOptHandler, SimpleShortQueryParamHandler simpleShortQueryParamHandler, SimpleShortQueryParamOptHandler simpleShortQueryParamOptHandler, SimpleIntQueryParamHandler simpleIntQueryParamHandler, SimpleIntQueryParamOptHandler simpleIntQueryParamOptHandler, SimpleLongQueryParamHandler simpleLongQueryParamHandler, SimpleLongQueryParamOptHandler simpleLongQueryParamOptHandler, SimpleFloatQueryParamHandler simpleFloatQueryParamHandler, SimpleFloatQueryParamOptHandler simpleFloatQueryParamOptHandler, SimpleDoubleQueryParamHandler simpleDoubleQueryParamHandler, SimpleDoubleQueryParamOptHandler simpleDoubleQueryParamOptHandler, SimpleStringQueryParamHandler simpleStringQueryParamHandler, SimpleStringQueryParamOptHandler simpleStringQueryParamOptHandler, SimpleLocalDateQueryParamHandler simpleLocalDateQueryParamHandler, SimpleLocalDateQueryParamOptHandler simpleLocalDateQueryParamOptHandler, SimpleLocalDateTimeQueryParamHandler simpleLocalDateTimeQueryParamHandler, SimpleLocalDateTimeQueryParamOptHandler simpleLocalDateTimeQueryParamOptHandler, SimpleZonedDateTimeQueryParamHandler simpleZonedDateTimeQueryParamHandler, SimpleZonedDateTimeQueryParamOptHandler simpleZonedDateTimeQueryParamOptHandler, SimpleScalarQueryParamHandler simpleScalarQueryParamHandler, SimpleScalarQueryParamOptHandler simpleScalarQueryParamOptHandler, SimpleEnumQueryParamHandler simpleEnumQueryParamHandler, SimpleEnumQueryParamOptHandler simpleEnumQueryParamOptHandler, MultiQueryParamHandler multiQueryParamHandler, MultiQueryParamOptHandler multiQueryParamOptHandler, RecordQueryParamHandler recordQueryParamHandler, RecordQueryParamOptHandler recordQueryParamOptHandler) {
		this.simpleBooleanQueryParamHandler = simpleBooleanQueryParamHandler;
		this.simpleBooleanQueryParamOptHandler = simpleBooleanQueryParamOptHandler;
		this.simpleShortQueryParamHandler = simpleShortQueryParamHandler;
		this.simpleShortQueryParamOptHandler = simpleShortQueryParamOptHandler;
		this.simpleIntQueryParamHandler = simpleIntQueryParamHandler;
		this.simpleIntQueryParamOptHandler = simpleIntQueryParamOptHandler;
		this.simpleLongQueryParamHandler = simpleLongQueryParamHandler;
		this.simpleLongQueryParamOptHandler = simpleLongQueryParamOptHandler;
		this.simpleFloatQueryParamHandler = simpleFloatQueryParamHandler;
		this.simpleFloatQueryParamOptHandler = simpleFloatQueryParamOptHandler;
		this.simpleDoubleQueryParamHandler = simpleDoubleQueryParamHandler;
		this.simpleDoubleQueryParamOptHandler = simpleDoubleQueryParamOptHandler;
		this.simpleStringQueryParamHandler = simpleStringQueryParamHandler;
		this.simpleStringQueryParamOptHandler = simpleStringQueryParamOptHandler;
		this.simpleLocalDateQueryParamHandler = simpleLocalDateQueryParamHandler;
		this.simpleLocalDateQueryParamOptHandler = simpleLocalDateQueryParamOptHandler;
		this.simpleLocalDateTimeQueryParamHandler = simpleLocalDateTimeQueryParamHandler;
		this.simpleLocalDateTimeQueryParamOptHandler = simpleLocalDateTimeQueryParamOptHandler;
		this.simpleZonedDateTimeQueryParamHandler = simpleZonedDateTimeQueryParamHandler;
		this.simpleZonedDateTimeQueryParamOptHandler = simpleZonedDateTimeQueryParamOptHandler;
		this.simpleScalarQueryParamHandler = simpleScalarQueryParamHandler;
		this.simpleScalarQueryParamOptHandler = simpleScalarQueryParamOptHandler;
		this.simpleEnumQueryParamHandler = simpleEnumQueryParamHandler;
		this.simpleEnumQueryParamOptHandler = simpleEnumQueryParamOptHandler;
		this.multiQueryParamHandler = multiQueryParamHandler;
		this.multiQueryParamOptHandler = multiQueryParamOptHandler;
		this.recordQueryParamHandler = recordQueryParamHandler;
		this.recordQueryParamOptHandler = recordQueryParamOptHandler;
	}

	@Override
	public boolean simpleBooleanQueryParam(BuilderFactory _factory, boolean queryValue) {
		return simpleBooleanQueryParamHandler.simpleBooleanQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleBooleanQueryParamOpt(BuilderFactory _factory, Boolean queryValue) {
		return simpleBooleanQueryParamOptHandler.simpleBooleanQueryParamOpt(_factory, queryValue);
	}

	@Override
	public short simpleShortQueryParam(BuilderFactory _factory, short queryValue) {
		return simpleShortQueryParamHandler.simpleShortQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleShortQueryParamOpt(BuilderFactory _factory, Short queryValue) {
		return simpleShortQueryParamOptHandler.simpleShortQueryParamOpt(_factory, queryValue);
	}

	@Override
	public int simpleIntQueryParam(BuilderFactory _factory, int queryValue) {
		return simpleIntQueryParamHandler.simpleIntQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleIntQueryParamOpt(BuilderFactory _factory, Integer queryValue) {
		return simpleIntQueryParamOptHandler.simpleIntQueryParamOpt(_factory, queryValue);
	}

	@Override
	public long simpleLongQueryParam(BuilderFactory _factory, long queryValue) {
		return simpleLongQueryParamHandler.simpleLongQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleLongQueryParamOpt(BuilderFactory _factory, Long queryValue) {
		return simpleLongQueryParamOptHandler.simpleLongQueryParamOpt(_factory, queryValue);
	}

	@Override
	public float simpleFloatQueryParam(BuilderFactory _factory, float queryValue) {
		return simpleFloatQueryParamHandler.simpleFloatQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleFloatQueryParamOpt(BuilderFactory _factory, Float queryValue) {
		return simpleFloatQueryParamOptHandler.simpleFloatQueryParamOpt(_factory, queryValue);
	}

	@Override
	public double simpleDoubleQueryParam(BuilderFactory _factory, double queryValue) {
		return simpleDoubleQueryParamHandler.simpleDoubleQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleDoubleQueryParamOpt(BuilderFactory _factory, Double queryValue) {
		return simpleDoubleQueryParamOptHandler.simpleDoubleQueryParamOpt(_factory, queryValue);
	}

	@Override
	public String simpleStringQueryParam(BuilderFactory _factory, String queryValue) {
		return simpleStringQueryParamHandler.simpleStringQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleStringQueryParamOpt(BuilderFactory _factory, String queryValue) {
		return simpleStringQueryParamOptHandler.simpleStringQueryParamOpt(_factory, queryValue);
	}

	@Override
	public LocalDate simpleLocalDateQueryParam(BuilderFactory _factory, LocalDate queryValue) {
		return simpleLocalDateQueryParamHandler.simpleLocalDateQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleLocalDateQueryParamOpt(BuilderFactory _factory, LocalDate queryValue) {
		return simpleLocalDateQueryParamOptHandler.simpleLocalDateQueryParamOpt(_factory, queryValue);
	}

	@Override
	public LocalDateTime simpleLocalDateTimeQueryParam(BuilderFactory _factory, LocalDateTime queryValue) {
		return simpleLocalDateTimeQueryParamHandler.simpleLocalDateTimeQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleLocalDateTimeQueryParamOpt(BuilderFactory _factory, LocalDateTime queryValue) {
		return simpleLocalDateTimeQueryParamOptHandler.simpleLocalDateTimeQueryParamOpt(_factory, queryValue);
	}

	@Override
	public ZonedDateTime simpleZonedDateTimeQueryParam(BuilderFactory _factory, ZonedDateTime queryValue) {
		return simpleZonedDateTimeQueryParamHandler.simpleZonedDateTimeQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleZonedDateTimeQueryParamOpt(BuilderFactory _factory, ZonedDateTime queryValue) {
		return simpleZonedDateTimeQueryParamOptHandler.simpleZonedDateTimeQueryParamOpt(_factory, queryValue);
	}

	@Override
	public ZoneId simpleScalarQueryParam(BuilderFactory _factory, ZoneId queryValue) {
		return simpleScalarQueryParamHandler.simpleScalarQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleScalarQueryParamOpt(BuilderFactory _factory, ZoneId queryValue) {
		return simpleScalarQueryParamOptHandler.simpleScalarQueryParamOpt(_factory, queryValue);
	}

	@Override
	public SampleEnum simpleEnumQueryParam(BuilderFactory _factory, SampleEnum queryValue) {
		return simpleEnumQueryParamHandler.simpleEnumQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult simpleEnumQueryParamOpt(BuilderFactory _factory, SampleEnum queryValue) {
		return simpleEnumQueryParamOptHandler.simpleEnumQueryParamOpt(_factory, queryValue);
	}

	@Override
	public String multiQueryParam(BuilderFactory _factory, String valueA, int valueB) {
		return multiQueryParamHandler.multiQueryParam(_factory, valueA, valueB);
	}

	@Override
	public String multiQueryParamOpt(BuilderFactory _factory, String valueA, Integer valueB) {
		return multiQueryParamOptHandler.multiQueryParamOpt(_factory, valueA, valueB);
	}

	@Override
	public SimpleRecord.Data recordQueryParam(BuilderFactory _factory, SimpleRecord.Data queryValue) {
		return recordQueryParamHandler.recordQueryParam(_factory, queryValue);
	}

	@Override
	public NilResult recordQueryParamOpt(BuilderFactory _factory, SimpleRecord.Data queryValue) {
		return recordQueryParamOptHandler.recordQueryParamOpt(_factory, queryValue);
	}

	public interface SimpleBooleanQueryParamHandler {
		public boolean simpleBooleanQueryParam(BuilderFactory _factory, boolean queryValue);
	}

	public interface SimpleBooleanQueryParamOptHandler {
		public NilResult simpleBooleanQueryParamOpt(BuilderFactory _factory, Boolean queryValue);
	}

	public interface SimpleShortQueryParamHandler {
		public short simpleShortQueryParam(BuilderFactory _factory, short queryValue);
	}

	public interface SimpleShortQueryParamOptHandler {
		public NilResult simpleShortQueryParamOpt(BuilderFactory _factory, Short queryValue);
	}

	public interface SimpleIntQueryParamHandler {
		public int simpleIntQueryParam(BuilderFactory _factory, int queryValue);
	}

	public interface SimpleIntQueryParamOptHandler {
		public NilResult simpleIntQueryParamOpt(BuilderFactory _factory, Integer queryValue);
	}

	public interface SimpleLongQueryParamHandler {
		public long simpleLongQueryParam(BuilderFactory _factory, long queryValue);
	}

	public interface SimpleLongQueryParamOptHandler {
		public NilResult simpleLongQueryParamOpt(BuilderFactory _factory, Long queryValue);
	}

	public interface SimpleFloatQueryParamHandler {
		public float simpleFloatQueryParam(BuilderFactory _factory, float queryValue);
	}

	public interface SimpleFloatQueryParamOptHandler {
		public NilResult simpleFloatQueryParamOpt(BuilderFactory _factory, Float queryValue);
	}

	public interface SimpleDoubleQueryParamHandler {
		public double simpleDoubleQueryParam(BuilderFactory _factory, double queryValue);
	}

	public interface SimpleDoubleQueryParamOptHandler {
		public NilResult simpleDoubleQueryParamOpt(BuilderFactory _factory, Double queryValue);
	}

	public interface SimpleStringQueryParamHandler {
		public String simpleStringQueryParam(BuilderFactory _factory, String queryValue);
	}

	public interface SimpleStringQueryParamOptHandler {
		public NilResult simpleStringQueryParamOpt(BuilderFactory _factory, String queryValue);
	}

	public interface SimpleLocalDateQueryParamHandler {
		public LocalDate simpleLocalDateQueryParam(BuilderFactory _factory, LocalDate queryValue);
	}

	public interface SimpleLocalDateQueryParamOptHandler {
		public NilResult simpleLocalDateQueryParamOpt(BuilderFactory _factory, LocalDate queryValue);
	}

	public interface SimpleLocalDateTimeQueryParamHandler {
		public LocalDateTime simpleLocalDateTimeQueryParam(BuilderFactory _factory, LocalDateTime queryValue);
	}

	public interface SimpleLocalDateTimeQueryParamOptHandler {
		public NilResult simpleLocalDateTimeQueryParamOpt(BuilderFactory _factory, LocalDateTime queryValue);
	}

	public interface SimpleZonedDateTimeQueryParamHandler {
		public ZonedDateTime simpleZonedDateTimeQueryParam(BuilderFactory _factory, ZonedDateTime queryValue);
	}

	public interface SimpleZonedDateTimeQueryParamOptHandler {
		public NilResult simpleZonedDateTimeQueryParamOpt(BuilderFactory _factory, ZonedDateTime queryValue);
	}

	public interface SimpleScalarQueryParamHandler {
		public ZoneId simpleScalarQueryParam(BuilderFactory _factory, ZoneId queryValue);
	}

	public interface SimpleScalarQueryParamOptHandler {
		public NilResult simpleScalarQueryParamOpt(BuilderFactory _factory, ZoneId queryValue);
	}

	public interface SimpleEnumQueryParamHandler {
		public SampleEnum simpleEnumQueryParam(BuilderFactory _factory, SampleEnum queryValue);
	}

	public interface SimpleEnumQueryParamOptHandler {
		public NilResult simpleEnumQueryParamOpt(BuilderFactory _factory, SampleEnum queryValue);
	}

	public interface MultiQueryParamHandler {
		public String multiQueryParam(BuilderFactory _factory, String valueA, int valueB);
	}

	public interface MultiQueryParamOptHandler {
		public String multiQueryParamOpt(BuilderFactory _factory, String valueA, Integer valueB);
	}

	public interface RecordQueryParamHandler {
		public SimpleRecord.Data recordQueryParam(BuilderFactory _factory, SimpleRecord.Data queryValue);
	}

	public interface RecordQueryParamOptHandler {
		public NilResult recordQueryParamOpt(BuilderFactory _factory, SimpleRecord.Data queryValue);
	}

}
