/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BinaryTypesTwoBinariesAdditionRequest
 */
export interface BinaryTypesTwoBinariesAdditionRequest {
    /**
     * 
     * @type {Blob}
     * @memberof BinaryTypesTwoBinariesAdditionRequest
     */
    dataBlob: Blob;
    /**
     * 
     * @type {Blob}
     * @memberof BinaryTypesTwoBinariesAdditionRequest
     */
    dataFile: Blob;
}

/**
 * Check if a given object implements the BinaryTypesTwoBinariesAdditionRequest interface.
 */
export function instanceOfBinaryTypesTwoBinariesAdditionRequest(value: object): value is BinaryTypesTwoBinariesAdditionRequest {
    if (!('dataBlob' in value) || value['dataBlob'] === undefined) return false;
    if (!('dataFile' in value) || value['dataFile'] === undefined) return false;
    return true;
}

export function BinaryTypesTwoBinariesAdditionRequestFromJSON(json: any): BinaryTypesTwoBinariesAdditionRequest {
    return BinaryTypesTwoBinariesAdditionRequestFromJSONTyped(json, false);
}

export function BinaryTypesTwoBinariesAdditionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryTypesTwoBinariesAdditionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dataBlob': json['dataBlob'],
        'dataFile': json['dataFile'],
    };
}

export function BinaryTypesTwoBinariesAdditionRequestToJSON(json: any): BinaryTypesTwoBinariesAdditionRequest {
    return BinaryTypesTwoBinariesAdditionRequestToJSONTyped(json, false);
}

export function BinaryTypesTwoBinariesAdditionRequestToJSONTyped(value?: BinaryTypesTwoBinariesAdditionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataBlob': value['dataBlob'],
        'dataFile': value['dataFile'],
    };
}

