/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SimpleRecord } from './SimpleRecord.js';
import {
    SimpleRecordFromJSON,
    SimpleRecordFromJSONTyped,
    SimpleRecordToJSON,
    SimpleRecordToJSONTyped,
} from './SimpleRecord.js';

/**
 * 
 * @export
 * @interface BinaryTypesUploadMixedOptRequest
 */
export interface BinaryTypesUploadMixedOptRequest {
    /**
     * 
     * @type {string}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    number?: number;
    /**
     * 
     * @type {SimpleRecord}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    rec?: SimpleRecord;
    /**
     * 
     * @type {Array<string>}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    textList?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    numberList?: Array<number>;
    /**
     * 
     * @type {Array<SimpleRecord>}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    recList?: Array<SimpleRecord>;
    /**
     * 
     * @type {any}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    dataFile?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BinaryTypesUploadMixedOptRequest
     */
    dataBlob?: any | null;
}

/**
 * Check if a given object implements the BinaryTypesUploadMixedOptRequest interface.
 */
export function instanceOfBinaryTypesUploadMixedOptRequest(value: object): value is BinaryTypesUploadMixedOptRequest {
    return true;
}

export function BinaryTypesUploadMixedOptRequestFromJSON(json: any): BinaryTypesUploadMixedOptRequest {
    return BinaryTypesUploadMixedOptRequestFromJSONTyped(json, false);
}

export function BinaryTypesUploadMixedOptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryTypesUploadMixedOptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'number': json['number'] == null ? undefined : json['number'],
        'rec': json['rec'] == null ? undefined : SimpleRecordFromJSON(json['rec']),
        'textList': json['textList'] == null ? undefined : json['textList'],
        'numberList': json['numberList'] == null ? undefined : json['numberList'],
        'recList': json['recList'] == null ? undefined : ((json['recList'] as Array<any>).map(SimpleRecordFromJSON)),
        'dataFile': json['dataFile'] == null ? undefined : json['dataFile'],
        'dataBlob': json['dataBlob'] == null ? undefined : json['dataBlob'],
    };
}

export function BinaryTypesUploadMixedOptRequestToJSON(json: any): BinaryTypesUploadMixedOptRequest {
    return BinaryTypesUploadMixedOptRequestToJSONTyped(json, false);
}

export function BinaryTypesUploadMixedOptRequestToJSONTyped(value?: BinaryTypesUploadMixedOptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'number': value['number'],
        'rec': SimpleRecordToJSON(value['rec']),
        'textList': value['textList'],
        'numberList': value['numberList'],
        'recList': value['recList'] == null ? undefined : ((value['recList'] as Array<any>).map(SimpleRecordToJSON)),
        'dataFile': value['dataFile'],
        'dataBlob': value['dataBlob'],
    };
}

