/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnumRecordSubstitutionMonthListOptPatchMerge } from './EnumRecordSubstitutionMonthListOptPatchMerge.js';
import {
    instanceOfEnumRecordSubstitutionMonthListOptPatchMerge,
    EnumRecordSubstitutionMonthListOptPatchMergeFromJSON,
    EnumRecordSubstitutionMonthListOptPatchMergeFromJSONTyped,
    EnumRecordSubstitutionMonthListOptPatchMergeToJSON,
} from './EnumRecordSubstitutionMonthListOptPatchMerge.js';
import type { EnumRecordSubstitutionMonthListOptPatchReplace } from './EnumRecordSubstitutionMonthListOptPatchReplace.js';
import {
    instanceOfEnumRecordSubstitutionMonthListOptPatchReplace,
    EnumRecordSubstitutionMonthListOptPatchReplaceFromJSON,
    EnumRecordSubstitutionMonthListOptPatchReplaceFromJSONTyped,
    EnumRecordSubstitutionMonthListOptPatchReplaceToJSON,
} from './EnumRecordSubstitutionMonthListOptPatchReplace.js';

/**
 * @type EnumRecordSubstitutionPatchMonthListOpt
 * 
 * @export
 */
export type EnumRecordSubstitutionPatchMonthListOpt = { type: 'merge' } & EnumRecordSubstitutionMonthListOptPatchMerge | { type: 'replace' } & EnumRecordSubstitutionMonthListOptPatchReplace;

export function EnumRecordSubstitutionPatchMonthListOptFromJSON(json: any): EnumRecordSubstitutionPatchMonthListOpt {
    return EnumRecordSubstitutionPatchMonthListOptFromJSONTyped(json, false);
}

export function EnumRecordSubstitutionPatchMonthListOptFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumRecordSubstitutionPatchMonthListOpt {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, EnumRecordSubstitutionMonthListOptPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, EnumRecordSubstitutionMonthListOptPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function EnumRecordSubstitutionPatchMonthListOptToJSON(json: any): any {
    return EnumRecordSubstitutionPatchMonthListOptToJSONTyped(json, false);
}

export function EnumRecordSubstitutionPatchMonthListOptToJSONTyped(value?: EnumRecordSubstitutionPatchMonthListOpt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, EnumRecordSubstitutionMonthListOptPatchMergeToJSON(value), { '@type': 'merge' } as const);
        case 'replace':
            return Object.assign({}, EnumRecordSubstitutionMonthListOptPatchReplaceToJSON(value), { '@type': 'replace' } as const);
        default:
            return value;
    }
}

