/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnumRecordSubstitutionMonthListNullPatchMerge } from './EnumRecordSubstitutionMonthListNullPatchMerge.js';
import {
    instanceOfEnumRecordSubstitutionMonthListNullPatchMerge,
    EnumRecordSubstitutionMonthListNullPatchMergeFromJSON,
    EnumRecordSubstitutionMonthListNullPatchMergeFromJSONTyped,
    EnumRecordSubstitutionMonthListNullPatchMergeToJSON,
} from './EnumRecordSubstitutionMonthListNullPatchMerge.js';
import type { EnumRecordSubstitutionMonthListNullPatchReplace } from './EnumRecordSubstitutionMonthListNullPatchReplace.js';
import {
    instanceOfEnumRecordSubstitutionMonthListNullPatchReplace,
    EnumRecordSubstitutionMonthListNullPatchReplaceFromJSON,
    EnumRecordSubstitutionMonthListNullPatchReplaceFromJSONTyped,
    EnumRecordSubstitutionMonthListNullPatchReplaceToJSON,
} from './EnumRecordSubstitutionMonthListNullPatchReplace.js';

/**
 * @type EnumRecordSubstitutionPatchMonthListNull
 * 
 * @export
 */
export type EnumRecordSubstitutionPatchMonthListNull = { type: 'merge' } & EnumRecordSubstitutionMonthListNullPatchMerge | { type: 'replace' } & EnumRecordSubstitutionMonthListNullPatchReplace;

export function EnumRecordSubstitutionPatchMonthListNullFromJSON(json: any): EnumRecordSubstitutionPatchMonthListNull {
    return EnumRecordSubstitutionPatchMonthListNullFromJSONTyped(json, false);
}

export function EnumRecordSubstitutionPatchMonthListNullFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumRecordSubstitutionPatchMonthListNull {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, EnumRecordSubstitutionMonthListNullPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, EnumRecordSubstitutionMonthListNullPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function EnumRecordSubstitutionPatchMonthListNullToJSON(json: any): any {
    return EnumRecordSubstitutionPatchMonthListNullToJSONTyped(json, false);
}

export function EnumRecordSubstitutionPatchMonthListNullToJSONTyped(value?: EnumRecordSubstitutionPatchMonthListNull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, EnumRecordSubstitutionMonthListNullPatchMergeToJSON(value), { '@type': 'merge' } as const);
        case 'replace':
            return Object.assign({}, EnumRecordSubstitutionMonthListNullPatchReplaceToJSON(value), { '@type': 'replace' } as const);
        default:
            return value;
    }
}

