/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableUnionA
 */
export interface PatchableUnionA {
    /**
     * 
     * @type {string}
     * @memberof PatchableUnionA
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableUnionA
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableUnionA
     */
    shared: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableUnionA
     */
    valueA: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableUnionA
     */
    type?: string;
}

/**
 * Check if a given object implements the PatchableUnionA interface.
 */
export function instanceOfPatchableUnionA(value: object): value is PatchableUnionA {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('shared' in value) || value['shared'] === undefined) return false;
    if (!('valueA' in value) || value['valueA'] === undefined) return false;
    return true;
}

export function PatchableUnionAFromJSON(json: any): PatchableUnionA {
    return PatchableUnionAFromJSONTyped(json, false);
}

export function PatchableUnionAFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableUnionA {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'version': json['version'],
        'shared': json['shared'],
        'valueA': json['valueA'],
        'type': json['@type'] == null ? undefined : json['@type'],
    };
}

export function PatchableUnionAToJSON(json: any): PatchableUnionA {
    return PatchableUnionAToJSONTyped(json, false);
}

export function PatchableUnionAToJSONTyped(value?: PatchableUnionA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'version': value['version'],
        'shared': value['shared'],
        'valueA': value['valueA'],
        '@type': value['type'],
    };
}

