/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableEnumInlineRecordListPatchMerge
 */
export interface PatchableEnumInlineRecordListPatchMerge {
    /**
     * 
     * @type {string}
     * @memberof PatchableEnumInlineRecordListPatchMerge
     */
    type: string;
    /**
     * 
     * @type {Array<PatchableEnumInlineRecordListPatchMergeAdditionsEnum>}
     * @memberof PatchableEnumInlineRecordListPatchMerge
     */
    additions: Array<PatchableEnumInlineRecordListPatchMergeAdditionsEnum>;
    /**
     * 
     * @type {Array<PatchableEnumInlineRecordListPatchMergeRemovalsEnum>}
     * @memberof PatchableEnumInlineRecordListPatchMerge
     */
    removals: Array<PatchableEnumInlineRecordListPatchMergeRemovalsEnum>;
}


/**
 * @export
 */
export const PatchableEnumInlineRecordListPatchMergeAdditionsEnum = {
    A: 'A',
    B: 'B'
} as const;
export type PatchableEnumInlineRecordListPatchMergeAdditionsEnum = typeof PatchableEnumInlineRecordListPatchMergeAdditionsEnum[keyof typeof PatchableEnumInlineRecordListPatchMergeAdditionsEnum];

/**
 * @export
 */
export const PatchableEnumInlineRecordListPatchMergeRemovalsEnum = {
    A: 'A',
    B: 'B'
} as const;
export type PatchableEnumInlineRecordListPatchMergeRemovalsEnum = typeof PatchableEnumInlineRecordListPatchMergeRemovalsEnum[keyof typeof PatchableEnumInlineRecordListPatchMergeRemovalsEnum];


/**
 * Check if a given object implements the PatchableEnumInlineRecordListPatchMerge interface.
 */
export function instanceOfPatchableEnumInlineRecordListPatchMerge(value: object): value is PatchableEnumInlineRecordListPatchMerge {
    if ((!('type' in value) && !('@type' in value)) || (value['type'] === undefined && value['@type'] === undefined)) return false;
    if (!('additions' in value) || value['additions'] === undefined) return false;
    if (!('removals' in value) || value['removals'] === undefined) return false;
    return true;
}

export function PatchableEnumInlineRecordListPatchMergeFromJSON(json: any): PatchableEnumInlineRecordListPatchMerge {
    return PatchableEnumInlineRecordListPatchMergeFromJSONTyped(json, false);
}

export function PatchableEnumInlineRecordListPatchMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableEnumInlineRecordListPatchMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'additions': json['additions'],
        'removals': json['removals'],
    };
}

export function PatchableEnumInlineRecordListPatchMergeToJSON(json: any): PatchableEnumInlineRecordListPatchMerge {
    return PatchableEnumInlineRecordListPatchMergeToJSONTyped(json, false);
}

export function PatchableEnumInlineRecordListPatchMergeToJSONTyped(value?: PatchableEnumInlineRecordListPatchMerge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'additions': value['additions'],
        'removals': value['removals'],
    };
}

