/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PatchableRecordOfRecordsListNullPatchMerge } from './PatchableRecordOfRecordsListNullPatchMerge.js';
import {
    instanceOfPatchableRecordOfRecordsListNullPatchMerge,
    PatchableRecordOfRecordsListNullPatchMergeFromJSON,
    PatchableRecordOfRecordsListNullPatchMergeFromJSONTyped,
    PatchableRecordOfRecordsListNullPatchMergeToJSON,
} from './PatchableRecordOfRecordsListNullPatchMerge.js';
import type { PatchableRecordOfRecordsListNullPatchReplace } from './PatchableRecordOfRecordsListNullPatchReplace.js';
import {
    instanceOfPatchableRecordOfRecordsListNullPatchReplace,
    PatchableRecordOfRecordsListNullPatchReplaceFromJSON,
    PatchableRecordOfRecordsListNullPatchReplaceFromJSONTyped,
    PatchableRecordOfRecordsListNullPatchReplaceToJSON,
} from './PatchableRecordOfRecordsListNullPatchReplace.js';

/**
 * @type PatchableRecordOfRecordsPatchListNull
 * 
 * @export
 */
export type PatchableRecordOfRecordsPatchListNull = { type: 'merge' } & PatchableRecordOfRecordsListNullPatchMerge | { type: 'replace' } & PatchableRecordOfRecordsListNullPatchReplace;

export function PatchableRecordOfRecordsPatchListNullFromJSON(json: any): PatchableRecordOfRecordsPatchListNull {
    return PatchableRecordOfRecordsPatchListNullFromJSONTyped(json, false);
}

export function PatchableRecordOfRecordsPatchListNullFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordOfRecordsPatchListNull {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordOfRecordsListNullPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordOfRecordsListNullPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function PatchableRecordOfRecordsPatchListNullToJSON(json: any): any {
    return PatchableRecordOfRecordsPatchListNullToJSONTyped(json, false);
}

export function PatchableRecordOfRecordsPatchListNullToJSONTyped(value?: PatchableRecordOfRecordsPatchListNull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordOfRecordsListNullPatchMergeToJSON(value), { '@type': 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordOfRecordsListNullPatchReplaceToJSON(value), { '@type': 'replace' } as const);
        default:
            return value;
    }
}

