/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge
 */
export interface PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge
     */
    type: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge
     */
    additions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge
     */
    removals: Array<string>;
}

/**
 * Check if a given object implements the PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge interface.
 */
export function instanceOfPatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge(value: object): value is PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge {
    if ((!('type' in value) && !('@type' in value)) || (value['type'] === undefined && value['@type'] === undefined)) return false;
    if (!('additions' in value) || value['additions'] === undefined) return false;
    if (!('removals' in value) || value['removals'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeFromJSON(json: any): PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge {
    return PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeFromJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'additions': json['additions'],
        'removals': json['removals'],
    };
}

export function PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeToJSON(json: any): PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge {
    return PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeToJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueOffsetDateTimePatchMergeToJSONTyped(value?: PatchableRecordBasicListOptionalValueOffsetDateTimePatchMerge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'additions': value['additions'],
        'removals': value['removals'],
    };
}

