/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SampleEnum } from './SampleEnum.js';
import {
    SampleEnumFromJSON,
    SampleEnumFromJSONTyped,
    SampleEnumToJSON,
    SampleEnumToJSONTyped,
} from './SampleEnum.js';

/**
 * 
 * @export
 * @interface PatchableEnumRecordListOptNullPatchMerge
 */
export interface PatchableEnumRecordListOptNullPatchMerge {
    /**
     * 
     * @type {string}
     * @memberof PatchableEnumRecordListOptNullPatchMerge
     */
    type: string;
    /**
     * 
     * @type {Array<SampleEnum>}
     * @memberof PatchableEnumRecordListOptNullPatchMerge
     */
    additions: Array<SampleEnum> | null;
    /**
     * 
     * @type {Array<SampleEnum>}
     * @memberof PatchableEnumRecordListOptNullPatchMerge
     */
    removals: Array<SampleEnum> | null;
}

/**
 * Check if a given object implements the PatchableEnumRecordListOptNullPatchMerge interface.
 */
export function instanceOfPatchableEnumRecordListOptNullPatchMerge(value: object): value is PatchableEnumRecordListOptNullPatchMerge {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('additions' in value) || value['additions'] === undefined) return false;
    if (!('removals' in value) || value['removals'] === undefined) return false;
    return true;
}

export function PatchableEnumRecordListOptNullPatchMergeFromJSON(json: any): PatchableEnumRecordListOptNullPatchMerge {
    return PatchableEnumRecordListOptNullPatchMergeFromJSONTyped(json, false);
}

export function PatchableEnumRecordListOptNullPatchMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableEnumRecordListOptNullPatchMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'additions': (json['additions'] == null ? null : (json['additions'] as Array<any>).map(SampleEnumFromJSON)),
        'removals': (json['removals'] == null ? null : (json['removals'] as Array<any>).map(SampleEnumFromJSON)),
    };
}

export function PatchableEnumRecordListOptNullPatchMergeToJSON(json: any): PatchableEnumRecordListOptNullPatchMerge {
    return PatchableEnumRecordListOptNullPatchMergeToJSONTyped(json, false);
}

export function PatchableEnumRecordListOptNullPatchMergeToJSONTyped(value?: PatchableEnumRecordListOptNullPatchMerge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'additions': (value['additions'] == null ? null : (value['additions'] as Array<any>).map(SampleEnumToJSON)),
        'removals': (value['removals'] == null ? null : (value['removals'] as Array<any>).map(SampleEnumToJSON)),
    };
}

