/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SampleEnum } from './SampleEnum.js';
import {
    SampleEnumFromJSON,
    SampleEnumFromJSONTyped,
    SampleEnumToJSON,
    SampleEnumToJSONTyped,
} from './SampleEnum.js';

/**
 * 
 * @export
 * @interface PatchableEnumRecordListOptPatchReplace
 */
export interface PatchableEnumRecordListOptPatchReplace {
    /**
     * 
     * @type {string}
     * @memberof PatchableEnumRecordListOptPatchReplace
     */
    type: string;
    /**
     * 
     * @type {Array<SampleEnum>}
     * @memberof PatchableEnumRecordListOptPatchReplace
     */
    elements: Array<SampleEnum>;
}

/**
 * Check if a given object implements the PatchableEnumRecordListOptPatchReplace interface.
 */
export function instanceOfPatchableEnumRecordListOptPatchReplace(value: object): value is PatchableEnumRecordListOptPatchReplace {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PatchableEnumRecordListOptPatchReplaceFromJSON(json: any): PatchableEnumRecordListOptPatchReplace {
    return PatchableEnumRecordListOptPatchReplaceFromJSONTyped(json, false);
}

export function PatchableEnumRecordListOptPatchReplaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableEnumRecordListOptPatchReplace {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'elements': ((json['elements'] as Array<any>).map(SampleEnumFromJSON)),
    };
}

export function PatchableEnumRecordListOptPatchReplaceToJSON(json: any): PatchableEnumRecordListOptPatchReplace {
    return PatchableEnumRecordListOptPatchReplaceToJSONTyped(json, false);
}

export function PatchableEnumRecordListOptPatchReplaceToJSONTyped(value?: PatchableEnumRecordListOptPatchReplace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'elements': ((value['elements'] as Array<any>).map(SampleEnumToJSON)),
    };
}

