/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PatchableRecordWithUnionListOptPatchMerge } from './PatchableRecordWithUnionListOptPatchMerge.js';
import {
    instanceOfPatchableRecordWithUnionListOptPatchMerge,
    PatchableRecordWithUnionListOptPatchMergeFromJSON,
    PatchableRecordWithUnionListOptPatchMergeFromJSONTyped,
    PatchableRecordWithUnionListOptPatchMergeToJSON,
} from './PatchableRecordWithUnionListOptPatchMerge.js';
import type { PatchableRecordWithUnionListOptPatchReplace } from './PatchableRecordWithUnionListOptPatchReplace.js';
import {
    instanceOfPatchableRecordWithUnionListOptPatchReplace,
    PatchableRecordWithUnionListOptPatchReplaceFromJSON,
    PatchableRecordWithUnionListOptPatchReplaceFromJSONTyped,
    PatchableRecordWithUnionListOptPatchReplaceToJSON,
} from './PatchableRecordWithUnionListOptPatchReplace.js';

/**
 * @type PatchableRecordWithUnionPatchListOpt
 * 
 * @export
 */
export type PatchableRecordWithUnionPatchListOpt = { type: 'merge' } & PatchableRecordWithUnionListOptPatchMerge | { type: 'replace' } & PatchableRecordWithUnionListOptPatchReplace;

export function PatchableRecordWithUnionPatchListOptFromJSON(json: any): PatchableRecordWithUnionPatchListOpt {
    return PatchableRecordWithUnionPatchListOptFromJSONTyped(json, false);
}

export function PatchableRecordWithUnionPatchListOptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordWithUnionPatchListOpt {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordWithUnionListOptPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordWithUnionListOptPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function PatchableRecordWithUnionPatchListOptToJSON(json: any): any {
    return PatchableRecordWithUnionPatchListOptToJSONTyped(json, false);
}

export function PatchableRecordWithUnionPatchListOptToJSONTyped(value?: PatchableRecordWithUnionPatchListOpt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordWithUnionListOptPatchMergeToJSON(value), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordWithUnionListOptPatchReplaceToJSON(value), { type: 'replace' } as const);
        default:
            return value;
    }
}

