/* tslint:disable */
/* eslint-disable */
/**
 * RSD Test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicListOptional
 */
export interface PatchableRecordBasicListOptional {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicListOptional
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicListOptional
     */
    version: string;
    /**
     * 
     * @type {Array<boolean>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueBoolean?: Array<boolean>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueShort?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueInt?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueLong?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueFloat?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueDouble?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueString?: Array<string>;
    /**
     * 
     * @type {Array<Date>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueLocalDate?: Array<Date>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueLocalDateTime?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchableRecordBasicListOptional
     */
    valueZonedDateTime?: Array<string>;
}

/**
 * Check if a given object implements the PatchableRecordBasicListOptional interface.
 */
export function instanceOfPatchableRecordBasicListOptional(value: object): value is PatchableRecordBasicListOptional {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicListOptionalFromJSON(json: any): PatchableRecordBasicListOptional {
    return PatchableRecordBasicListOptionalFromJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicListOptional {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'version': json['version'],
        'valueBoolean': json['valueBoolean'] == null ? undefined : json['valueBoolean'],
        'valueShort': json['valueShort'] == null ? undefined : json['valueShort'],
        'valueInt': json['valueInt'] == null ? undefined : json['valueInt'],
        'valueLong': json['valueLong'] == null ? undefined : json['valueLong'],
        'valueFloat': json['valueFloat'] == null ? undefined : json['valueFloat'],
        'valueDouble': json['valueDouble'] == null ? undefined : json['valueDouble'],
        'valueString': json['valueString'] == null ? undefined : json['valueString'],
        'valueLocalDate': json['valueLocalDate'] == null ? undefined : json['valueLocalDate'],
        'valueLocalDateTime': json['valueLocalDateTime'] == null ? undefined : json['valueLocalDateTime'],
        'valueZonedDateTime': json['valueZonedDateTime'] == null ? undefined : json['valueZonedDateTime'],
    };
}

export function PatchableRecordBasicListOptionalToJSON(json: any): PatchableRecordBasicListOptional {
    return PatchableRecordBasicListOptionalToJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalToJSONTyped(value?: PatchableRecordBasicListOptional | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'version': value['version'],
        'valueBoolean': value['valueBoolean'],
        'valueShort': value['valueShort'],
        'valueInt': value['valueInt'],
        'valueLong': value['valueLong'],
        'valueFloat': value['valueFloat'],
        'valueDouble': value['valueDouble'],
        'valueString': value['valueString'],
        'valueLocalDate': value['valueLocalDate'],
        'valueLocalDateTime': value['valueLocalDateTime'],
        'valueZonedDateTime': value['valueZonedDateTime'],
    };
}

