/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicListOptionalValueShortPatchMerge
 */
export interface PatchableRecordBasicListOptionalValueShortPatchMerge {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicListOptionalValueShortPatchMerge
     */
    type: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptionalValueShortPatchMerge
     */
    additions: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchableRecordBasicListOptionalValueShortPatchMerge
     */
    removals: Array<number>;
}

/**
 * Check if a given object implements the PatchableRecordBasicListOptionalValueShortPatchMerge interface.
 */
export function instanceOfPatchableRecordBasicListOptionalValueShortPatchMerge(value: object): value is PatchableRecordBasicListOptionalValueShortPatchMerge {
    if ((!('type' in value) && !('@type' in value)) || (value['type'] === undefined && value['@type'] === undefined)) return false;
    if (!('additions' in value) || value['additions'] === undefined) return false;
    if (!('removals' in value) || value['removals'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicListOptionalValueShortPatchMergeFromJSON(json: any): PatchableRecordBasicListOptionalValueShortPatchMerge {
    return PatchableRecordBasicListOptionalValueShortPatchMergeFromJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueShortPatchMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicListOptionalValueShortPatchMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'additions': json['additions'],
        'removals': json['removals'],
    };
}

export function PatchableRecordBasicListOptionalValueShortPatchMergeToJSON(json: any): PatchableRecordBasicListOptionalValueShortPatchMerge {
    return PatchableRecordBasicListOptionalValueShortPatchMergeToJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueShortPatchMergeToJSONTyped(value?: PatchableRecordBasicListOptionalValueShortPatchMerge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'additions': value['additions'],
        'removals': value['removals'],
    };
}

