/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordOfRecordsValueOptNullPatchMerge
 */
export interface PatchableRecordOfRecordsValueOptNullPatchMerge {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    version: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueBoolean?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueShort?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueInt?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueLong?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueFloat?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueDouble?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueString?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueLocalDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueLocalDateTime?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    valueZonedDateTime?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordOfRecordsValueOptNullPatchMerge
     */
    type: string;
}

/**
 * Check if a given object implements the PatchableRecordOfRecordsValueOptNullPatchMerge interface.
 */
export function instanceOfPatchableRecordOfRecordsValueOptNullPatchMerge(value: object): value is PatchableRecordOfRecordsValueOptNullPatchMerge {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('type' in value) && !('@type' in value)) || (value['type'] === undefined && value['@type'] === undefined)) return false;
    return true;
}

export function PatchableRecordOfRecordsValueOptNullPatchMergeFromJSON(json: any): PatchableRecordOfRecordsValueOptNullPatchMerge {
    return PatchableRecordOfRecordsValueOptNullPatchMergeFromJSONTyped(json, false);
}

export function PatchableRecordOfRecordsValueOptNullPatchMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordOfRecordsValueOptNullPatchMerge {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'version': json['version'],
        'valueBoolean': json['valueBoolean'] == null ? undefined : json['valueBoolean'],
        'valueShort': json['valueShort'] == null ? undefined : json['valueShort'],
        'valueInt': json['valueInt'] == null ? undefined : json['valueInt'],
        'valueLong': json['valueLong'] == null ? undefined : json['valueLong'],
        'valueFloat': json['valueFloat'] == null ? undefined : json['valueFloat'],
        'valueDouble': json['valueDouble'] == null ? undefined : json['valueDouble'],
        'valueString': json['valueString'] == null ? undefined : json['valueString'],
        'valueLocalDate': json['valueLocalDate'] == null ? undefined : (new Date(json['valueLocalDate'])),
        'valueLocalDateTime': json['valueLocalDateTime'] == null ? undefined : json['valueLocalDateTime'],
        'valueZonedDateTime': json['valueZonedDateTime'] == null ? undefined : json['valueZonedDateTime'],
        'type': json['@type'],
    };
}

export function PatchableRecordOfRecordsValueOptNullPatchMergeToJSON(json: any): PatchableRecordOfRecordsValueOptNullPatchMerge {
    return PatchableRecordOfRecordsValueOptNullPatchMergeToJSONTyped(json, false);
}

export function PatchableRecordOfRecordsValueOptNullPatchMergeToJSONTyped(value?: PatchableRecordOfRecordsValueOptNullPatchMerge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'version': value['version'],
        'valueBoolean': value['valueBoolean'],
        'valueShort': value['valueShort'],
        'valueInt': value['valueInt'],
        'valueLong': value['valueLong'],
        'valueFloat': value['valueFloat'],
        'valueDouble': value['valueDouble'],
        'valueString': value['valueString'],
        'valueLocalDate': value['valueLocalDate'] == null ? value['valueLocalDate'] : value['valueLocalDate'].toISOString().substring(0,10),
        'valueLocalDateTime': value['valueLocalDateTime'],
        'valueZonedDateTime': value['valueZonedDateTime'],
        '@type': value['type'],
    };
}

