/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PatchableScalarRecordListOptPatchMerge } from './PatchableScalarRecordListOptPatchMerge.js';
import {
    instanceOfPatchableScalarRecordListOptPatchMerge,
    PatchableScalarRecordListOptPatchMergeFromJSON,
    PatchableScalarRecordListOptPatchMergeFromJSONTyped,
    PatchableScalarRecordListOptPatchMergeToJSON,
} from './PatchableScalarRecordListOptPatchMerge.js';
import type { PatchableScalarRecordListOptPatchReplace } from './PatchableScalarRecordListOptPatchReplace.js';
import {
    instanceOfPatchableScalarRecordListOptPatchReplace,
    PatchableScalarRecordListOptPatchReplaceFromJSON,
    PatchableScalarRecordListOptPatchReplaceFromJSONTyped,
    PatchableScalarRecordListOptPatchReplaceToJSON,
} from './PatchableScalarRecordListOptPatchReplace.js';

/**
 * @type PatchableScalarRecordPatchListOpt
 * 
 * @export
 */
export type PatchableScalarRecordPatchListOpt = { type: 'merge' } & PatchableScalarRecordListOptPatchMerge | { type: 'replace' } & PatchableScalarRecordListOptPatchReplace;

export function PatchableScalarRecordPatchListOptFromJSON(json: any): PatchableScalarRecordPatchListOpt {
    return PatchableScalarRecordPatchListOptFromJSONTyped(json, false);
}

export function PatchableScalarRecordPatchListOptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableScalarRecordPatchListOpt {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, PatchableScalarRecordListOptPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableScalarRecordListOptPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function PatchableScalarRecordPatchListOptToJSON(json: any): any {
    return PatchableScalarRecordPatchListOptToJSONTyped(json, false);
}

export function PatchableScalarRecordPatchListOptToJSONTyped(value?: PatchableScalarRecordPatchListOpt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, PatchableScalarRecordListOptPatchMergeToJSON(value), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableScalarRecordListOptPatchReplaceToJSON(value), { type: 'replace' } as const);
        default:
            return value;
    }
}

