/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PatchableRecordBasicListValueIntPatchMerge } from './PatchableRecordBasicListValueIntPatchMerge.js';
import {
    instanceOfPatchableRecordBasicListValueIntPatchMerge,
    PatchableRecordBasicListValueIntPatchMergeFromJSON,
    PatchableRecordBasicListValueIntPatchMergeFromJSONTyped,
    PatchableRecordBasicListValueIntPatchMergeToJSON,
} from './PatchableRecordBasicListValueIntPatchMerge.js';
import type { PatchableRecordBasicListValueIntPatchReplace } from './PatchableRecordBasicListValueIntPatchReplace.js';
import {
    instanceOfPatchableRecordBasicListValueIntPatchReplace,
    PatchableRecordBasicListValueIntPatchReplaceFromJSON,
    PatchableRecordBasicListValueIntPatchReplaceFromJSONTyped,
    PatchableRecordBasicListValueIntPatchReplaceToJSON,
} from './PatchableRecordBasicListValueIntPatchReplace.js';

/**
 * @type PatchableRecordBasicListPatchValueInt
 * 
 * @export
 */
export type PatchableRecordBasicListPatchValueInt = { type: 'merge' } & PatchableRecordBasicListValueIntPatchMerge | { type: 'replace' } & PatchableRecordBasicListValueIntPatchReplace;

export function PatchableRecordBasicListPatchValueIntFromJSON(json: any): PatchableRecordBasicListPatchValueInt {
    return PatchableRecordBasicListPatchValueIntFromJSONTyped(json, false);
}

export function PatchableRecordBasicListPatchValueIntFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicListPatchValueInt {
    if (json == null) {
        return json;
    }
    switch (json['@type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordBasicListValueIntPatchMergeFromJSONTyped(json, true), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordBasicListValueIntPatchReplaceFromJSONTyped(json, true), { type: 'replace' } as const);
        default:
            return json;
    }
}

export function PatchableRecordBasicListPatchValueIntToJSON(json: any): any {
    return PatchableRecordBasicListPatchValueIntToJSONTyped(json, false);
}

export function PatchableRecordBasicListPatchValueIntToJSONTyped(value?: PatchableRecordBasicListPatchValueInt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'merge':
            return Object.assign({}, PatchableRecordBasicListValueIntPatchMergeToJSON(value), { type: 'merge' } as const);
        case 'replace':
            return Object.assign({}, PatchableRecordBasicListValueIntPatchReplaceToJSON(value), { type: 'replace' } as const);
        default:
            return value;
    }
}

