/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableEnumInlineRecordListPatchReplace
 */
export interface PatchableEnumInlineRecordListPatchReplace {
    /**
     * 
     * @type {string}
     * @memberof PatchableEnumInlineRecordListPatchReplace
     */
    type: string;
    /**
     * 
     * @type {Array<PatchableEnumInlineRecordListPatchReplaceElementsEnum>}
     * @memberof PatchableEnumInlineRecordListPatchReplace
     */
    elements: Array<PatchableEnumInlineRecordListPatchReplaceElementsEnum>;
}


/**
 * @export
 */
export const PatchableEnumInlineRecordListPatchReplaceElementsEnum = {
    A: 'A',
    B: 'B'
} as const;
export type PatchableEnumInlineRecordListPatchReplaceElementsEnum = typeof PatchableEnumInlineRecordListPatchReplaceElementsEnum[keyof typeof PatchableEnumInlineRecordListPatchReplaceElementsEnum];


/**
 * Check if a given object implements the PatchableEnumInlineRecordListPatchReplace interface.
 */
export function instanceOfPatchableEnumInlineRecordListPatchReplace(value: object): value is PatchableEnumInlineRecordListPatchReplace {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PatchableEnumInlineRecordListPatchReplaceFromJSON(json: any): PatchableEnumInlineRecordListPatchReplace {
    return PatchableEnumInlineRecordListPatchReplaceFromJSONTyped(json, false);
}

export function PatchableEnumInlineRecordListPatchReplaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableEnumInlineRecordListPatchReplace {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'elements': json['elements'],
    };
}

export function PatchableEnumInlineRecordListPatchReplaceToJSON(json: any): PatchableEnumInlineRecordListPatchReplace {
    return PatchableEnumInlineRecordListPatchReplaceToJSONTyped(json, false);
}

export function PatchableEnumInlineRecordListPatchReplaceToJSONTyped(value?: PatchableEnumInlineRecordListPatchReplace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'elements': value['elements'],
    };
}

