/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicOptionalNullPatch
 */
export interface PatchableRecordBasicOptionalNullPatch {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    version: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueBoolean?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueShort?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueInt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueLong?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueFloat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueDouble?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueString?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueLocalDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueLocalDateTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueLocalTime?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueOffsetDateTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNullPatch
     */
    valueZonedDateTime?: string | null;
}

/**
 * Check if a given object implements the PatchableRecordBasicOptionalNullPatch interface.
 */
export function instanceOfPatchableRecordBasicOptionalNullPatch(value: object): value is PatchableRecordBasicOptionalNullPatch {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicOptionalNullPatchFromJSON(json: any): PatchableRecordBasicOptionalNullPatch {
    return PatchableRecordBasicOptionalNullPatchFromJSONTyped(json, false);
}

export function PatchableRecordBasicOptionalNullPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicOptionalNullPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'version': json['version'],
        'valueBoolean': json['valueBoolean'] == null ? undefined : json['valueBoolean'],
        'valueShort': json['valueShort'] == null ? undefined : json['valueShort'],
        'valueInt': json['valueInt'] == null ? undefined : json['valueInt'],
        'valueLong': json['valueLong'] == null ? undefined : json['valueLong'],
        'valueFloat': json['valueFloat'] == null ? undefined : json['valueFloat'],
        'valueDouble': json['valueDouble'] == null ? undefined : json['valueDouble'],
        'valueString': json['valueString'] == null ? undefined : json['valueString'],
        'valueLocalDate': json['valueLocalDate'] == null ? undefined : (new Date(json['valueLocalDate'])),
        'valueLocalDateTime': json['valueLocalDateTime'] == null ? undefined : json['valueLocalDateTime'],
        'valueLocalTime': json['valueLocalTime'] == null ? undefined : json['valueLocalTime'],
        'valueOffsetDateTime': json['valueOffsetDateTime'] == null ? undefined : (new Date(json['valueOffsetDateTime'])),
        'valueZonedDateTime': json['valueZonedDateTime'] == null ? undefined : json['valueZonedDateTime'],
    };
}

export function PatchableRecordBasicOptionalNullPatchToJSON(json: any): PatchableRecordBasicOptionalNullPatch {
    return PatchableRecordBasicOptionalNullPatchToJSONTyped(json, false);
}

export function PatchableRecordBasicOptionalNullPatchToJSONTyped(value?: PatchableRecordBasicOptionalNullPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'version': value['version'],
        'valueBoolean': value['valueBoolean'],
        'valueShort': value['valueShort'],
        'valueInt': value['valueInt'],
        'valueLong': value['valueLong'],
        'valueFloat': value['valueFloat'],
        'valueDouble': value['valueDouble'],
        'valueString': value['valueString'],
        'valueLocalDate': value['valueLocalDate'] == null ? value['valueLocalDate'] : value['valueLocalDate'].toISOString().substring(0,10),
        'valueLocalDateTime': value['valueLocalDateTime'],
        'valueLocalTime': value['valueLocalTime'],
        'valueOffsetDateTime': value['valueOffsetDateTime'] == null ? value['valueOffsetDateTime'] : value['valueOffsetDateTime'].toISOString(),
        'valueZonedDateTime': value['valueZonedDateTime'],
    };
}

