/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicOptionalNull
 */
export interface PatchableRecordBasicOptionalNull {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNull
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNull
     */
    version: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueBoolean?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueShort?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueInt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueLong?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueFloat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueDouble?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueString?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueLocalDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueLocalDateTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicOptionalNull
     */
    valueZonedDateTime?: string | null;
}

/**
 * Check if a given object implements the PatchableRecordBasicOptionalNull interface.
 */
export function instanceOfPatchableRecordBasicOptionalNull(value: object): value is PatchableRecordBasicOptionalNull {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicOptionalNullFromJSON(json: any): PatchableRecordBasicOptionalNull {
    return PatchableRecordBasicOptionalNullFromJSONTyped(json, false);
}

export function PatchableRecordBasicOptionalNullFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicOptionalNull {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'version': json['version'],
        'valueBoolean': json['valueBoolean'] == null ? undefined : json['valueBoolean'],
        'valueShort': json['valueShort'] == null ? undefined : json['valueShort'],
        'valueInt': json['valueInt'] == null ? undefined : json['valueInt'],
        'valueLong': json['valueLong'] == null ? undefined : json['valueLong'],
        'valueFloat': json['valueFloat'] == null ? undefined : json['valueFloat'],
        'valueDouble': json['valueDouble'] == null ? undefined : json['valueDouble'],
        'valueString': json['valueString'] == null ? undefined : json['valueString'],
        'valueLocalDate': json['valueLocalDate'] == null ? undefined : (new Date(json['valueLocalDate'])),
        'valueLocalDateTime': json['valueLocalDateTime'] == null ? undefined : json['valueLocalDateTime'],
        'valueZonedDateTime': json['valueZonedDateTime'] == null ? undefined : json['valueZonedDateTime'],
    };
}

export function PatchableRecordBasicOptionalNullToJSON(json: any): PatchableRecordBasicOptionalNull {
    return PatchableRecordBasicOptionalNullToJSONTyped(json, false);
}

export function PatchableRecordBasicOptionalNullToJSONTyped(value?: PatchableRecordBasicOptionalNull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'version': value['version'],
        'valueBoolean': value['valueBoolean'],
        'valueShort': value['valueShort'],
        'valueInt': value['valueInt'],
        'valueLong': value['valueLong'],
        'valueFloat': value['valueFloat'],
        'valueDouble': value['valueDouble'],
        'valueString': value['valueString'],
        'valueLocalDate': value['valueLocalDate'] == null ? value['valueLocalDate'] : value['valueLocalDate'].toISOString().substring(0,10),
        'valueLocalDateTime': value['valueLocalDateTime'],
        'valueZonedDateTime': value['valueZonedDateTime'],
    };
}

