/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PatchableRecordBasicListOptionalValueLocalDatePatchReplace
 */
export interface PatchableRecordBasicListOptionalValueLocalDatePatchReplace {
    /**
     * 
     * @type {string}
     * @memberof PatchableRecordBasicListOptionalValueLocalDatePatchReplace
     */
    type: string;
    /**
     * 
     * @type {Array<Date>}
     * @memberof PatchableRecordBasicListOptionalValueLocalDatePatchReplace
     */
    elements: Array<Date>;
}

/**
 * Check if a given object implements the PatchableRecordBasicListOptionalValueLocalDatePatchReplace interface.
 */
export function instanceOfPatchableRecordBasicListOptionalValueLocalDatePatchReplace(value: object): value is PatchableRecordBasicListOptionalValueLocalDatePatchReplace {
    if ((!('type' in value) && !('@type' in value)) || (value['type'] === undefined && value['@type'] === undefined)) return false;
    if (!('elements' in value) || value['elements'] === undefined) return false;
    return true;
}

export function PatchableRecordBasicListOptionalValueLocalDatePatchReplaceFromJSON(json: any): PatchableRecordBasicListOptionalValueLocalDatePatchReplace {
    return PatchableRecordBasicListOptionalValueLocalDatePatchReplaceFromJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueLocalDatePatchReplaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchableRecordBasicListOptionalValueLocalDatePatchReplace {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['@type'],
        'elements': json['elements'],
    };
}

export function PatchableRecordBasicListOptionalValueLocalDatePatchReplaceToJSON(json: any): PatchableRecordBasicListOptionalValueLocalDatePatchReplace {
    return PatchableRecordBasicListOptionalValueLocalDatePatchReplaceToJSONTyped(json, false);
}

export function PatchableRecordBasicListOptionalValueLocalDatePatchReplaceToJSONTyped(value?: PatchableRecordBasicListOptionalValueLocalDatePatchReplace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '@type': value['type'],
        'elements': value['elements'],
    };
}

