/* tslint:disable */
/* eslint-disable */
/**
 * TBD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ScalarRecordSubstitution
 */
export interface ScalarRecordSubstitution {
    /**
     * 
     * @type {string}
     * @memberof ScalarRecordSubstitution
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof ScalarRecordSubstitution
     */
    value_Null: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScalarRecordSubstitution
     */
    value_Opt?: string;
    /**
     * 
     * @type {string}
     * @memberof ScalarRecordSubstitution
     */
    value_Opt_Null?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScalarRecordSubstitution
     */
    list: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScalarRecordSubstitution
     */
    list_Null: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScalarRecordSubstitution
     */
    list_Opt?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScalarRecordSubstitution
     */
    list_Opt_Null?: Array<string> | null;
}

/**
 * Check if a given object implements the ScalarRecordSubstitution interface.
 */
export function instanceOfScalarRecordSubstitution(value: object): value is ScalarRecordSubstitution {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('value_Null' in value) || value['value_Null'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('list_Null' in value) || value['list_Null'] === undefined) return false;
    return true;
}

export function ScalarRecordSubstitutionFromJSON(json: any): ScalarRecordSubstitution {
    return ScalarRecordSubstitutionFromJSONTyped(json, false);
}

export function ScalarRecordSubstitutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScalarRecordSubstitution {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'value_Null': json['value_Null'],
        'value_Opt': json['value_Opt'] == null ? undefined : json['value_Opt'],
        'value_Opt_Null': json['value_Opt_Null'] == null ? undefined : json['value_Opt_Null'],
        'list': json['list'],
        'list_Null': json['list_Null'] == null ? null : json['list_Null'],
        'list_Opt': json['list_Opt'] == null ? undefined : json['list_Opt'],
        'list_Opt_Null': json['list_Opt_Null'] == null ? undefined : json['list_Opt_Null'],
    };
}

export function ScalarRecordSubstitutionToJSON(json: any): ScalarRecordSubstitution {
    return ScalarRecordSubstitutionToJSONTyped(json, false);
}

export function ScalarRecordSubstitutionToJSONTyped(value?: ScalarRecordSubstitution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'value_Null': value['value_Null'],
        'value_Opt': value['value_Opt'],
        'value_Opt_Null': value['value_Opt_Null'],
        'list': value['list'],
        'list_Null': value['list_Null'],
        'list_Opt': value['list_Opt'],
        'list_Opt_Null': value['list_Opt_Null'],
    };
}

