// Generated by RSD - Do not modify
import type { Result } from './_result-utils.js';
import type { NativeRSDError, StatusRSDError } from './Errors.js';
import type { SampleEnum } from './model/SampleEnum.js';

export interface PathParameterTypeServiceService {
	simpleBooleanPathParam(pathBoolean: boolean): Promise<Result<boolean, StatusRSDError | NativeRSDError>>;
	simpleShortPathParam(pathShort: number): Promise<Result<number, StatusRSDError | NativeRSDError>>;
	simpleIntPathParam(pathInt: number): Promise<Result<number, StatusRSDError | NativeRSDError>>;
	simpleLongPathParam(pathLong: number): Promise<Result<number, StatusRSDError | NativeRSDError>>;
	simpleFloatPathParam(pathFloat: number): Promise<Result<number, StatusRSDError | NativeRSDError>>;
	simpleDoublePathParam(pathDouble: number): Promise<Result<number, StatusRSDError | NativeRSDError>>;
	simpleStringPathParam(pathString: string): Promise<Result<string, StatusRSDError | NativeRSDError>>;
	simpleLocalDatePathParam(pathLocalDate: string): Promise<Result<string, StatusRSDError | NativeRSDError>>;
	simpleLocalDateTimePathParam(pathLocalDateTime: string): Promise<Result<string, StatusRSDError | NativeRSDError>>;
	simpleZonedDateTimePathParam(pathZonedDateTime: string): Promise<Result<string, StatusRSDError | NativeRSDError>>;
	simpleScalarPathParam(pathScalar: string): Promise<Result<string, StatusRSDError | NativeRSDError>>;
	simpleEnumPathParam(pathEnum: SampleEnum): Promise<Result<SampleEnum, StatusRSDError | NativeRSDError>>;
	multiPathParam(valueA: string, valueB: number): Promise<Result<string, StatusRSDError | NativeRSDError>>;
}
