// Generated by RSD - Do not modify
package dev.rsdlang.sample.client.model.impl.json;

import java.util.List;
import java.util.Optional;

import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;
import jakarta.json.JsonString;

import dev.rsdlang.sample.client.model._Base;
import dev.rsdlang.sample.client.model.PatchableScalarRecord_Substitution;
import dev.rsdlang.sample.client.MyRange;

public class PatchableScalarRecord_SubstitutionPatchImpl extends _BaseDataImpl implements PatchableScalarRecord_Substitution.Patch {
	static class ListSetChangeImpl extends _ChangeSupport.ValueElementsChange<MyRange> implements ListSetChange {
		ListSetChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class ListMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<MyRange, MyRange> implements ListMergeChange {
		ListMergeChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()), v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_NullSetChangeImpl extends _ChangeSupport.ValueElementsChange<MyRange> implements List_NullSetChange {
		List_NullSetChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_NullMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<MyRange, MyRange> implements List_NullMergeChange {
		List_NullMergeChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()), v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_OptSetChangeImpl extends _ChangeSupport.ValueElementsChange<MyRange> implements List_OptSetChange {
		List_OptSetChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_OptMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<MyRange, MyRange> implements List_OptMergeChange {
		List_OptMergeChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()), v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_Opt_NullSetChangeImpl extends _ChangeSupport.ValueElementsChange<MyRange> implements List_Opt_NullSetChange {
		List_Opt_NullSetChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	static class List_Opt_NullMergeChangeImpl extends _ChangeSupport.ListMergeAddRemoveImpl<MyRange, MyRange> implements List_Opt_NullMergeChange {
		List_Opt_NullMergeChangeImpl(JsonObject data) {
			super(data, v -> MyRange.of(((JsonString) v).getString()), v -> MyRange.of(((JsonString) v).getString()));
		}
	}

	PatchableScalarRecord_SubstitutionPatchImpl(JsonObject data) {
		super(data);
	}

	@Override
	public String key() {
		return _JsonUtils.mapString(data, "key");
	}

	@Override
	public String version() {
		return _JsonUtils.mapString(data, "version");
	}

	public Optional<MyRange> value() {
		return _JsonUtils.mapOptLiteral(data, "value", MyRange::of);
	}

	public _Base.Nillable<MyRange> value_Null() {
		return _JsonUtils.mapNilLiteral(data, "value_Null", MyRange::of );
	}

	public _Base.Nillable<MyRange> value_Opt() {
		return _JsonUtils.mapNilLiteral(data, "value_Opt", MyRange::of );
	}

	public _Base.Nillable<MyRange> value_Opt_Null() {
		return _JsonUtils.mapNilLiteral(data, "value_Opt_Null", MyRange::of );
	}

	public Optional<ListChange> list() {
		return _JsonUtils.mapOptObject(data, "list", o -> _ChangeSupport.of(o, "@type", ListSetChangeImpl::new, ListMergeChangeImpl::new));
	}

	public _Base.Nillable<List_NullChange> list_Null() {
		return _JsonUtils.mapNilObject(data, "list_Null", o -> _ChangeSupport.of(o, "@type", List_NullSetChangeImpl::new, List_NullMergeChangeImpl::new));
	}

	public _Base.Nillable<List_OptChange> list_Opt() {
		return _JsonUtils.mapNilObject(data, "list_Opt", o -> _ChangeSupport.of(o, "@type", List_OptSetChangeImpl::new, List_OptMergeChangeImpl::new));
	}

	public _Base.Nillable<List_Opt_NullChange> list_Opt_Null() {
		return _JsonUtils.mapNilObject(data, "list_Opt_Null", o -> _ChangeSupport.of(o, "@type", List_Opt_NullSetChangeImpl::new, List_Opt_NullMergeChangeImpl::new));
	}

	public static class PatchBuilderImpl implements PatchableScalarRecord_Substitution.PatchBuilder {
		private JsonObjectBuilder $builder = Json.createObjectBuilder();

		public PatchableScalarRecord_Substitution.PatchBuilder key(String key) {
			$builder.add("key", key);
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder version(String version) {
			$builder.add("version", version);
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder value(MyRange value) {
			$builder.add("value", value.toString());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder value_Null(MyRange value_Null) {
			if (value_Null == null) {
				$builder.addNull("value_Null");
				return this;
			}
			$builder.add("value_Null", value_Null.toString());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder value_Opt(MyRange value_Opt) {
			if (value_Opt == null) {
				$builder.addNull("value_Opt");
				return this;
			}
			$builder.add("value_Opt", value_Opt.toString());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder value_Opt_Null(MyRange value_Opt_Null) {
			if (value_Opt_Null == null) {
				$builder.addNull("value_Opt_Null");
				return this;
			}
			$builder.add("value_Opt_Null", value_Opt_Null.toString());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder list(ListChange list) {
			$builder.add("list", ((_BaseDataImpl) list).data);
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list(List<MyRange> additions, List<MyRange> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("list", $changeBuilder.build());
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list(List<MyRange> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("list", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder list_Null(List_NullChange list_Null) {
			$builder.add("list_Null", ((_BaseDataImpl) list_Null).data);
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Null(List<MyRange> additions, List<MyRange> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("list_Null", $changeBuilder.build());
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Null(List<MyRange> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("list_Null", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt(List_OptChange list_Opt) {
			$builder.add("list_Opt", ((_BaseDataImpl) list_Opt).data);
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt(List<MyRange> additions, List<MyRange> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("list_Opt", $changeBuilder.build());
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt(List<MyRange> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("list_Opt", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt_Null(List_Opt_NullChange list_Opt_Null) {
			$builder.add("list_Opt_Null", ((_BaseDataImpl) list_Opt_Null).data);
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt_Null(List<MyRange> additions, List<MyRange> removals) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "merge");
			$changeBuilder.add("additions", _JsonUtils.toJsonLiteralArray(additions));
			$changeBuilder.add("removals", _JsonUtils.toJsonLiteralArray(removals));
			$builder.add("list_Opt_Null", $changeBuilder.build());
			return this;
		}

		public PatchableScalarRecord_Substitution.PatchBuilder list_Opt_Null(List<MyRange> elements) {
			var $changeBuilder = Json.createObjectBuilder();
			$changeBuilder.add("@type", "replace");
			$changeBuilder.add("elements", _JsonUtils.toJsonLiteralArray(elements));
			$builder.add("list_Opt_Null", $changeBuilder.build());
			return this;
		}

		@Override
		public PatchableScalarRecord_Substitution.Patch build() {
			return new PatchableScalarRecord_SubstitutionPatchImpl($builder.build());
		}
	}

	public static PatchableScalarRecord_Substitution.Patch of(JsonObject obj) {
		return new PatchableScalarRecord_SubstitutionPatchImpl(obj);
	}

	public static PatchBuilderImpl builder() {
		return new PatchBuilderImpl();
	}
}
