// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.service;

import dev.rsdlang.sample.server.model.ZoneId;

public class SampleErrorScalarException extends RSDException.RSDStructuredDataException {
	private final ZoneId data;

	public SampleErrorScalarException(String message, ZoneId data) {
		super(Type.SampleErrorScalar, message);
		this.data = data;
	}
	public ZoneId data() {
		return this.data;
	}
}
