// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.ZoneId;

import dev.rsdlang.sample.server.service.model.SampleEnum;
import dev.rsdlang.sample.server.service.model.SimpleRecord;

public interface SampleServiceService {
	public boolean getBoolean(BuilderFactory _factory);

	public short getShort(BuilderFactory _factory);

	public int getInt(BuilderFactory _factory);

	public long getLong(BuilderFactory _factory);

	public float getFloat(BuilderFactory _factory);

	public double getDouble(BuilderFactory _factory);

	public String getString(BuilderFactory _factory);

	public LocalDate getLocalDate(BuilderFactory _factory);

	public LocalDateTime getLocalDateTime(BuilderFactory _factory);

	public ZonedDateTime getZonedDateTime(BuilderFactory _factory);

	public ZoneId getScalar(BuilderFactory _factory);

	public SampleEnum getEnum(BuilderFactory _factory);

	public void voidOperation(BuilderFactory _factory);

	public void errorOperation(BuilderFactory _factory)
			throws SampleErrorException;

	public void multiErrorOperation(BuilderFactory _factory)
			throws SampleErrorException,
			SampleError2Exception;

	public SimpleRecord.Data getSimpleRecord(BuilderFactory _factory, String key);

	public SimpleRecord.Data getSimpleRecordWithError(BuilderFactory _factory, String key)
			throws SampleErrorException;

}
