// Generated by RSD - Do not modify
package dev.rsdlang.sample.server.model.mixins;

import dev.rsdlang.sample.server.model.SimpleRecord;

public interface RecordMixinMixin {
	public SimpleRecord.Data myRecord();

}
