// Generated by RSD - Do not modify
package dev.rsdlang.sample.client.jdkhttp.impl;

import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.net.URI;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

import dev.rsdlang.sample.client.jdkhttp.JDKSpecSamplesClient;
import dev.rsdlang.sample.client.model.impl.json._JsonUtils;
import dev.rsdlang.sample.client.model.NilResult;
import dev.rsdlang.sample.client.MyRange;
import dev.rsdlang.sample.client.Result;
import dev.rsdlang.sample.client.RSDError;
import dev.rsdlang.sample.client.SampleErrorScalarSub;
import dev.rsdlang.sample.client.ScalarSubstition_ServiceService;
import dev.rsdlang.sample.client.SpecSamplesClient;

public class ScalarSubstition_ServiceServiceImpl implements ScalarSubstition_ServiceService {
	private final JDKSpecSamplesClient client;

	private final SpecSamplesClient.LifecycleHook lifecycleHook;

	public ScalarSubstition_ServiceServiceImpl(JDKSpecSamplesClient client, SpecSamplesClient.LifecycleHook lifecycleHook) {
		this.client = client;
		this.lifecycleHook = lifecycleHook;
	}

	public JDKSpecSamplesClient client() {
		return this.client;
	}

	private String baseURI() {
		return this.client.baseURI().toString();
	}

	private HttpClient httpClient() {
		return this.client.httpClient();
	}

	private String contentType() {
		return this.client.contentTypeEncoding().contentType;
	}

	public Result<MyRange, RSDError.$GenericError> get() {
		var $path = "%s/api/scalarsubstitution/get".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("get", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, MyRange::of);
				this.lifecycleHook.onSuccess("get", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("get", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation get", e);
			this.lifecycleHook.onCatch("get", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("get");
		}
	}

	public Result<List<MyRange>, RSDError.$GenericError> list() {
		var $path = "%s/api/scalarsubstitution/list".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("list", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiterals($response, MyRange::of);
				this.lifecycleHook.onSuccess("list", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("list", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation list", e);
			this.lifecycleHook.onCatch("list", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("list");
		}
	}

	public Result<MyRange, RSDError.$GenericError> post(MyRange range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/post".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteral(range, false, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("post", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, MyRange::of);
				this.lifecycleHook.onSuccess("post", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("post", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation post", e);
			this.lifecycleHook.onCatch("post", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("post");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postOpt() {
		var $path = "%s/api/scalarsubstitution/postOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(_JsonUtils.encodeEmptyValue($contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postOpt", e);
			this.lifecycleHook.onCatch("postOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postOpt(MyRange range) {
		var $path = "%s/api/scalarsubstitution/postOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(range == null ? _JsonUtils.encodeEmptyValue($contentType) : BaseUtils.ofLiteral(range, false, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postOpt", e);
			this.lifecycleHook.onCatch("postOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/postNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteral(range, true, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postNull", e);
			this.lifecycleHook.onCatch("postNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postOptNull() {
		var $path = "%s/api/scalarsubstitution/postOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(_JsonUtils.encodeEmptyValue($contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postOptNull", e);
			this.lifecycleHook.onCatch("postOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postOptNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/postOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteral(range, true, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postOptNull", e);
			this.lifecycleHook.onCatch("postOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postOptNull");
		}
	}

	public Result<List<MyRange>, RSDError.$GenericError> postList(List<MyRange> range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/postList".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteralList(range, false, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postList", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiterals($response, MyRange::of);
				this.lifecycleHook.onSuccess("postList", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postList", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postList", e);
			this.lifecycleHook.onCatch("postList", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postList");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postListOpt() {
		var $path = "%s/api/scalarsubstitution/postListOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(_JsonUtils.encodeEmptyValue($contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postListOpt", e);
			this.lifecycleHook.onCatch("postListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postListOpt(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/postListOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(range == null ? _JsonUtils.encodeEmptyValue($contentType) : BaseUtils.ofLiteralList(range, false, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postListOpt", e);
			this.lifecycleHook.onCatch("postListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postListNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/postListNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteralList(range, true, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postListNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postListNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postListNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postListNull", e);
			this.lifecycleHook.onCatch("postListNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postListNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postListOptNull() {
		var $path = "%s/api/scalarsubstitution/postListOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(_JsonUtils.encodeEmptyValue($contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postListOptNull", e);
			this.lifecycleHook.onCatch("postListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postListOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> postListOptNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/postListOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(BaseUtils.ofLiteralList(range, true, $contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("postListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("postListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("postListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation postListOptNull", e);
			this.lifecycleHook.onCatch("postListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("postListOptNull");
		}
	}

	public Result<MyRange, RSDError.$GenericError> query(MyRange range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/query".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		$queryParams.append("range", range);

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("query", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, MyRange::of);
				this.lifecycleHook.onSuccess("query", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("query", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation query", e);
			this.lifecycleHook.onCatch("query", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("query");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryOpt() {
		var $path = "%s/api/scalarsubstitution/queryOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryOpt", e);
			this.lifecycleHook.onCatch("queryOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryOpt(MyRange range) {
		var $path = "%s/api/scalarsubstitution/queryOpt".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			$queryParams.append("range", range);
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryOpt", e);
			this.lifecycleHook.onCatch("queryOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/queryNull".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			$queryParams.append("range", range);
		} else {
			$queryParams.append("range", "null");
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryNull", e);
			this.lifecycleHook.onCatch("queryNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryOptNull() {
		var $path = "%s/api/scalarsubstitution/queryOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryOptNull", e);
			this.lifecycleHook.onCatch("queryOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryOptNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/queryOptNull".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			$queryParams.append("range", range);
		} else {
			$queryParams.append("range", "null");
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryOptNull", e);
			this.lifecycleHook.onCatch("queryOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryOptNull");
		}
	}

	public Result<List<MyRange>, RSDError.$GenericError> queryList(List<MyRange> range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/queryList".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		range.stream().forEach($q -> {
			$queryParams.append("range", $q);
		});

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryList", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiterals($response, MyRange::of);
				this.lifecycleHook.onSuccess("queryList", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryList", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryList", e);
			this.lifecycleHook.onCatch("queryList", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryList");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryListOpt() {
		var $path = "%s/api/scalarsubstitution/queryListOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryListOpt", e);
			this.lifecycleHook.onCatch("queryListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryListOpt(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/queryListOpt".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			range.stream().forEach($q -> {
				$queryParams.append("range", $q);
			});
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryListOpt", e);
			this.lifecycleHook.onCatch("queryListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryListNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/queryListNull".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			range.stream().forEach($q -> {
				$queryParams.append("range", $q);
			});
		} else {
			$queryParams.append("range", "null");
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryListNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryListNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryListNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryListNull", e);
			this.lifecycleHook.onCatch("queryListNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryListNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryListOptNull() {
		var $path = "%s/api/scalarsubstitution/queryListOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryListOptNull", e);
			this.lifecycleHook.onCatch("queryListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryListOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> queryListOptNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/queryListOptNull".formatted(
				this.baseURI());

		var $queryParams = new BaseUtils.URLSearchParams();
		if (range != null) {
			range.stream().forEach($q -> {
				$queryParams.append("range", $q);
			});
		} else {
			$queryParams.append("range", "null");
		}

		var $uri = URI.create($path + $queryParams.toQueryString());
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("queryListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("queryListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("queryListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation queryListOptNull", e);
			this.lifecycleHook.onCatch("queryListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("queryListOptNull");
		}
	}

	public Result<MyRange, RSDError.$GenericError> header(MyRange range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/header".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		$headerParams.put("range", BaseUtils.encodeAsciiString(Objects.toString(range)));
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("header", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, MyRange::of);
				this.lifecycleHook.onSuccess("header", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("header", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation header", e);
			this.lifecycleHook.onCatch("header", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("header");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerOpt() {
		var $path = "%s/api/scalarsubstitution/headerOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("headerOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerOpt", e);
			this.lifecycleHook.onCatch("headerOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerOpt(MyRange range) {
		var $path = "%s/api/scalarsubstitution/headerOpt".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		$headerParams.put("range", BaseUtils.encodeAsciiString(Objects.toString(range)));
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerOpt", e);
			this.lifecycleHook.onCatch("headerOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/headerNull".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		$headerParams.put("range", BaseUtils.encodeAsciiString(Objects.toString(range)));
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerNull", e);
			this.lifecycleHook.onCatch("headerNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerOptNull() {
		var $path = "%s/api/scalarsubstitution/headerOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("headerOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerOptNull", e);
			this.lifecycleHook.onCatch("headerOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerOptNull(MyRange range) {
		var $path = "%s/api/scalarsubstitution/headerOptNull".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		$headerParams.put("range", BaseUtils.encodeAsciiString(Objects.toString(range)));
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerOptNull", e);
			this.lifecycleHook.onCatch("headerOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerOptNull");
		}
	}

	public Result<List<MyRange>, RSDError.$GenericError> headerList(List<MyRange> range) {
		Objects.requireNonNull(range, "range must not be null");

		var $path = "%s/api/scalarsubstitution/headerList".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		$headerParams.put("range", String.join(",", range.stream().map($v -> BaseUtils.encodeAsciiString(Objects.toString($v))).toList()));
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerList", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiterals($response, MyRange::of);
				this.lifecycleHook.onSuccess("headerList", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerList", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerList", e);
			this.lifecycleHook.onCatch("headerList", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerList");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerListOpt() {
		var $path = "%s/api/scalarsubstitution/headerListOpt".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("headerListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerListOpt", e);
			this.lifecycleHook.onCatch("headerListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerListOpt(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/headerListOpt".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		if (range != null) {
			$headerParams.put("range", String.join(",", range.stream().map($v -> BaseUtils.encodeAsciiString(Objects.toString($v))).toList()));
		}
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerListOpt", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerListOpt", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerListOpt", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerListOpt", e);
			this.lifecycleHook.onCatch("headerListOpt", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerListOpt");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerListNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/headerListNull".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		if (range != null) {
			$headerParams.put("range", String.join(",", range.stream().map($v -> BaseUtils.encodeAsciiString(Objects.toString($v))).toList()));
		} else {
			$headerParams.put("range", "null");
		}
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerListNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerListNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerListNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerListNull", e);
			this.lifecycleHook.onCatch("headerListNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerListNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerListOptNull() {
		var $path = "%s/api/scalarsubstitution/headerListOptNull".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			this.lifecycleHook.preRequest("headerListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerListOptNull", e);
			this.lifecycleHook.onCatch("headerListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerListOptNull");
		}
	}

	public Result<NilResult, RSDError.$GenericError> headerListOptNull(List<MyRange> range) {
		var $path = "%s/api/scalarsubstitution/headerListOptNull".formatted(
				this.baseURI());

		var $headerParams = new HashMap<String, String>();
		if (range != null) {
			$headerParams.put("range", String.join(",", range.stream().map($v -> BaseUtils.encodeAsciiString(Objects.toString($v))).toList()));
		} else {
			$headerParams.put("range", "null");
		}
		var $headers = BaseUtils.toHeaders($headerParams);

		var $uri = URI.create($path);
		try {
			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.GET();
			if($headers.length > 0) {
				$requestBuilder = $requestBuilder.headers($headers);
			}
			this.lifecycleHook.preRequest("headerListOptNull", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				var $rv = JDKHttpClientResponseUtils.mapLiteral($response, NilResult::valueOf);
				this.lifecycleHook.onSuccess("headerListOptNull", $rv, this.client.createResponseAdaptable($response));
				return Result.ok($rv);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("headerListOptNull", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation headerListOptNull", e);
			this.lifecycleHook.onCatch("headerListOptNull", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("headerListOptNull");
		}
	}

	public Result<Void, RSDError.E9> fail() {
		var $path = "%s/api/scalarsubstitution/fail".formatted(
				this.baseURI());

		var $uri = URI.create($path);
		try {
			var $contentType = this.contentType();
			var $body = BodyPublishers.ofByteArray(_JsonUtils.encodeEmptyValue($contentType));

			var $requestBuilder = HttpRequest.newBuilder()
					.uri($uri)
					.header("Accept", this.contentType())
					.header("Content-Type", $contentType)
					.POST($body);
			this.lifecycleHook.preRequest("fail", client.createRequestBuilderAdaptable($requestBuilder));
			var $request = $requestBuilder.build();

			var $response = this.httpClient().send($request, BodyHandlers.ofInputStream());
			if ($response.statusCode() == 200) {
				this.lifecycleHook.onSuccess("fail", null, this.client.createResponseAdaptable($response));
				return Result.ok(null);
			} else if ($response.statusCode() == 400) {
				var $errorData = JDKHttpClientResponseUtils.mapLiteral($response, MyRange::of);
				var $message = $response.headers().firstValue("X-RSD-Error-Message").orElse("Invocation of fail failed");
				var $error = new SampleErrorScalarSub($message, $errorData);
				this.lifecycleHook.onError("fail", $error, this.client.createResponseAdaptable($response));
				return Result.err($error);
			}
			var $error = new RSDError.$GenericError(RSDError.Type._UnknownResponse, String.format("Unsupported Http-Status '%s':\n%s", $response.statusCode(), JDKHttpClientResponseUtils.toString($response)), null);
			this.lifecycleHook.onError("fail", $error, this.client.createResponseAdaptable($response));
			return Result.err($error);
		} catch (Exception e) {
			if (e instanceof InterruptedException) {
				Thread.currentThread().interrupt();
			}

			var $error = new RSDError.$GenericError(RSDError.Type._Native, "Unexpected error while executing operation fail", e);
			this.lifecycleHook.onCatch("fail", $error);
			return Result.err($error);
		} finally {
			this.lifecycleHook.onFinally("fail");
		}
	}
}
