// Generated by RSD - Do not modify
export type NilResult = 'UNDEFINED' | 'NULL' | 'DEFINED';

export function isNilResult(value: unknown) {
	return value === 'UNDEFINED' || value === 'NULL' || value === 'DEFINED';
}
