// Generated by RSD - Do not modify
import { isRSDString, type RSDString, RSDStringFromJSON, RSDStringToJSON } from './_Builtins.js';
import { checkOptProp, checkProp, createIsStringTypeGuard, isRecord, isString, isUndefined, propMappedValue } from '../_type-utils.js';

export type PatchableUnionA = {
	'@type': 'union-a';
	readonly key: RSDString;
	readonly version: RSDString;
	readonly shared: RSDString;
	readonly valueA: RSDString;
};

export function isPatchableUnionA(value: unknown): value is PatchableUnionA {
	return isRecord(value) &&
		checkProp(value, '@type', createIsStringTypeGuard('union-a')) &&
		checkProp(value, 'key', isRSDString) &&
		checkProp(value, 'version', isRSDString) &&
		checkProp(value, 'shared', isRSDString) &&
		checkProp(value, 'valueA', isRSDString);
}

export function PatchableUnionAFromJSON($value: Record<string, unknown>): PatchableUnionA {
	const key = propMappedValue('key', $value, isString, RSDStringFromJSON);
	const version = propMappedValue('version', $value, isString, RSDStringFromJSON);
	const shared = propMappedValue('shared', $value, isString, RSDStringFromJSON);
	const valueA = propMappedValue('valueA', $value, isString, RSDStringFromJSON);
	return {
		'@type': 'union-a',
		key,
		version,
		shared,
		valueA,
	};
}

export function PatchableUnionAToJSON($value: PatchableUnionA): Record<string, unknown> {
	const key = RSDStringToJSON($value.key);
	const version = RSDStringToJSON($value.version);
	const shared = RSDStringToJSON($value.shared);
	const valueA = RSDStringToJSON($value.valueA);

	return {
		'@type': 'union-a',
		key,
		version,
		shared,
		valueA,
	};
}

export type PatchableUnionAPatch = {
	'@type': 'patch:union-a';
	readonly key: RSDString;
	readonly version: RSDString;
	readonly shared?: RSDString;
	readonly valueA?: RSDString;
};

export function isPatchableUnionAPatch(value: unknown): value is PatchableUnionAPatch {
	return isRecord(value) &&
		checkProp(value, '@type', createIsStringTypeGuard('patch:union-a')) &&
		checkProp(value, 'key', isRSDString) &&
		checkProp(value, 'version', isRSDString) &&
		checkOptProp(value, 'shared', isRSDString) &&
		checkOptProp(value, 'valueA', isRSDString);
}

export function PatchableUnionAPatchFromJSON($value: Record<string, unknown>): PatchableUnionAPatch {
	const key = propMappedValue('key', $value, isString, RSDStringFromJSON);
	const version = propMappedValue('version', $value, isString, RSDStringFromJSON);
	const shared = propMappedValue('shared', $value, isString, RSDStringFromJSON, 'optional');
	const valueA = propMappedValue('valueA', $value, isString, RSDStringFromJSON, 'optional');
	return {
		'@type': 'patch:union-a',
		key,
		version,
		shared,
		valueA,
	};
}

export function PatchableUnionAPatchToJSON($value: PatchableUnionAPatch): Record<string, unknown> {
	const key = RSDStringToJSON($value.key);
	const version = RSDStringToJSON($value.version);
	const shared = isUndefined($value.shared) ? undefined : RSDStringToJSON($value.shared);
	const valueA = isUndefined($value.valueA) ? undefined : RSDStringToJSON($value.valueA);

	return {
		'@type': 'patch:union-a',
		key,
		version,
		shared,
		valueA,
	};
}

