// Generated by RSD - Do not modify
import { isRSDString, type RSDString, RSDStringFromJSON, RSDStringToJSON } from './Builtins.js';
import { isZoneId, type ZoneId, ZoneIdFromJSON } from './Scalars.js';
import { checkOptProp, checkProp, createReplaceAddRemoveGuard, createTypedArrayGuard, isListReplace, isNull, isRecord, isString, type ListMergeAddRemove, ListMergeAddRemoveFromJSON, type ListReplace, ListReplaceFromJSON, propMappedListValue, propMappedValue } from '../_type-utils.js';

export type PatchableScalarRecord = {
	readonly key: RSDString;
	readonly version: RSDString;
	readonly value: ZoneId;
	readonly value_Null: ZoneId | null;
	readonly value_Opt?: ZoneId;
	readonly value_Opt_Null?: ZoneId | null;
	readonly list: ZoneId[];
	readonly list_Null: ZoneId[] | null;
	readonly list_Opt?: ZoneId[];
	readonly list_Opt_Null?: ZoneId[] | null;
};

export function isPatchableScalarRecord(value: unknown): value is PatchableScalarRecord {
	return isRecord(value) &&
		checkProp(value, 'key', isRSDString) &&
		checkProp(value, 'version', isRSDString) &&
		checkProp(value, 'value', isZoneId) &&
		(checkProp(value, 'value_Null', isNull) || checkProp(value, 'value_Null', isZoneId)) &&
		checkOptProp(value, 'value_Opt', isZoneId) &&
		(checkOptProp(value, 'value_Opt_Null', isNull) || checkOptProp(value, 'value_Opt_Null', isZoneId)) &&
		checkProp(value, 'list', createTypedArrayGuard(isZoneId)) &&
		(checkProp(value, 'list_Null', isNull) || checkProp(value, 'list_Null', createTypedArrayGuard(isZoneId))) &&
		checkOptProp(value, 'list_Opt', createTypedArrayGuard(isZoneId)) &&
		(checkOptProp(value, 'list_Opt_Null', isNull) || checkOptProp(value, 'list_Opt_Null', createTypedArrayGuard(isZoneId)));
}

export function PatchableScalarRecordFromJSON($value: Record<string, unknown>): PatchableScalarRecord {
	const key = propMappedValue('key', $value, isString, RSDStringFromJSON);
	const version = propMappedValue('version', $value, isString, RSDStringFromJSON);
	const value = propMappedValue('value', $value, isString, ZoneIdFromJSON);
	const value_Null = propMappedValue('value_Null', $value, isString, ZoneIdFromJSON, 'null');
	const value_Opt = propMappedValue('value_Opt', $value, isString, ZoneIdFromJSON, 'optional');
	const value_Opt_Null = propMappedValue('value_Opt_Null', $value, isString, ZoneIdFromJSON, 'optional_null');
	const list = propMappedListValue('list', $value, isString, ZoneIdFromJSON);
	const list_Null = propMappedListValue('list_Null', $value, isString, ZoneIdFromJSON, 'null');
	const list_Opt = propMappedListValue('list_Opt', $value, isString, ZoneIdFromJSON, 'optional');
	const list_Opt_Null = propMappedListValue('list_Opt_Null', $value, isString, ZoneIdFromJSON, 'optional_null');
	return {
		key,
		version,
		value,
		value_Null,
		value_Opt,
		value_Opt_Null,
		list,
		list_Null,
		list_Opt,
		list_Opt_Null,
	};
}

export function PatchableScalarRecordToJSON($value: PatchableScalarRecord): Record<string, unknown> {
	const key = RSDStringToJSON($value.key);
	const version = RSDStringToJSON($value.version);
	const value = $value.value;
	const value_Null = $value.value_Null;
	const value_Opt = $value.value_Opt;
	const value_Opt_Null = $value.value_Opt_Null;
	const list = $value.list;
	const list_Null = $value.list_Null;
	const list_Opt = $value.list_Opt;
	const list_Opt_Null = $value.list_Opt_Null;

	return {
		key,
		version,
		value,
		value_Null,
		value_Opt,
		value_Opt_Null,
		list,
		list_Null,
		list_Opt,
		list_Opt_Null,
	};
}

type $ListReplace = ListReplace<ZoneId>;
type $ListMerge = ListMergeAddRemove<ZoneId, ZoneId>;
type $ListPatch = $ListReplace | $ListMerge;

type $List_NullReplace = ListReplace<ZoneId>;
type $List_NullMerge = ListMergeAddRemove<ZoneId, ZoneId>;
type $List_NullPatch = $List_NullReplace | $List_NullMerge;

type $List_OptReplace = ListReplace<ZoneId>;
type $List_OptMerge = ListMergeAddRemove<ZoneId, ZoneId>;
type $List_OptPatch = $List_OptReplace | $List_OptMerge;

type $List_Opt_NullReplace = ListReplace<ZoneId>;
type $List_Opt_NullMerge = ListMergeAddRemove<ZoneId, ZoneId>;
type $List_Opt_NullPatch = $List_Opt_NullReplace | $List_Opt_NullMerge;

export type PatchableScalarRecordPatch = {
	readonly key: RSDString;
	readonly version: RSDString;
	readonly value?: ZoneId;
	readonly value_Null?: ZoneId | null;
	readonly value_Opt?: ZoneId | null;
	readonly value_Opt_Null?: ZoneId | null;
	readonly list?: $ListPatch;
	readonly list_Null?: $List_NullPatch | null;
	readonly list_Opt?: $List_OptPatch | null;
	readonly list_Opt_Null?: $List_Opt_NullPatch | null;
};

export function isPatchableScalarRecordPatch(value: unknown): value is PatchableScalarRecordPatch {
	return isRecord(value) &&
		checkProp(value, 'key', isRSDString) &&
		checkProp(value, 'version', isRSDString) &&
		checkOptProp(value, 'value', isZoneId) &&
		(checkOptProp(value, 'value_Null', isNull) || checkOptProp(value, 'value_Null', isZoneId)) &&
		(checkOptProp(value, 'value_Opt', isNull) || checkOptProp(value, 'value_Opt', isZoneId)) &&
		(checkOptProp(value, 'value_Opt_Null', isNull) || checkOptProp(value, 'value_Opt_Null', isZoneId)) &&
		checkOptProp(value, 'list', createReplaceAddRemoveGuard(isZoneId)) &&
		(checkOptProp(value, 'list_Null', isNull) || checkOptProp(value, 'list_Null', createReplaceAddRemoveGuard(isZoneId))) &&
		(checkOptProp(value, 'list_Opt', isNull) || checkOptProp(value, 'list_Opt', createReplaceAddRemoveGuard(isZoneId))) &&
		(checkOptProp(value, 'list_Opt_Null', isNull) || checkOptProp(value, 'list_Opt_Null', createReplaceAddRemoveGuard(isZoneId)));
}

export function PatchableScalarRecordPatchFromJSON($value: Record<string, unknown>): PatchableScalarRecordPatch {
	const key = propMappedValue('key', $value, isString, RSDStringFromJSON);
	const version = propMappedValue('version', $value, isString, RSDStringFromJSON);
	const value = propMappedValue('value', $value, isString, ZoneIdFromJSON, 'optional');
	const value_Null = propMappedValue('value_Null', $value, isString, ZoneIdFromJSON, 'optional_null');
	const value_Opt = propMappedValue('value_Opt', $value, isString, ZoneIdFromJSON, 'optional_null');
	const value_Opt_Null = propMappedValue('value_Opt_Null', $value, isString, ZoneIdFromJSON, 'optional_null');
	const list = propMappedValue('list', $value, isRecord, v => isListReplace(v, isString) ? ListReplaceFromJSON(v, isString, ZoneIdFromJSON) : ListMergeAddRemoveFromJSON(v, isString, ZoneIdFromJSON, isString, ZoneIdFromJSON), 'optional');
	const list_Null = propMappedValue('list_Null', $value, isRecord, v => isListReplace(v, isString) ? ListReplaceFromJSON(v, isString, ZoneIdFromJSON) : ListMergeAddRemoveFromJSON(v, isString, ZoneIdFromJSON, isString, ZoneIdFromJSON), 'optional_null');
	const list_Opt = propMappedValue('list_Opt', $value, isRecord, v => isListReplace(v, isString) ? ListReplaceFromJSON(v, isString, ZoneIdFromJSON) : ListMergeAddRemoveFromJSON(v, isString, ZoneIdFromJSON, isString, ZoneIdFromJSON), 'optional_null');
	const list_Opt_Null = propMappedValue('list_Opt_Null', $value, isRecord, v => isListReplace(v, isString) ? ListReplaceFromJSON(v, isString, ZoneIdFromJSON) : ListMergeAddRemoveFromJSON(v, isString, ZoneIdFromJSON, isString, ZoneIdFromJSON), 'optional_null');
	return {
		key,
		version,
		value,
		value_Null,
		value_Opt,
		value_Opt_Null,
		list,
		list_Null,
		list_Opt,
		list_Opt_Null,
	};
}

export function PatchableScalarRecordPatchToJSON($value: PatchableScalarRecordPatch): Record<string, unknown> {
	const key = RSDStringToJSON($value.key);
	const version = RSDStringToJSON($value.version);
	const value = $value.value;
	const value_Null = $value.value_Null;
	const value_Opt = $value.value_Opt;
	const value_Opt_Null = $value.value_Opt_Null;
	const list = $value.list;
	const list_Null = $value.list_Null;
	const list_Opt = $value.list_Opt;
	const list_Opt_Null = $value.list_Opt_Null;

	return {
		key,
		version,
		value,
		value_Null,
		value_Opt,
		value_Opt_Null,
		list,
		list_Null,
		list_Opt,
		list_Opt_Null,
	};
}

