import { CompositeGeneratorNode, NL, toString } from 'langium/generate';

import { Artifact } from '../artifact-generator.js';
import { JavaClientAPIGeneratorConfig, toPath } from '../java-gen-utils.js';
import { MResolvedError, MResolvedService } from '../model.js';

export type ServiceErrorCombination = {
	interfaceName: string;
	errorNames: readonly string[];
};

export function computeServiceErrorCombination(
	services: readonly MResolvedService[],
): Map<string, ServiceErrorCombination> {
	const errorNames = new Map<string, ServiceErrorCombination>();
	services
		.flatMap(s => s.operations)
		.forEach(op => {
			if (op.operationErrors.length > 0) {
				const key = op.operationErrors
					.map(e => e.error)
					.toSorted((e1, e2) => e1.localeCompare(e2))
					.join(',');
				if (!errorNames.has(key)) {
					errorNames.set(key, {
						interfaceName: `E${(errorNames.size + 1).toFixed()}`,
						errorNames: op.operationErrors.map(e => e.error),
					});
				}
			}
		});
	return errorNames;
}

function generateTypeContent(errors: readonly MResolvedError[]) {
	const node = new CompositeGeneratorNode();
	node.append('public enum Type {', NL);
	node.indent(classBody => {
		classBody.append('_Native,', NL);
		if (errors.length > 0) {
			classBody.append('_UnknownResponse,', NL);
		} else {
			classBody.append('_UnknownResponse;', NL);
		}
		errors
			.map(e => e.name)
			.toSorted((e1, e2) => e1.localeCompare(e2))
			.forEach((name, idx, arr) => {
				classBody.append(name, idx + 1 < arr.length ? ',' : ';', NL);
			});
	});
	node.append('}', NL, NL);
	return node;
}

export function generateServiceErrors(
	artifactConfig: JavaClientAPIGeneratorConfig,
	services: readonly MResolvedService[],
	errors: readonly MResolvedError[],
): Artifact {
	const packageName = artifactConfig.rootPackageName;

	const errs = errors.map(e => e.name).toSorted((e1, e2) => e1.localeCompare(e2));
	errs.unshift('RSDError.$GenericError');

	const node = new CompositeGeneratorNode();
	node.append(`// Generated by RSD - Do not modify`, NL);
	node.append(`package ${packageName};`, NL, NL);
	node.append(`public sealed interface RSDError permits ${errs.join(', ')} {`, NL);
	node.indent(body => {
		body.append(generateTypeContent(errors));
		body.append('public Type type();', NL, NL);
		const errorNames = [...computeServiceErrorCombination(services).values()];
		errorNames.forEach(({ interfaceName, errorNames }) => {
			const errorList = errorNames.slice();
			body.append(`public sealed interface ${interfaceName} permits $GenericError, ${errorList.join(', ')} {`, NL);
			body.append('}', NL, NL);
		});
		body.append(
			`public record $GenericError(Type type, String message, Throwable error) implements RSDError${
				errorNames.length > 0 ? ', ' + errorNames.map(({ interfaceName }) => interfaceName).join(', ') : ''
			} {`,
			NL,
		);
		body.append('}', NL);
	});
	node.append('}', NL);

	return {
		name: 'RSDError.java',
		content: toString(node, '\t'),
		path: toPath(artifactConfig.targetFolder, packageName),
	};
}
